### ISSUE TITLE
editing of timeperiods templates not possible

### ISSUE THREAD

**Issue by vita2** [Icinga/icingaweb2-module-director#1028]
hello tom,

if i want to edit a timeperiod template i get a "page not found" error.
![notifications-template](https://user-images.githubusercontent.com/25298055/28457292-d6d49490-6e05-11e7-957a-e1b07d344364.png)

when i click on the treeview button i see a more detailed error message:
![notifications-templates-treeview](https://user-images.githubusercontent.com/25298055/28457293-d6db0064-6e05-11e7-8a88-b85dc711813f.png)
```
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'icingaweb2director.icinga_timePeriod' doesn't exist, query was: SELECT o.id, o.object_name AS name, o.object_type, p.id AS parent_id, p.object_name AS parent_name FROM icinga_timePeriod AS o
 LEFT JOIN icinga_timePeriod_inheritance AS i ON o.id = i.timePeriod_id
 LEFT JOIN icinga_timePeriod AS p ON p.id = i.parent_timePeriod_id AND p.object_type = 'template' WHERE (o.object_type = 'template') ORDER BY o.id ASC, i.weight ASC (Pdo.php:225)
 
 
#0 /usr/share/icingaweb2/library/vendor/Zend/Db/Statement.php(297): Zend_Db_Statement_Pdo->_execute(Array)
#1 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Abstract.php(470): Zend_Db_Statement->execute(Array)
#2 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Pdo/Abstract.php(232): Zend_Db_Adapter_Abstract->query(Object(Zend_Db_Select), Array)
#3 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Abstract.php(725): Zend_Db_Adapter_Pdo_Abstract->query(Object(Zend_Db_Select), Array)
#4 /usr/share/icingaweb2/modules/director/library/Director/Resolver/TemplateTree.php(259): Zend_Db_Adapter_Abstract->fetchAll(Object(Zend_Db_Select))
#5 /usr/share/icingaweb2/modules/director/library/Director/Resolver/TemplateTree.php(179): Icinga\Module\Director\Resolver\TemplateTree->fetchTemplates()
#6 /usr/share/icingaweb2/modules/director/library/Director/Resolver/TemplateTree.php(146): Icinga\Module\Director\Resolver\TemplateTree->prepareTree()
#7 /usr/share/icingaweb2/modules/director/library/Director/Web/Tree/TemplateTreeRenderer.php(44): Icinga\Module\Director\Resolver\TemplateTree->getTree()
#8 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/BaseElement.php(133): Icinga\Module\Director\Web\Tree\TemplateTreeRenderer->renderContent()
#9 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/Html.php(139): ipl\Html\BaseElement->render()
#10 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/BaseElement.php(105): ipl\Html\Html->render()
#11 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/BaseElement.php(133): ipl\Html\BaseElement->renderContent()
#12 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/Html.php(227): ipl\Html\BaseElement->render()
#13 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Zf1/SimpleViewRenderer.php(47): ipl\Html\Html->__toString()
#14 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Zf1/SimpleViewRenderer.php(66): ipl\Zf1\SimpleViewRenderer->render()
#15 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker.php(272): ipl\Zf1\SimpleViewRenderer->postDispatch()
#16 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(518): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#17 /usr/share/icingaweb2/library/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('templatesAction')
#18 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#19 /usr/share/icingaweb2/library/Icinga/Application/Web.php(389): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#20 /usr/share/icingaweb2/library/Icinga/Application/webrouter.php(104): Icinga\Application\Web->dispatch()
#21 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/icin...')
#22 {main}
```

## Possible Solution
is there a uppercase typo in the table name "icinga_time(P)eriod" and "icinga_time(P)eriod_inheritance"?

## Your Environment
* Director version (System - About): commit bf65f668a7cbebf41c5ebd4d56cfe54caf3141ad in master branch
* Icinga Web 2 version and modules (System - About): 2.4.1
* Icinga 2 version (`icinga2 --version`): r2.6.3-1
* Operating System and version: Debian Jessie 8.8 (3.16.0-4-amd64)
* Webserver, PHP versions: nginx 1.6.2-5 + php5-fpm 5.6.30

**Comment by tobiasvdk** [comment]
Looks like the same issue as #1032. I think the director is missing functionality here. The views for the e.g. the service templates are very new (at least to me).

**Comment by Thomas-Gelf** [comment]
Related code is missing. Will push it immediately. Some related add object/template links are still wrong, will also be fixed. Thanks for reporting this!
