### ISSUE TITLE
Error occurred, when using "assign where IN"

### ISSUE THREAD

**Issue by Foxeronie** [Icinga/icingaweb2-module-director#1068]
Hi,

I'm on the current master and getting an error, when I select "IN" for an assign where rule.

## Error message
```
Plugin by name 'FormExtensibleSet' was not found in the registry; used paths:
Zend_View_Helper_: Zend/View/Helper/:/usr/share/icingaweb2/application/views/helpers/:/usr/share/icingaweb2/modules/director/application/views/helpers/ (PluginLoader.php:418)
```
```
#0 /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php(1168): Zend_Loader_PluginLoader->load('FormExtensibleS...')
#1 /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php(610): Zend_View_Abstract->_getPlugin('helper', 'formExtensibleS...')
#2 /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php(340): Zend_View_Abstract->getHelper('formExtensibleS...')
#3 /usr/share/icingaweb2/library/Icinga/Web/View.php(250): Zend_View_Abstract->__call('formExtensibleS...', Array)
#4 /usr/share/icingaweb2/modules/director/application/views/helpers/FormDataFilter.php(226): Icinga\Web\View->__call('formExtensibleS...', Array)
#5 /usr/share/icingaweb2/modules/director/application/views/helpers/FormDataFilter.php(226): Icinga\Web\View->formExtensibleSet('assign_filter[i...', Array)
#6 /usr/share/icingaweb2/modules/director/application/views/helpers/FormDataFilter.php(184): Zend_View_Helper_FormDataFilter->text(Object(Icinga\Data\Filter\FilterMatch))
#7 /usr/share/icingaweb2/modules/director/application/views/helpers/FormDataFilter.php(144): Zend_View_Helper_FormDataFilter->element(Object(Icinga\Data\Filter\FilterMatch))
#8 /usr/share/icingaweb2/modules/director/application/views/helpers/FormDataFilter.php(153): Zend_View_Helper_FormDataFilter->filterExpressionHtml(Object(Icinga\Data\Filter\FilterMatch))
#9 /usr/share/icingaweb2/modules/director/application/views/helpers/FormDataFilter.php(73): Zend_View_Helper_FormDataFilter->renderFilterExpression(Object(Icinga\Data\Filter\FilterMatch))
#10 /usr/share/icingaweb2/modules/director/application/views/helpers/FormDataFilter.php(93): Zend_View_Helper_FormDataFilter->renderFilter(Object(Icinga\Data\Filter\FilterMatch))
#11 /usr/share/icingaweb2/modules/director/application/views/helpers/FormDataFilter.php(71): Zend_View_Helper_FormDataFilter->renderFilterChain(Object(Icinga\Data\Filter\FilterNot))
#12 /usr/share/icingaweb2/modules/director/application/views/helpers/FormDataFilter.php(93): Zend_View_Helper_FormDataFilter->renderFilter(Object(Icinga\Data\Filter\FilterNot))
#13 /usr/share/icingaweb2/modules/director/application/views/helpers/FormDataFilter.php(71): Zend_View_Helper_FormDataFilter->renderFilterChain(Object(Icinga\Data\Filter\FilterAnd))
#14 /usr/share/icingaweb2/modules/director/application/views/helpers/FormDataFilter.php(93): Zend_View_Helper_FormDataFilter->renderFilter(Object(Icinga\Data\Filter\FilterAnd))
#15 /usr/share/icingaweb2/modules/director/application/views/helpers/FormDataFilter.php(71): Zend_View_Helper_FormDataFilter->renderFilterChain(Object(Icinga\Data\Filter\FilterAnd))
#16 /usr/share/icingaweb2/modules/director/application/views/helpers/FormDataFilter.php(64): Zend_View_Helper_FormDataFilter->renderFilter(Object(Icinga\Data\Filter\FilterAnd))
#17 [internal function]: Zend_View_Helper_FormDataFilter->formDataFilter('assign_filter', Object(Icinga\Data\Filter\FilterAnd), Array, NULL)
#18 /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php(346): call_user_func_array(Array, Array)
#19 /usr/share/icingaweb2/library/Icinga/Web/View.php(250): Zend_View_Abstract->__call('formDataFilter', Array)
#20 /usr/share/icingaweb2/library/vendor/Zend/Form/Decorator/ViewHelper.php(254): Icinga\Web\View->__call('formDataFilter', Array)
#21 /usr/share/icingaweb2/library/vendor/Zend/Form/Decorator/ViewHelper.php(254): Icinga\Web\View->formDataFilter('assign_filter', Object(Icinga\Data\Filter\FilterAnd), Array, NULL)
#22 /usr/share/icingaweb2/library/vendor/Zend/Form/Element.php(2048): Zend_Form_Decorator_ViewHelper->render('')
#23 /usr/share/icingaweb2/library/vendor/Zend/Form/Decorator/FormElements.php(115): Zend_Form_Element->render()
#24 /usr/share/icingaweb2/library/vendor/Zend/Form/DisplayGroup.php(914): Zend_Form_Decorator_FormElements->render('')
#25 /usr/share/icingaweb2/library/vendor/Zend/Form/Decorator/FormElements.php(115): Zend_Form_DisplayGroup->render()
#26 /usr/share/icingaweb2/library/vendor/Zend/Form.php(2974): Zend_Form_Decorator_FormElements->render('')
#27 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/Html.php(171): Zend_Form->render()
#28 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/BaseElement.php(105): ipl\Html\Html->render()
#29 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/BaseElement.php(133): ipl\Html\BaseElement->renderContent()
#30 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/Html.php(259): ipl\Html\BaseElement->render()
#31 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Zf1/SimpleViewRenderer.php(47): ipl\Html\Html->__toString()
#32 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Zf1/SimpleViewRenderer.php(66): ipl\Zf1\SimpleViewRenderer->render()
#33 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker.php(272): ipl\Zf1\SimpleViewRenderer->postDispatch()
#34 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(518): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#35 /usr/share/icingaweb2/library/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('editAction')
#36 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#37 /usr/share/icingaweb2/library/Icinga/Application/Web.php(389): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#38 /usr/share/icingaweb2/library/Icinga/Application/webrouter.php(104): Icinga\Application\Web->dispatch()
#39 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/icin...')
#40 {main}
```
## Your Environment
```
Version	1.3.1
Git commit	7fd94fb5bdb63057916f18e541654fc30143a9e2
```
```
Version
2.4.1
Git commit
824f625d19b191bd619910975150b51f486d6a05
```
```
icinga2 - The Icinga 2 network monitoring daemon (version: r2.7.0-1)

Copyright (c) 2012-2017 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: Ubuntu
  Platform version: 14.04.5 LTS, Trusty Tahr
  Kernel: Linux
  Kernel version: 3.13.0-121-generic
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.2
  Build host: e1e9a326f1b8
```
```
Ubuntu 14.04.5 LTS 
```
```
Server version: Apache/2.4.7 (Ubuntu)
PHP 5.5.9-1ubuntu4.21 (cli) (built: Feb  9 2017 20:54:58) 
```

Best regards,
Patrick

**Comment by Foxeronie** [comment]
Heyho,

can you reproduce this error? I'm currently can't edit my Apply Rules because of that and I want to know if this is a problem on my side.

Best regards,
Patrick

**Comment by Thomas-Gelf** [comment]
I can reproduce this, it's a bug.

**Comment by Thomas-Gelf** [comment]
I pushed a fix, please give it a try and let me know in case you're still experiencing related issues.
