### ISSUE TITLE
Fetchticket with Powershell-Module

### ISSUE THREAD

**Issue by vittel1** [Icinga/icingaweb2-module-director#1079]
Hi,

I am using the Powershell-Module (https://github.com/Icinga/icinga2-powershell-module) for the configuration of my Windows Host. I guess this is a problem of the director therefore I am posting it here.
Maybe someon has an explanation? 

Director Version: 1.3.1
Git commit : 7fd94fb5bdb63057916f18e541654fc30143a9e2

If you need other information, please ask. Thanks!

```
Fatal: Exception calling "fetchTicketFromIcingaDirector" with "0" argument(s): "Failed to fetch ticket for host HOSTNAME. Got <br />
<b>Fatal error</b>:  Uncaught Error: Call to a member function getResolvedProperty() on null in /usr/share/icingaweb2/modules/director/application/controllers/HostController.ph
p:586
Stack trace:
#0 /usr/share/icingaweb2/modules/director/library/Director/Web/Controller/ObjectController.php(44): Icinga\Module\Director\Controllers\HostController-&gt;handleApiRequest()
#1 /usr/share/php/Icinga/Web/Controller/ActionController.php(139): Icinga\Module\Director\Web\Controller\ObjectController-&gt;init()
#2 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(59): Icinga\Web\Controller\ActionController-&gt;__construct(Object(Icinga\Web\Request), Object(Icinga\Web\Response), Arra
y)
#3 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher-&gt;dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#4 /usr/share/php/Icinga/Application/Web.php(389): Zend_Controller_Front-&gt;dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#5 /usr/share/php/Icinga/Application/webrouter.php(109): Icing in <b>/usr/share/icingaweb2/modules/director/application/controllers/HostController.php</b> on line <b>586</b><br
 />
 as ticket."
######## The script encountered several errors during run ########
Fatal: Exception calling "fetchTicketFromIcingaDirector" with "0" argument(s): "Failed to fetch ticket for host HOSTNAME. Got <br />
<b>Fatal error</b>:  Uncaught Error: Call to a member function getResolvedProperty() on null in /usr/share/icingaweb2/modules/director/application/controllers/HostController.ph
p:586
Stack trace:
#0 /usr/share/icingaweb2/modules/director/library/Director/Web/Controller/ObjectController.php(44): Icinga\Module\Director\Controllers\HostController-&gt;handleApiRequest()
#1 /usr/share/php/Icinga/Web/Controller/ActionController.php(139): Icinga\Module\Director\Web\Controller\ObjectController-&gt;init()
#2 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(59): Icinga\Web\Controller\ActionController-&gt;__construct(Object(Icinga\Web\Request), Object(Icinga\Web\Response), Arra
y)
#3 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher-&gt;dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#4 /usr/share/php/Icinga/Application/Web.php(389): Zend_Controller_Front-&gt;dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#5 /usr/share/php/Icinga/Application/webrouter.php(109): Icing in <b>/usr/share/icingaweb2/modules/director/application/controllers/HostController.php</b> on line <b>586</b><br
 />
 as ticket."

```

Call the Powershell-Module like this:
```

$icinga = Icinga2AgentModule `
    -AgentName       'HOSTNAME' `
    -DirectorUrl          'https://icinga-master/icingaweb2/director/' `
    -DirectorUser         'fetchticketuser' `
    -DirectorPassword     $adminpassword `
    -ParentZone           'master' `
    -ParentEndpoints      'icinga-master' -EndpointsConfig 'icinga-master;5665'`
    -CAServer             'icinga-master'

exit $icinga.installMonitoringComponents();
```

**Comment by Thomas-Gelf** [comment]
Seems that you're using the GIT master at some point in time. The related issue should have been fixed, I pushed another related commit right now. In case you're still facing issues please let me know.
