### ISSUE TITLE
regression? opening information about a non existing host results in a crash.

### ISSUE THREAD

**Issue by hboetes** [Icinga/icingaweb2-module-director#1092]
This problem is related to https://github.com/theforeman/smart_proxy_monitoring/issues/14

If I try to add a new host via the foreman webinterface to icinga, the foreman-proxy will ask the director if said host exists: With recent releases the director throws an error. I don't know what the previous behaviour was but I guess it replied the host did not exist.

Opening this URL results in the following crash: https://icinga01.example.org/icingaweb2/director/host?name=nonexistant

```
#0 /usr/share/icingaweb2/modules/director/library/Director/Data/Db/DbObject.php(1081): Icinga\Module\Director\Data\Db\DbObject->loadFromDb()
#1 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObject.php(2343): Icinga\Module\Director\Data\Db\DbObject::load('nonexistant', Object(Icinga\Module\Director\Db))
#2 /usr/share/icingaweb2/modules/director/library/Director/Web/Controller/ObjectController.php(336): Icinga\Module\Director\Objects\IcingaObject::loadByType('host', 'nonexistant', Object(Icinga\Module\Director\Db))
#3 /usr/share/icingaweb2/modules/director/library/Director/Web/Controller/ObjectController.php(319): Icinga\Module\Director\Web\Controller\ObjectController->loadObject()
#4 /usr/share/icingaweb2/modules/director/library/Director/Web/Controller/ObjectController.php(45): Icinga\Module\Director\Web\Controller\ObjectController->eventuallyLoadObject()
#5 /usr/share/php/Icinga/Web/Controller/ActionController.php(139): Icinga\Module\Director\Web\Controller\ObjectController->init()
#6 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(59): Icinga\Web\Controller\ActionController->__construct(Object(Icinga\Web\Request), Object(Icinga\Web\Response), Array)
#7 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#8 /usr/share/php/Icinga/Application/Web.php(389): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#9 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
#10 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#11 {main}
```

Director: latest from git
Icinga: latest from packages

**Comment by Thomas-Gelf** [comment]
@hboetes: HTTP response codes are wrong, I'll immediately push a fix. Btw, what you're showing doesn't happen when issuing a REST API request - you need to pass `Accept: application/json` as a header to simulate such.

**Comment by Thomas-Gelf** [comment]
@hboetes: could you please try again?

**Comment by hboetes** [comment]
@Thomas-Gelf 
Thanks! Now it works again! Thanks for the heads up on using the rest api.
