### ISSUE TITLE
Delete entries from "assign where in" doesn't work

### ISSUE THREAD

**Issue by Foxeronie** [Icinga/icingaweb2-module-director#1100]
Hey,

when I try to delete a host from a "assign where in" rule via the delete icon the following happens:

Before:
![assign_where_in_before](https://user-images.githubusercontent.com/10115997/29614133-536835bc-8809-11e7-8989-b1a8a941178a.png)

After:
![assign_where_in_after](https://user-images.githubusercontent.com/10115997/29614140-5bdee81c-8809-11e7-8fe8-27ea2ff90b6a.png)

Database apply_filter field before:
host.name=%5B%22it-puppet01%22%2C%22it-puppet02%22%2C%22it-puppet03%22%2C%22it-puppet04%22%2C%22it-puppet05%22%2C%22it-puppet06%22%2C%22it-puppet-ca02%22%5D

Database apply_filter field after:
host.name=%5B%22%5Cue804%22%5D

If I delete the string of one entry and press enter the following error occours:
```
htmlspecialchars() expects parameter 1 to be string, object given (View.php:88)
#0 [internal function]: Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(2, 'htmlspecialchar...', '/usr/share/icin...', 88, Array)
#1 /usr/share/icingaweb2/library/Icinga/Web/View.php(88): htmlspecialchars(Object(stdClass), 58, 'UTF-8', true)
#2 /usr/share/icingaweb2/library/vendor/Zend/View/Helper/FormText.php(70): Icinga\Web\View->escape(Object(stdClass))
#3 [internal function]: Zend_View_Helper_FormText->formText('assign_filter[i...', Object(stdClass))
#4 /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php(346): call_user_func_array(Array, Array)
#5 /usr/share/icingaweb2/library/Icinga/Web/View.php(250): Zend_View_Abstract->__call('formText', Array)
#6 /usr/share/icingaweb2/modules/director/application/views/helpers/FormDataFilter.php(234): Icinga\Web\View->__call('formText', Array)
#7 /usr/share/icingaweb2/modules/director/application/views/helpers/FormDataFilter.php(234): Icinga\Web\View->formText('assign_filter[i...', Object(stdClass))
#8 /usr/share/icingaweb2/modules/director/application/views/helpers/FormDataFilter.php(184): Zend_View_Helper_FormDataFilter->text(Object(Icinga\Data\Filter\FilterMatch))
#9 /usr/share/icingaweb2/modules/director/application/views/helpers/FormDataFilter.php(144): Zend_View_Helper_FormDataFilter->element(Object(Icinga\Data\Filter\FilterMatch))
#10 /usr/share/icingaweb2/modules/director/application/views/helpers/FormDataFilter.php(153): Zend_View_Helper_FormDataFilter->filterExpressionHtml(Object(Icinga\Data\Filter\FilterMatch))
#11 /usr/share/icingaweb2/modules/director/application/views/helpers/FormDataFilter.php(73): Zend_View_Helper_FormDataFilter->renderFilterExpression(Object(Icinga\Data\Filter\FilterMatch))
#12 /usr/share/icingaweb2/modules/director/application/views/helpers/FormDataFilter.php(64): Zend_View_Helper_FormDataFilter->renderFilter(Object(Icinga\Data\Filter\FilterMatch))
#13 [internal function]: Zend_View_Helper_FormDataFilter->formDataFilter('assign_filter', Object(Icinga\Data\Filter\FilterMatch), Array, NULL)
#14 /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php(346): call_user_func_array(Array, Array)
#15 /usr/share/icingaweb2/library/Icinga/Web/View.php(250): Zend_View_Abstract->__call('formDataFilter', Array)
#16 /usr/share/icingaweb2/library/vendor/Zend/Form/Decorator/ViewHelper.php(254): Icinga\Web\View->__call('formDataFilter', Array)
#17 /usr/share/icingaweb2/library/vendor/Zend/Form/Decorator/ViewHelper.php(254): Icinga\Web\View->formDataFilter('assign_filter', Object(Icinga\Data\Filter\FilterMatch), Array, NULL)
#18 /usr/share/icingaweb2/library/vendor/Zend/Form/Element.php(2048): Zend_Form_Decorator_ViewHelper->render('')
#19 /usr/share/icingaweb2/library/vendor/Zend/Form/Decorator/FormElements.php(115): Zend_Form_Element->render()
#20 /usr/share/icingaweb2/library/vendor/Zend/Form/DisplayGroup.php(914): Zend_Form_Decorator_FormElements->render('')
#21 /usr/share/icingaweb2/library/vendor/Zend/Form/Decorator/FormElements.php(115): Zend_Form_DisplayGroup->render()
#22 /usr/share/icingaweb2/library/vendor/Zend/Form.php(2974): Zend_Form_Decorator_FormElements->render('')
#23 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/Html.php(171): Zend_Form->render()
#24 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/BaseElement.php(105): ipl\Html\Html->render()
#25 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/BaseElement.php(133): ipl\Html\BaseElement->renderContent()
#26 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/Html.php(259): ipl\Html\BaseElement->render()
#27 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Zf1/SimpleViewRenderer.php(47): ipl\Html\Html->__toString()
#28 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Zf1/SimpleViewRenderer.php(66): ipl\Zf1\SimpleViewRenderer->render()
#29 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker.php(272): ipl\Zf1\SimpleViewRenderer->postDispatch()
#30 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(518): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#31 /usr/share/icingaweb2/library/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('indexAction')
#32 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#33 /usr/share/icingaweb2/library/Icinga/Application/Web.php(389): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#34 /usr/share/icingaweb2/library/Icinga/Application/webrouter.php(104): Icinga\Application\Web->dispatch()
#35 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/icin...')
#36 {main}
```

And the database field has this string:
```
host.name=%7B%221%22%3A%22it-puppet02%22%2C%222%22%3A%22it-puppet03%22%2C%223%22%3A%22it-puppet04%22%2C%224%22%3A%22it-puppet05%22%2C%225%22%3A%22it-puppet06%22%2C%226%22%3A%22it-puppet-ca02%22%7D
```

## Expected Behavior
Be able to delete single values in a "assign where in" rule.

## Current Behavior
Broken rule or error message

## Possible Solution
Edit database field

## Steps to Reproduce (for bugs)
Create a assign where rule with some values and delete one.

## Your Environment
Director:
```
current master
Git commit 71ab8b4663b799d45bac42b366d21575fb755d0e
```

Icinga Web 2:
```
2.4.1
Git commit a66b036ab28d500615f0e6c5bbd704849d8582f6
```

Icinga 2:
```
icinga2 - The Icinga 2 network monitoring daemon (version: r2.7.0-1)

Copyright (c) 2012-2017 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: Ubuntu
  Platform version: 14.04.5 LTS, Trusty Tahr
  Kernel: Linux
  Kernel version: 3.13.0-121-generic
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.2
  Build host: e1e9a326f1b8
Ubuntu 14.04.5 LTS 
Server version: Apache/2.4.7 (Ubuntu)
PHP 5.5.9-1ubuntu4.21 (cli) (built: Feb  9 2017 20:54:58) 
```

**Comment by Thomas-Gelf** [comment]
@Foxeronie: can be reproduced, thanks for reporting this!
