### ISSUE TITLE
 Invalid text representation while adding new host

### ISSUE THREAD

**Issue by TheCapsLock** [Icinga/icingaweb2-module-director#1101]
```
SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: ""
LINE 2: ... f ON df.id = f.datafield_id WHERE (f.host_id IN ('')) ORDER...
^, query was: SELECT f.host_id AS object_id, ('host') AS icinga_type, f.var_filter, f.is_required, df.id, df.varname, df.caption, df.description, df.datatype, df.format FROM director_datafield AS df
INNER JOIN icinga_host_field AS f ON df.id = f.datafield_id WHERE (f.host_id IN ('')) ORDER BY CASE WHEN var_filter IS NULL THEN 0 ELSE 1 END ASC, df.caption ASC

#0 /usr/share/icingaweb2/library/vendor/Zend/Db/Statement.php(297): Zend_Db_Statement_Pdo->_execute(Array)
#1 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Abstract.php(470): Zend_Db_Statement->execute(Array)
#2 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Pdo/Abstract.php(232): Zend_Db_Adapter_Abstract->query('SELECT f.host_i...', Array)
#3 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Abstract.php(725): Zend_Db_Adapter_Pdo_Abstract->query(Object(Zend_Db_Select), Array)
#4 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/IcingaObjectFieldLoader.php(468): Zend_Db_Adapter_Abstract->fetchAll(Object(Zend_Db_Select))
#5 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/IcingaObjectFieldLoader.php(453): Icinga\Module\Director\Web\Form\IcingaObjectFieldLoader->fetchFieldDetailsForIds(Array)
#6 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/IcingaObjectFieldLoader.php(519): Icinga\Module\Director\Web\Form\IcingaObjectFieldLoader->fetchFieldDetailsForObject(Object(Icinga\Module\Director\Objects\IcingaHost))
#7 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/IcingaObjectFieldLoader.php(415): Icinga\Module\Director\Web\Form\IcingaObjectFieldLoader->loadDataFieldsForObject(Object(Icinga\Module\Director\Objects\IcingaHost))
#8 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/IcingaObjectFieldLoader.php(376): Icinga\Module\Director\Web\Form\IcingaObjectFieldLoader->loadResolvedFieldsForObject(Object(Icinga\Module\Director\Objects\IcingaHost))
#9 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/IcingaObjectFieldLoader.php(160): Icinga\Module\Director\Web\Form\IcingaObjectFieldLoader->prepareObjectFields(Object(Icinga\Module\Director\Objects\IcingaHost))
#10 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/IcingaObjectFieldLoader.php(333): Icinga\Module\Director\Web\Form\IcingaObjectFieldLoader->getFields()
#11 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/IcingaObjectFieldLoader.php(176): Icinga\Module\Director\Web\Form\IcingaObjectFieldLoader->createElements(Object(Icinga\Module\Director\Forms\IcingaHostForm))
#12 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/IcingaObjectFieldLoader.php(193): Icinga\Module\Director\Web\Form\IcingaObjectFieldLoader->getElements(Object(Icinga\Module\Director\Forms\IcingaHostForm))
#13 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/DirectorObjectForm.php(377): Icinga\Module\Director\Web\Form\IcingaObjectFieldLoader->prepareElements(Object(Icinga\Module\Director\Forms\IcingaHostForm))
#14 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/DirectorObjectForm.php(690): Icinga\Module\Director\Web\Form\DirectorObjectForm->prepareFields(Object(Icinga\Module\Director\Objects\IcingaHost))
#15 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(496): Icinga\Module\Director\Web\Form\DirectorObjectForm->onRequest()
#16 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(508): Icinga\Module\Director\Web\Form\QuickForm->setRequest(Object(Icinga\Web\Request))
#17 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(367): Icinga\Module\Director\Web\Form\QuickForm->getRequest()
#18 /usr/share/icingaweb2/modules/director/library/Director/Web/Controller/ObjectController.php(86): Icinga\Module\Director\Web\Form\QuickForm->handleRequest()
#19 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Director\Web\Controller\ObjectController->addAction()
#20 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('addAction')
#21 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#22 /usr/share/php/Icinga/Application/Web.php(389): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#23 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
#24 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#25 {main}
```
## Expected Behavior
On icinga director, ones wants to add a new host. On hosts list, shes clicks on "add" then should fill the form.

## Current Behavior
Since 8bc26ccb973b381949385a65cef064194f657e43 error above is displayed in place of host form.

## Steps to Reproduce (for bugs)
1. Install a fresh icinga2 ; icingaweb2 and director
2. add a host

## Your Environment

* Director version : master
* Icinga Web 2 version and modules : 2.4.1
*   Monitoring : 2.4.1
*   Doc : 2.4.1
* Icinga 2 version : r2.7.0-1
* Operating System and version: GNU/Linux Debian stretch 9.0
* Webserver, PHP versions: nginx/1.10.3 ; php 7.0.19

**Comment by Thomas-Gelf** [comment]
Duplicates #1102, has been fixed - thanks for reporting this!
