### ISSUE TITLE
'Invalid text representation' error when adding hosts/services/etc

### ISSUE THREAD

**Issue by XNRL** [Icinga/icingaweb2-module-director#1102]
Clicking on the 'add' link opens an empty side panel (occasionally with trace) and the word 'Error' in bottom left corner. Opening 'error' link in a new tab gives the trace. For example:

```
SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: ""
LINE 2: ... f ON df.id = f.datafield_id WHERE (f.host_id IN ('')) ORDER...
^, query was: SELECT f.host_id AS object_id, ('host') AS icinga_type, f.var_filter, f.is_required, df.id, df.varname, df.caption, df.description, df.datatype, df.format FROM director_datafield AS df
INNER JOIN icinga_host_field AS f ON df.id = f.datafield_id WHERE (f.host_id IN ('')) ORDER BY CASE WHEN var_filter IS NULL THEN 0 ELSE 1 END ASC, df.caption ASC

#0 /usr/share/icingaweb2/library/vendor/Zend/Db/Statement.php(297): Zend_Db_Statement_Pdo->_execute(Array)
#1 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Abstract.php(470): Zend_Db_Statement->execute(Array)
#2 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Pdo/Abstract.php(232): Zend_Db_Adapter_Abstract->query(Object(Zend_Db_Select), Array)
#3 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Abstract.php(725): Zend_Db_Adapter_Pdo_Abstract->query(Object(Zend_Db_Select), Array)
#4 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/IcingaObjectFieldLoader.php(468): Zend_Db_Adapter_Abstract->fetchAll(Object(Zend_Db_Select))
#5 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/IcingaObjectFieldLoader.php(453): Icinga\Module\Director\Web\Form\IcingaObjectFieldLoader->fetchFieldDetailsForIds(Array)
#6 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/IcingaObjectFieldLoader.php(519): Icinga\Module\Director\Web\Form\IcingaObjectFieldLoader->fetchFieldDetailsForObject(Object(Icinga\Module\Director\Objects\IcingaHost))
#7 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/IcingaObjectFieldLoader.php(416): Icinga\Module\Director\Web\Form\IcingaObjectFieldLoader->loadDataFieldsForObject(Object(Icinga\Module\Director\Objects\IcingaHost))
#8 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/IcingaObjectFieldLoader.php(376): Icinga\Module\Director\Web\Form\IcingaObjectFieldLoader->loadResolvedFieldsForObject(Object(Icinga\Module\Director\Objects\IcingaHost))
#9 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/IcingaObjectFieldLoader.php(160): Icinga\Module\Director\Web\Form\IcingaObjectFieldLoader->prepareObjectFields(Object(Icinga\Module\Director\Objects\IcingaHost))
#10 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/IcingaObjectFieldLoader.php(333): Icinga\Module\Director\Web\Form\IcingaObjectFieldLoader->getFields()
#11 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/IcingaObjectFieldLoader.php(176): Icinga\Module\Director\Web\Form\IcingaObjectFieldLoader->createElements(Object(Icinga\Module\Director\Forms\IcingaHostForm))
#12 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/IcingaObjectFieldLoader.php(193): Icinga\Module\Director\Web\Form\IcingaObjectFieldLoader->getElements(Object(Icinga\Module\Director\Forms\IcingaHostForm))
#13 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/DirectorObjectForm.php(423): Icinga\Module\Director\Web\Form\IcingaObjectFieldLoader->prepareElements(Object(Icinga\Module\Director\Forms\IcingaHostForm))
#14 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/DirectorObjectForm.php(742): Icinga\Module\Director\Web\Form\DirectorObjectForm->prepareFields(Object(Icinga\Module\Director\Objects\IcingaHost))
#15 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(500): Icinga\Module\Director\Web\Form\DirectorObjectForm->onRequest()
#16 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(512): Icinga\Module\Director\Web\Form\QuickForm->setRequest(Object(Icinga\Web\Request))
#17 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(367): Icinga\Module\Director\Web\Form\QuickForm->getRequest()
#18 /usr/share/icingaweb2/modules/director/library/Director/Web/Controller/ObjectController.php(103): Icinga\Module\Director\Web\Form\QuickForm->handleRequest()
#19 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Director\Web\Controller\ObjectController->addAction()
#20 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('addAction')
#21 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#22 /usr/share/php/Icinga/Application/Web.php(389): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#23 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
#24 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#25 {main}
```

The issue is present for the following menus: hosts and host templates, services, service templates and service apply rules, commands and command templates. Probably some others.
Host and service groups addition is working as intended.

* Director version: git master, latest commit 71ab8b4663b799d45bac42b366d21575fb755d0e 
* Icinga Web 2 version and modules: 2.4.1
* Operating System and version: Debian 8, 4.9.0-0.bpo.3-amd64 inside LXC container
* Webserver, PHP versions: nginx 1.6.2-5+deb8u4, PHP 5.6.30+dfsg-0+deb8u1
* Database: postgres 9.4+165+deb8u2

**Comment by TobiasKneidl** [comment]
Same here. But only on my PostgreSQL installation. With a MySQL database, there's no problem.

**Comment by Thomas-Gelf** [comment]
@TobiasKneidl: thanks for pointing this out, I can reproduce it - will be fixed
