### ISSUE TITLE
'Undefined function' error when searching commands

### ISSUE THREAD

**Issue by TobiasKneidl** [Icinga/icingaweb2-module-director#1109]
Searching in commands gives the following trace: 

```
SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: enum_object_type_all ~~ unknown
LINE 1: ...HERE (o.object_name LIKE '%ser%' OR o.object_type LIKE '%ser...
                                                             ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts., query was: SELECT COUNT(*) AS cnt FROM icinga_command AS o WHERE (o.object_name LIKE '%ser%' OR o.object_type LIKE '%ser%' OR o.command LIKE '%ser%') AND (object_type = 'external_object') (Pdo.php:225)
#0 /usr/share/icingaweb2/library/vendor/Zend/Db/Statement.php(297): Zend_Db_Statement_Pdo->_execute(Array)
#1 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Abstract.php(470): Zend_Db_Statement->execute(Array)
#2 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Pdo/Abstract.php(232): Zend_Db_Adapter_Abstract->query('SELECT COUNT(*)...', Array)
#3 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Abstract.php(816): Zend_Db_Adapter_Pdo_Abstract->query(Object(Zend_Db_Select), Array)
#4 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Db/Zf1/SelectPaginationAdapter.php(33): Zend_Db_Adapter_Abstract->fetchOne(Object(Zend_Db_Select))
#5 [internal function]: ipl\Db\Zf1\SelectPaginationAdapter->count()
#6 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Web/Widget/Paginator.php(134): count(Object(ipl\Db\Zf1\SelectPaginationAdapter))
#7 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Web/Widget/Paginator.php(115): ipl\Web\Widget\Paginator->getTotalItemCount()
#8 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Web/Widget/Paginator.php(457): ipl\Web\Widget\Paginator->getPageCount()
#9 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/Html.php(171): ipl\Web\Widget\Paginator->render()
#10 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/BaseElement.php(105): ipl\Html\Html->render()
#11 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/BaseElement.php(133): ipl\Html\BaseElement->renderContent()
#12 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/Html.php(171): ipl\Html\BaseElement->render()
#13 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/BaseElement.php(105): ipl\Html\Html->render()
#14 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Web/Widget/Controls.php(148): ipl\Html\BaseElement->renderContent()
#15 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/BaseElement.php(133): ipl\Web\Widget\Controls->renderContent()
#16 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/Html.php(259): ipl\Html\BaseElement->render()
#17 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Zf1/SimpleViewRenderer.php(44): ipl\Html\Html->__toString()
#18 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Zf1/SimpleViewRenderer.php(66): ipl\Zf1\SimpleViewRenderer->render()
#19 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker.php(272): ipl\Zf1\SimpleViewRenderer->postDispatch()
#20 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(518): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#21 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('indexAction')
#22 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#23 /usr/share/php/Icinga/Application/Web.php(389): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#24 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
#25 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#26 {main}
```

* Director version: git master, latest commit bd0ccc6
* Icinga Web 2 version and modules: 2.4.1
* Operating System and version: Ubuntu Server 16.04
* Database: PostgreSQL 9.5.8

Happens again only with a PostgreSQL Database, MySQL works.

**Comment by Thomas-Gelf** [comment]
@TobiasKneidl: thanks again! Problem here is that object_type is an enum, and it isn't possibly to use string operators on enum columns without casting them to string in PostgreSQL. So, using `object_type::text` when `$this->isPgsql()` would fix this. However, searching for object_type is pointless here since we now have different tables for different types. Will be fixed immediately!
