### ISSUE TITLE
Error by adding a service to a single host

### ISSUE THREAD

**Issue by TobiasKneidl** [Icinga/icingaweb2-module-director#1112]
Trying to add a service to a single host gives the following trace: 

```
Declaration of Icinga\Module\Director\Forms\IcingaAddServiceForm::groupMainProperties() should be compatible with Icinga\Module\Director\Web\Form\DirectorObjectForm::groupMainProperties($importsFirst = false)

#0 /usr/share/icingaweb2/modules/director/application/forms/IcingaAddServiceForm.php(9): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(2, 'Declaration of ...', '/usr/share/icin...', 9, Array)
#1 /usr/share/php/Icinga/Application/ClassLoader.php(306): require('/usr/share/icin...')
#2 [internal function]: Icinga\Application\ClassLoader->loadClass('Icinga\\Module\\D...')
#3 /usr/share/icingaweb2/modules/director/application/controllers/HostController.php(49): spl_autoload_call('Icinga\\Module\\D...')
#4 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Director\Controllers\HostController->serviceAction()
#5 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('serviceAction')
#6 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#7 /usr/share/php/Icinga/Application/Web.php(389): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#8 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
#9 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#10 {main}
```

* Director version: git master, latest commit bd0ccc6
* Icinga Web 2 version and modules: 2.4.1
* Operating System and version: Ubuntu Server 16.04
* Database: PostgreSQL 9.5.8

**Comment by Thomas-Gelf** [comment]
Thanks again :-)
