### ISSUE TITLE
Restoring the service set object removes its template

### ISSUE THREAD

**Issue by darmagan** [Icinga/icingaweb2-module-director#1115]
This works if the set is assigned to host in the service set screen. But if the set is added trough the host it runs into dependency issues.

This issue references to #1107.

## Expected Behavior
If restoring the removed set, dependencies should be checked.

## Current Behavior
Object exists in DB without the template it is referenced from.

## Steps to Reproduce (for bugs)
1. create service set
2. add to host(from Host konfiguration screen)
DB looks like this:
mysql> select * from icinga_service_set\G
*************************** 1. row ***************************
           id: 6
  object_name: newServiceSet
  object_type: template
      host_id: NULL
  description: NULL
assign_filter: NULL
*************************** 2. row ***************************
           id: 7
  object_name: newServiceSet
  object_type: object
      host_id: 2
  description: NULL
assign_filter: NULL
2 rows in set (0.00 sec)

3. delete Set from Host
DB:
mysql> select * from icinga_service_set\G
*************************** 1. row ***************************
           id: 6
  object_name: newServiceSet
  object_type: template
      host_id: NULL
  description: NULL
assign_filter: NULL
1 row in set (0.01 sec)

4. on delete service set "" -> Restore former object
Error: Failed to load icinga_service_set for host_id IS NULL AND object_name = 'newServiceSet' (DbObject.php:583)
DB:
mysql> select * from icinga_service_set\G
*************************** 1. row ***************************
           id: 6
  object_name: newServiceSet
  object_type: object
      host_id: 2
  description: NULL
assign_filter: NULL
1 row in set (0.00 sec)

it's now an object, the template is missing.

In the director the service set is not listed on the host(isn't existing).

## Context
I want to restore service set objects.

## Your Environment

>git status
HEAD detached at v1.3.2
nothing to commit, working directory clean

>git log -n 1
commit c4a97692df23e428a2eb6f1be41a7c25ea7b19a4
Author: Thomas Gelf <thomas@gelf.net>
Date:   Thu Jul 20 18:12:43 2017 +0200

    module.info: prepare v1.3.2

Regards

**Comment by darmagan** [comment]
I tested this again with the recent master:
´´´
# git log -1
commit f7353b66283ee3f11e15fd5d616a690ac7b72c4c
Author: Thomas Gelf <thomas@gelf.net>
Date:   Tue Sep 12 15:51:33 2017 +0200

    IcingaObject: allow to load Choices by type
    
    fixes #1129
´´´
The problem is still persistent, with the difference that the Service Set is existing in the hosts service set listing. But if I select it I get an 'undefined offset'

Undefined offset: 2
´´´
#0 /usr/share/icingaweb2/modules/director/library/Director/Resolver/TemplateTree.php(186): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(8, 'Undefined offse...', '/usr/share/icin...', 186, Array)
#1 /usr/share/icingaweb2/modules/director/library/Director/Resolver/TemplateTree.php(126): Icinga\Module\Director\Resolver\TemplateTree->getParentsById('2')
#2 /usr/share/icingaweb2/modules/director/library/Director/Resolver/TemplateTree.php(105): Icinga\Module\Director\Resolver\TemplateTree->getParentsFor(Object(Icinga\Module\Director\Objects\IcingaServiceSet))
#3 /usr/share/icingaweb2/modules/director/library/Director/Repository/IcingaTemplateRepository.php(40): Icinga\Module\Director\Resolver\TemplateTree->listParentIdsFor(Object(Icinga\Module\Director\Objects\IcingaServiceSet))
#4 /usr/share/icingaweb2/modules/director/library/Director/Repository/IcingaTemplateRepository.php(79): Icinga\Module\Director\Repository\IcingaTemplateRepository->getTemplatesFor(Object(Icinga\Module\Director\Objects\IcingaServiceSet), false)
#5 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObjectImports.php(278): Icinga\Module\Director\Repository\IcingaTemplateRepository->getTemplatesIndexedByNameFor(Object(Icinga\Module\Director\Objects\IcingaServiceSet))
#6 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObjectImports.php(350): Icinga\Module\Director\Objects\IcingaObjectImports->loadFromDb()
#7 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObject.php(806): Icinga\Module\Director\Objects\IcingaObjectImports::loadForStoredObject(Object(Icinga\Module\Director\Objects\IcingaServiceSet))
#8 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObject.php(2745): Icinga\Module\Director\Objects\IcingaObject->imports()
#9 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObject.php(1419): Icinga\Module\Director\Objects\IcingaObject->getPlainUnmodifiedObject()
#10 /usr/share/icingaweb2/modules/director/library/Director/Data/Db/DbObject.php(942): Icinga\Module\Director\Objects\IcingaObject->beforeDelete()
#11 /usr/share/icingaweb2/modules/director/application/controllers/HostController.php(271): Icinga\Module\Director\Data\Db\DbObject->delete()
#12 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Director\Controllers\HostController->removesetAction()
#13 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('removesetAction')
#14 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#15 /usr/share/php/Icinga/Application/Web.php(389): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#16 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
#17 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#18 {main}
´´´

In the DB the template is missing like before:
´´´
mysql> select * from icinga_service_set;
+----+-------------+-------------+---------+-------------+---------------+
| id | object_name | object_type | host_id | description | assign_filter |
+----+-------------+-------------+---------+-------------+---------------+
|  2 | fdfgd       | object      |       2 | NULL        | NULL          |
+----+-------------+-------------+---------+-------------+---------------+
1 row in set (0.00 sec)

´´´

Regards

**Comment by opticgeist** [comment]
darmagan,  were you able to find solution or work-around to this issue?

**Comment by darmagan** [comment]
there is no real solution/work-around for this, it should be avoided to use the restore functionality for Service-Sets.

**Comment by opticgeist** [comment]
Thank you for your diligence and posting your investigation.

**Comment by lazyfrosch** [comment]
Basically the template object is updated to a normal object, which inherits itself.

All services are still attached, but the service set is no longer visible in the UI and breaks rendering of the configuration.

See all sets and inheritance:

```
MariaDB [icingaweb2]> select * from icinga_service_set s LEFT JOIN icinga_service_set_inheritance ssi ON ssi.service_set_id = s.id;
+----+-------------+-------------+---------+-------------+------------------------------+----------------+-----------------------+--------+
| id | object_name | object_type | host_id | description | assign_filter                | service_set_id | parent_service_set_id | weight |
+----+-------------+-------------+---------+-------------+------------------------------+----------------+-----------------------+--------+
|  1 | cust1       | template    |    NULL | NULL        | NULL                         |           NULL |                  NULL |   NULL |
|  2 | cust1-test  | template    |    NULL | NULL        | NULL                         |           NULL |                  NULL |   NULL |
|  4 | test        | template    |    NULL | NULL        | host.address=%221.1.1.%2A%22 |           NULL |                  NULL |   NULL |
|  5 | test2       | object      |      16 | NULL        | NULL                         |              5 |                     5 |      1 |
|  6 | test2       | object      |      17 | NULL        | NULL                         |              6 |                     5 |      1 |
+----+-------------+-------------+---------+-------------+------------------------------+----------------+-----------------------+--------+
5 rows in set (0.00 sec)
```

ID 5 is here the problem

To revert the failed restore:

```sql
UPDATE icinga_service_set SET object_type = 'template', host_id = NULL WHERE id = 5;
DELETE FROM icinga_service_set_inheritance WHERE service_set_id = 5;
```

This should fix the main service set, but won't assign the set back to the host.
