### ISSUE TITLE
Error while adding Service to Host Template

### ISSUE THREAD

**Issue by cptnkoiz** [Icinga/icingaweb2-module-director#1118]
## Expected Behavior
It works ;D

## Current Behavior
It doesn't.

While clicking on "Add Service"
![bildschirmfoto 2017-08-25 um 14 47 36](https://user-images.githubusercontent.com/24245068/29714729-af7fd16a-89a4-11e7-9363-bf85472a899f.png)

Selecting any Service from the Dropdown and saving results in this

![bildschirmfoto 2017-08-25 um 14 47 54](https://user-images.githubusercontent.com/24245068/29714740-bc3fbca8-89a4-11e7-8155-594c14464080.png)

```
#0 /usr/share/icingaweb2/modules/director/library/Director/Resolver/TemplateTree.php(105): Icinga\Module\Director\Resolver\TemplateTree->getParentsFor(Object(Icinga\Module\Director\Objects\IcingaService))
#1 /usr/share/icingaweb2/modules/director/library/Director/Repository/IcingaTemplateRepository.php(40): Icinga\Module\Director\Resolver\TemplateTree->listParentIdsFor(Object(Icinga\Module\Director\Objects\IcingaService))
#2 /usr/share/icingaweb2/modules/director/library/Director/Repository/IcingaTemplateRepository.php(79): Icinga\Module\Director\Repository\IcingaTemplateRepository->getTemplatesFor(Object(Icinga\Module\Director\Objects\IcingaService), false)
#3 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObject.php(1128): Icinga\Module\Director\Repository\IcingaTemplateRepository->getTemplatesIndexedByNameFor(Object(Icinga\Module\Director\Objects\IcingaService))
#4 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObject.php(993): Icinga\Module\Director\Objects\IcingaObject->resolve('Vars')
#5 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObject.php(1036): Icinga\Module\Director\Objects\IcingaObject->resolveVars()
#6 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObject.php(988): Icinga\Module\Director\Objects\IcingaObject->getInherited('Vars')
#7 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObject.php(919): Icinga\Module\Director\Objects\IcingaObject->getInheritedVars()
#8 /usr/share/icingaweb2/modules/director/library/Director/Objects/DirectorDatafield.php(112): Icinga\Module\Director\Objects\IcingaObject->getInheritedVar('Service_Notific...')
#9 /usr/share/icingaweb2/modules/director/library/Director/Objects/DirectorDatafield.php(97): Icinga\Module\Director\Objects\DirectorDatafield->applyObjectData(Object(Zend_Form_Element_Select), Object(Icinga\Module\Director\Forms\IcingaAddServiceForm))
#10 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/IcingaObjectFieldLoader.php(335): Icinga\Module\Director\Objects\DirectorDatafield->getFormElement(Object(Icinga\Module\Director\Forms\IcingaAddServiceForm))
#11 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/IcingaObjectFieldLoader.php(177): Icinga\Module\Director\Web\Form\IcingaObjectFieldLoader->createElements(Object(Icinga\Module\Director\Forms\IcingaAddServiceForm))
#12 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/IcingaObjectFieldLoader.php(194): Icinga\Module\Director\Web\Form\IcingaObjectFieldLoader->getElements(Object(Icinga\Module\Director\Forms\IcingaAddServiceForm))
#13 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/DirectorObjectForm.php(426): Icinga\Module\Director\Web\Form\IcingaObjectFieldLoader->prepareElements(Object(Icinga\Module\Director\Forms\IcingaAddServiceForm))
#14 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/DirectorObjectForm.php(755): Icinga\Module\Director\Web\Form\DirectorObjectForm->prepareFields(Object(Icinga\Module\Director\Objects\IcingaService))
#15 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(500): Icinga\Module\Director\Web\Form\DirectorObjectForm->onRequest()
#16 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(512): Icinga\Module\Director\Web\Form\QuickForm->setRequest(Object(Icinga\Web\Request))
#17 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(367): Icinga\Module\Director\Web\Form\QuickForm->getRequest()
#18 /usr/share/icingaweb2/modules/director/application/controllers/HostController.php(52): Icinga\Module\Director\Web\Form\QuickForm->handleRequest()
#19 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Director\Controllers\HostController->serviceAction()
#20 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('serviceAction')
#21 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#22 /usr/share/php/Icinga/Application/Web.php(389): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#23 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
#24 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#25 {main}
```

## Your Environment

* Director version (System - About): Master
* Icinga Web 2 version and modules (System - About): 2.4.1
* Icinga 2 version (`icinga2 --version`): 2.7.0
* Operating System and version: CentOS7
* Webserver, PHP versions: Apache2/HTTPD

**Comment by cptnkoiz** [comment]
+ Happens also when adding a Service Set.

**Comment by Thomas-Gelf** [comment]
Ouch, this is new

**Comment by cptnkoiz** [comment]
Today is Break & Fix day :)

**Comment by Thomas-Gelf** [comment]
Should have been broken 40 minutes ago, please try again.

**Comment by cptnkoiz** [comment]
Yes! Already fixed. Thank you :)

**Comment by Thomas-Gelf** [comment]
You're welcome, thanks for reporting it!
