### ISSUE TITLE
Can't add host to single service

### ISSUE THREAD

**Issue by TheCry** [Icinga/icingaweb2-module-director#1170]
## Current Behavior
``Failed to load icinga_service for host_id IS NULL AND service_set_id IS NULL AND object_name = 'system_disks' AND object_type = 'template'``

``#0 /usr/share/icingaweb2/modules/director/library/Director/Data/Db/DbObject.php(1081): Icinga\Module\Director\Data\Db\DbObject->loadFromDb()
#1 /usr/share/icingaweb2/modules/director/application/controllers/ServiceController.php(247): Icinga\Module\Director\Data\Db\DbObject::load(Array, Object(Icinga\Module\Director\Db))
#2 /usr/share/icingaweb2/modules/director/library/Director/Web/Controller/ObjectController.php(328): Icinga\Module\Director\Controllers\ServiceController->loadObject()
#3 /usr/share/icingaweb2/modules/director/library/Director/Web/Controller/ObjectController.php(62): Icinga\Module\Director\Web\Controller\ObjectController->eventuallyLoadObject()
#4 /usr/share/icingaweb2/modules/director/application/controllers/ServiceController.php(43): Icinga\Module\Director\Web\Controller\ObjectController->init()
#5 /usr/share/php/Icinga/Web/Controller/ActionController.php(139): Icinga\Module\Director\Controllers\ServiceController->init()
#6 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(59): Icinga\Web\Controller\ActionController->__construct(Object(Icinga\Web\Request), Object(Icinga\Web\Response), Array)
#7 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#8 /usr/share/php/Icinga/Application/Web.php(389): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#9 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
#10 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#11 {main}``

## Steps to Reproduce (for bugs)

1. Icinga Director
2. Services
3. Single Servcies
4. Klick on service

## Your Environment

* Director version (System - About): master
* Icinga Web 2 version and modules (System - About):
director	master
doc	2.4.1
grafana	1.1.10
map	1.0.3
monitoring	2.4.1
setup	2.4.1
translation	2.4.1
* Icinga 2 version (`icinga2 --version`): icinga2 - The Icinga 2 network monitoring daemon (version: r2.7.0-1)
* Operating System and version: Debian 9
* Webserver, PHP versions: 
Server version: Apache/2.4.25 (Debian)
PHP 7.0.19-1
Server built:   2017-07-18T18:37:33

**Comment by Thomas-Gelf** [comment]
@TheCry: are these red services like shown in #1172?

**Comment by TheCry** [comment]
Yes.. This is the same

**Comment by Thomas-Gelf** [comment]
@TheCry: ok, thank you
