### ISSUE TITLE
Formatted error message instead of stacktrace when trying to delete used command

### ISSUE THREAD

**Issue by sysadmama** [Icinga/icingaweb2-module-director#1192]
When you try to delete a command which is currently in use by Service Template, an *Integrity constraint violation* stacktrace appears. It would be nice (and less shocking btw) to have a meaningful error message instead. 

Cheers!

## Stacktrace
```
#0 /usr/share/icingaweb2/library/vendor/Zend/Db/Statement.php(297): Zend_Db_Statement_Pdo->_execute(Array)
#1 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Abstract.php(470): Zend_Db_Statement->execute(Array)
#2 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Pdo/Abstract.php(232): Zend_Db_Adapter_Abstract->query('DELETE FROM ici...', Array)
#3 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Abstract.php(652): Zend_Db_Adapter_Pdo_Abstract->query('DELETE FROM ici...')
#4 /usr/share/icingaweb2/modules/director/library/Director/Data/Db/DbObject.php(820): Zend_Db_Adapter_Abstract->delete('icinga_command', '(id = 80)')
#5 /usr/share/icingaweb2/modules/director/library/Director/Data/Db/DbObject.php(943): Icinga\Module\Director\Data\Db\DbObject->deleteFromDb()
#6 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/DirectorObjectForm.php(842): Icinga\Module\Director\Data\Db\DbObject->delete()
#7 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/DirectorObjectForm.php(776): Icinga\Module\Director\Web\Form\DirectorObjectForm->deleteObject(Object(Icinga\Module\Director\Objects\IcingaCommand))
#8 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/DirectorObjectForm.php(762): Icinga\Module\Director\Web\Form\DirectorObjectForm->handlePost()
#9 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(520): Icinga\Module\Director\Web\Form\DirectorObjectForm->onRequest()
#10 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(532): Icinga\Module\Director\Web\Form\QuickForm->setRequest(Object(Icinga\Web\Request))
#11 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(367): Icinga\Module\Director\Web\Form\QuickForm->getRequest()
#12 /usr/share/icingaweb2/modules/director/library/Director/Web/Controller/ObjectController.php(403): Icinga\Module\Director\Web\Form\QuickForm->handleRequest()
#13 /usr/share/icingaweb2/modules/director/library/Director/Web/Controller/ObjectController.php(112): Icinga\Module\Director\Web\Controller\ObjectController->addObjectForm(Object(Icinga\Module\Director\Objects\IcingaCommand))
#14 /usr/share/icingaweb2/modules/director/library/Director/Web/Controller/ObjectController.php(79): Icinga\Module\Director\Web\Controller\ObjectController->editAction()
#15 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Director\Web\Controller\ObjectController->indexAction()
#16 /usr/share/icingaweb2/library/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('indexAction')
#17 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#18 /usr/share/icingaweb2/library/Icinga/Application/Web.php(389): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#19 /usr/share/icingaweb2/library/Icinga/Application/webrouter.php(104): Icinga\Application\Web->dispatch()
#20 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/icin...')
#21 {main}
```

## Your Environment

* Director version (System - About): f7353b66283ee3f11e15fd5d616a690ac7b72c4c
* Icinga Web 2 version and modules (System - About): b7639651e80e85b81d9fb92c1db77e90c3754d2d
* Icinga 2 version (`icinga2 --version`): r2.7.0-1
* Operating System and version: Ubuntu-16.04
* Webserver, PHP versions: apache2, php7

**Comment by Thomas-Gelf** [comment]
This is no longer an issue with v1.5.x
