### ISSUE TITLE
Backlink to nowhere when cloning service for host

### ISSUE THREAD

**Issue by sysadmama** [Icinga/icingaweb2-module-director#1202]
## Steps to Reproduce (for bugs)
1. Modify a host and add a service to it
2. Select this newly created service, hit *Clone*
3. Hit link *back*
4. Get stacktrace

```
Failed to load icinga_service for host_id IS NULL AND service_set_id IS NULL AND object_name = 'Bacula Backup' AND object_type = 'template'

#0 /usr/share/icingaweb2/modules/director/library/Director/Data/Db/DbObject.php(1081): Icinga\Module\Director\Data\Db\DbObject->loadFromDb()
#1 /usr/share/icingaweb2/modules/director/application/controllers/ServiceController.php(252): Icinga\Module\Director\Data\Db\DbObject::load(Array, Object(Icinga\Module\Director\Db))
#2 /usr/share/icingaweb2/modules/director/library/Director/Web/Controller/ObjectController.php(328): Icinga\Module\Director\Controllers\ServiceController->loadObject()
#3 /usr/share/icingaweb2/modules/director/library/Director/Web/Controller/ObjectController.php(62): Icinga\Module\Director\Web\Controller\ObjectController->eventuallyLoadObject()
#4 /usr/share/icingaweb2/modules/director/application/controllers/ServiceController.php(43): Icinga\Module\Director\Web\Controller\ObjectController->init()
#5 /usr/share/icingaweb2/library/Icinga/Web/Controller/ActionController.php(152): Icinga\Module\Director\Controllers\ServiceController->init()
#6 /usr/share/icingaweb2/library/Icinga/Web/Controller/Dispatcher.php(59): Icinga\Web\Controller\ActionController->__construct(Object(Icinga\Web\Request), Object(Icinga\Web\Response), Array)
#7 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#8 /usr/share/icingaweb2/library/Icinga/Application/Web.php(389): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#9 /usr/share/icingaweb2/library/Icinga/Application/webrouter.php(104): Icinga\Application\Web->dispatch()
#10 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/icin...')
#11 {main}
````
Cheers,
  Marianne

## Your Environment

* Director version (System - About): still f7353b66283ee3f11e15fd5d616a690ac7b72c4c
* Icinga Web 2 version and modules (System - About): b7639651e80e85b81d9fb92c1db77e90c3754d2d
* Icinga 2 version (`icinga2 --version`): r2.7.1-1
* Operating System and version: Ubuntu 16.04
* Webserver, PHP versions: apache2/ php7

**Comment by Thomas-Gelf** [comment]
Works fine in current master, didn't test v1.4.x.
