### ISSUE TITLE
Got invalid parent id 2 for timeperiod

### ISSUE THREAD

**Issue by kbks** [Icinga/icingaweb2-module-director#1224]
## Expected Behavior

Should deploy changes as usual.

## Current Behavior

Shows error **Got invalid parent id 2 for timeperiod "24x7_logrotate"**

## Steps to Reproduce (for bugs)

1. Configure Timeperiod in director 1.3.2
2. Update to director 1.4.0 and apply new scheme suggested after upgrade
3. Change any object and try to deploy. 

## Context

In object list i can see this Timeperiod

```
$ icinga2 object list --type Timeperiod --name "24x7_logrotate"                                                      
Object '24x7_logrotate' of type 'TimePeriod':
  % declared in '/var/lib/icinga2/api/packages/director/jessica-1507545415-1/zones.d/director-global/timeperiods.conf', lines 44:1-44:34
  * __name = "24x7_logrotate"
  * display_name = "24x7 excluding 00:00am to 00:45am"
    % = modified in '/var/lib/icinga2/api/packages/director/jessica-1507545415-1/zones.d/director-global/timeperiod_templates.conf', lines 3:5-3:25
    % = modified in '/var/lib/icinga2/api/packages/director/jessica-1507545415-1/zones.d/director-global/timeperiods.conf', lines 16:5-16:25
    % = modified in '/var/lib/icinga2/api/packages/director/jessica-1507545415-1/zones.d/director-global/timeperiods.conf', lines 48:5-48:54
  * excludes = [ ]
  * includes = [ ]
  * name = "24x7_logrotate"
  * package = "director"
  * prefer_includes = true
  * ranges
    % = modified in '/var/lib/icinga2/api/packages/director/jessica-1507545415-1/zones.d/director-global/timeperiod_templates.conf', lines 4:5-12:5
    % = modified in '/var/lib/icinga2/api/packages/director/jessica-1507545415-1/zones.d/director-global/timeperiods.conf', lines 17:5-25:5
    % = modified in '/var/lib/icinga2/api/packages/director/jessica-1507545415-1/zones.d/director-global/timeperiods.conf', lines 49:5-57:5
    * friday = "00:45-24:00"
    * monday = "00:45-24:00"
    * saturday = "00:45-24:00"
    * sunday = "00:45-24:00"
    * thursday = "00:45-24:00"
    * tuesday = "00:45-24:00"
    * wednesday = "00:45-24:00"
  * source_location
    * first_column = 1
    * first_line = 44
    * last_column = 34
    * last_line = 44
    * path = "/var/lib/icinga2/api/packages/director/jessica-1507545415-1/zones.d/director-global/timeperiods.conf"
  * templates = [ "24x7_logrotate", "legacy-timeperiod", "legacy-timeperiod", "24x7", "legacy-timeperiod", "legacy-timeperiod", "Template", "legacy-timeperiod" ]
    % = modified in '/var/lib/icinga2/api/packages/director/jessica-1507545415-1/zones.d/director-global/timeperiods.conf', lines 44:1-44:34
    % = modified in 'icinga-itl.conf', lines 23:2-23:64
    % = modified in 'icinga-itl.conf', lines 23:2-23:64
    % = modified in '/var/lib/icinga2/api/packages/director/jessica-1507545415-1/zones.d/director-global/timeperiods.conf', lines 12:1-12:24
    % = modified in 'icinga-itl.conf', lines 23:2-23:64
    % = modified in 'icinga-itl.conf', lines 23:2-23:64
    % = modified in '/var/lib/icinga2/api/packages/director/jessica-1507545415-1/zones.d/director-global/timeperiod_templates.conf', lines 1:0-1:29
    % = modified in 'icinga-itl.conf', lines 23:2-23:64
  * type = "TimePeriod"
  * update
    % = modified in 'icinga-itl.conf', lines 24:3-24:37
    % = modified in 'icinga-itl.conf', lines 24:3-24:37
    % = modified in 'icinga-itl.conf', lines 24:3-24:37
    % = modified in 'icinga-itl.conf', lines 24:3-24:37
    % = modified in 'icinga-itl.conf', lines 24:3-24:37
    * arguments = [ "tp", "begin", "end" ]
    * deprecated = false
    * name = "Internal#LegacyTimePeriod"
    * side_effect_free = false
    * type = "Function"
  * vars = null
  * zone = "director-global"
```

But if to try show it via director-cli

```
$ icingacli director timeperiod show 24x7_logrotate                                                         
PHP Notice:  Icinga\Exception\ConfigurationError: Got invalid parent id 2 for timeperiod "24x7_logrotate" in /usr/share/icingaweb2/modules/director/library/Director/Resolver/TemplateTree.php:62
Stack trace:
#0 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObject.php(2642): Icinga\Module\Director\Resolver\TemplateTree->listParentNamesFor(Object(Icinga\Module\Director\Objects\IcingaTimePeriod))
#1 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObject.php(850): Icinga\Module\Director\Objects\IcingaObject->listImportNames()
#2 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObject.php(1595): Icinga\Module\Director\Objects\IcingaObject->getImports()
#3 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObject.php(2202): Icinga\Module\Director\Objects\IcingaObject->renderImports()
#4 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObject.php(2796): Icinga\Module\Director\Objects\IcingaObject->toConfigString()
#5 /usr/sh in /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObject.php on line 2798

Notice: Icinga\Exception\ConfigurationError: Got invalid parent id 2 for timeperiod "24x7_logrotate" in /usr/share/icingaweb2/modules/director/library/Director/Resolver/TemplateTree.php:62
Stack trace:
#0 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObject.php(2642): Icinga\Module\Director\Resolver\TemplateTree->listParentNamesFor(Object(Icinga\Module\Director\Objects\IcingaTimePeriod))
#1 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObject.php(850): Icinga\Module\Director\Objects\IcingaObject->listImportNames()
#2 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObject.php(1595): Icinga\Module\Director\Objects\IcingaObject->getImports()
#3 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObject.php(2202): Icinga\Module\Director\Objects\IcingaObject->renderImports()
#4 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObject.php(2796): Icinga\Module\Director\Objects\IcingaObject->toConfigString()
#5 /usr/sh in /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObject.php on line 2798
```

As a result cant deploy anything. 

![screen shot 2017-10-10 at 5 19 56 pm](https://user-images.githubusercontent.com/6768503/31392333-ac23d60e-ade1-11e7-8d8c-c410814d39af.png)
![screen shot 2017-10-10 at 5 06 15 pm](https://user-images.githubusercontent.com/6768503/31392335-ac573b48-ade1-11e7-9696-1abf8e7e7654.png)

## Your Environment

* Director version (System - About): 1.4.0
* Icinga Web 2 version (System - About): 2.4.1
* Icinga 2 version (`icinga2 --version`): 2.7.1
* Operating System and version: Ubuntu 16.04
* Webserver, PHP versions: Apache 2.4.18, PHP 7.0.22
* Mysql: 5.7.19

**Comment by Thomas-Gelf** [comment]
@kbks: looks like an older version broke something with your inheritance. v1.4.0 is more strict and prefers to bail when it encounters weirdness.

Please show me the output of:
```sql
SELECT id, object_name FROM icinga_timeperiod;
SELECT * FROM icinga_timeperiod_inheritance;
```

**Comment by kbks** [comment]
Sure Thomas. Here you go

```
mysql> SELECT id, object_name FROM icinga_timeperiod;
+----+-------------------+
| id | object_name       |
+----+-------------------+
|  2 | 24x7              |
|  7 | 24x7_backup       |
|  3 | 24x7_jefflogminer |
|  4 | 24x7_logrotate    |
|  5 | nonworkhours      |
|  9 | Template          |
|  6 | weekend           |
|  1 | workhours         |
+----+-------------------+
8 rows in set (0.01 sec)

mysql> SELECT * FROM icinga_timeperiod_inheritance;
+---------------+----------------------+--------+
| timeperiod_id | parent_timeperiod_id | weight |
+---------------+----------------------+--------+
|             2 |                    9 |      1 |
|             3 |                    9 |      1 |
|             4 |                    2 |      1 |
|             5 |                    2 |      1 |
+---------------+----------------------+--------+
4 rows in set (0.01 sec)
```

**Comment by Thomas-Gelf** [comment]
One more please, forgot a column:

```sql
SELECT id, object_name, object_type FROM icinga_timeperiod;
```

Sorry.

**Comment by kbks** [comment]
No problem.
```

mysql> SELECT id, object_name, object_type FROM icinga_timeperiod;
+----+-------------------+-------------+
| id | object_name       | object_type |
+----+-------------------+-------------+
|  1 | workhours         | object      |
|  2 | 24x7              | object      |
|  3 | 24x7_jefflogminer | object      |
|  4 | 24x7_logrotate    | object      |
|  5 | nonworkhours      | object      |
|  6 | weekend           | object      |
|  7 | 24x7_backup       | object      |
|  9 | Template          | template    |
+----+-------------------+-------------+
8 rows in set (0.00 sec)
```

**Comment by Thomas-Gelf** [comment]
Ok, the problem is that `24x7` is not a template, but you're inheriting from it. While this could in theory be allowed (you might want to open a related feature request), it is currently rejected. Director currently allows only Commands to inherit from other Objects.

Is your 24x7 TimePeriod currently in use by any Host, Service, Notification or so?

**Comment by kbks** [comment]
Yes it does. 
Converted 24x7 to timeperiod template, added new 24x7 timeperiod object (object and template with different names). Changed where it was complaining and have a successful deploy as a result. 

Thank you @Thomas-Gelf!

**Comment by Thomas-Gelf** [comment]
Glad to hear that - and sorry for the inconvenience.
