### ISSUE TITLE
SQL error when inspecting template choices

### ISSUE THREAD

**Issue by terra-nova** [Icinga/icingaweb2-module-director#1242]
Setting up a new host template choice through the UI works, but selecting existing choice objects in the list view results in a database error.

```
SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: "Test"
LINE 1: ...template_choice_id IS NULL OR o.template_choice_id = 'Test')
^, query was: SELECT o.object_name AS k, o.object_name AS v FROM icinga_host AS o WHERE (o.object_type = 'template') AND (o.template_choice_id IS NULL OR o.template_choice_id = 'Test')
```

In the above case, "Test" is the name of the choice object, but `template_choice_id` is defined as an `integer` field in the database.

The above error is with a director db on PostgreSQL, but I guess MySQL users would be affected as well.

## Expected Behavior

Selecting a choice object should fire up the object editing form.

## Current Behavior

A database error prevents the editing view from being shown.

## Steps to Reproduce (for bugs)

1. Create new host template choice
2. Select newly created object from list view
3. SQL Error prevents edit view from being displayed

## Your Environment

* Director version (System - About): 1.4.0
* Icinga Web 2 version and modules (System - About): 2.4.2
* Icinga 2 version (`icinga2 --version`): 2.7.1-1
* Operating System and version: CentOS 7 7.4 x64
* Webserver, PHP versions: Apache 2.4.6, PHP 5.4

**Comment by terra-nova** [comment]
Oops, I forgot the stack trace ...

```
#0 /usr/share/icingaweb2/library/vendor/Zend/Db/Statement.php(297): Zend_Db_Statement_Pdo->_execute(Array)
#1 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Abstract.php(470): Zend_Db_Statement->execute(Array)
#2 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Pdo/Abstract.php(232): Zend_Db_Adapter_Abstract->query(Object(Zend_Db_Select), Array)
#3 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Abstract.php(799): Zend_Db_Adapter_Pdo_Abstract->query(Object(Zend_Db_Select), Array)
#4 /usr/share/icingaweb2/modules/director/application/forms/IcingaTemplateChoiceForm.php(119): Zend_Db_Adapter_Abstract->fetchPairs(Object(Zend_Db_Select))
#5 /usr/share/icingaweb2/modules/director/application/forms/IcingaTemplateChoiceForm.php(69): Icinga\Module\Director\Forms\IcingaTemplateChoiceForm->fetchUnboundTemplates()
#6 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(356): Icinga\Module\Director\Forms\IcingaTemplateChoiceForm->setup()
#7 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(517): Icinga\Module\Director\Web\Form\QuickForm->prepareElements()
#8 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(530): Icinga\Module\Director\Web\Form\QuickForm->setRequest(Object(Icinga\Web\Request))
#9 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(367): Icinga\Module\Director\Web\Form\QuickForm->getRequest()
#10 /usr/share/icingaweb2/modules/director/application/controllers/TemplatechoiceController.php(30): Icinga\Module\Director\Web\Form\QuickForm->handleRequest()
#11 /usr/share/icingaweb2/modules/director/application/controllers/TemplatechoiceController.php(17): Icinga\Module\Director\Controllers\TemplatechoiceController->prepare('host', 'Host template c...')
#12 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Director\Controllers\TemplatechoiceController->hostAction()
#13 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('hostAction')
#14 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#15 /usr/share/php/Icinga/Application/Web.php(389): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#16 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
#17 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#18 {main}
```

**Comment by terra-nova** [comment]
The following patch works for me.

```
# git diff IcingaTemplateChoiceForm.php
diff --git a/application/forms/IcingaTemplateChoiceForm.php b/application/forms/IcingaTemplateChoiceForm.php
index c3388fb..35beb28 100644
--- a/application/forms/IcingaTemplateChoiceForm.php
+++ b/application/forms/IcingaTemplateChoiceForm.php
@@ -110,7 +110,7 @@ class IcingaTemplateChoiceForm extends DirectorObjectForm
         if ($object->hasBeenLoadedFromDb()) {
             $query->where(
                 'o.template_choice_id IS NULL OR o.template_choice_id = ?',
-                $this->object()->getId()
+                $this->object()->get('id')
             );
         } else {
             $query->where('o.template_choice_id IS NULL');
```

**Comment by terra-nova** [comment]
reopen to give Thomas a chance to comment on the problem..

I have no idea whether the getId() function is incorrectly returning the object name instead of the id and needs to be fixed instead of patching IcingaTemplateChoiceForm.php, for example...

**Comment by Thomas-Gelf** [comment]
Thanks @terra-nova, both for reporting and fixing this. `getId` is an ancient special beast and should better have had a different name from the beginning. It gives you the property uniquely identifying an object. And while this is the auto-incrementing `id` in many cases, it is not so for most `IcingaObject` types, as wherever possible we are using their `object_name` to identify them.

Would you like to send me a pull request for this or should I just fix it? It's a small one, but hey, credits belong to you - so IMO the commit should carry your name!

Cheers,
Thomas

**Comment by Thomas-Gelf** [comment]
Merged, thank you!
