### ISSUE TITLE
Invalid group object

### ISSUE THREAD

**Issue by olebowle** [Icinga/icingaweb2-module-director#1256]
Hi,

when I try to apply the following sync rule:

${netelementtype_id} (retrieved from an import source) --> groups

I get the following error: **Invalid group object.**

The problem is, that the netelementtype_id is an integer and not a string. Using the following patch works fine for me. However I'm not sure if this is the proper way:
```diff
--- library/Director/Objects/IcingaObjectGroups.php
+++ library/Director/Objects/IcingaObjectGroups.php
@@ -173,7 +173,7 @@
             }
 
             $this->groups[$group->object_name] = $group;
-        } elseif (is_string($group)) {
+        } elseif (is_string($group) || is_integer($group)) {
             if (array_key_exists($group, $this->groups)) {
                 return $this;
             }
```

**Comment by Thomas-Gelf** [comment]
Once stored this should be fine, problem seems that your import source provides an integer and not a string with some numbers. Could you please try to apply a property modifier like `Lowercase` to your `netelementtype_id` column and let me know whether this works?

**Comment by olebowle** [comment]
Adding the modifier won't change the behaviour. However, I noticed I can still deploy without an issue, even without the patch. Just clicking on an added host in the activity log will give the following traceback, which I worked around with the patch.
```
#0 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObjectGroups.php(162): Icinga\Module\Director\Objects\IcingaObjectGroups->add(Integer, String)
#1 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObjectGroups.php(128): Icinga\Module\Director\Objects\IcingaObjectGroups->add(Array)
#2 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObject.php(1002): Icinga\Module\Director\Objects\IcingaObjectGroups->set(Array)
#3 /usr/share/icingaweb2/modules/director/library/Director/Data/Db/DbObject.php(316): Icinga\Module\Director\Objects\IcingaObject->setGroups(Array)
#4 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObject.php(686): Icinga\Module\Director\Data\Db\DbObject->set(String, Array)
#5 /usr/share/icingaweb2/modules/director/library/Director/Data/Db/DbObject.php(412): Icinga\Module\Director\Objects\IcingaObject->set(String, Array)
#6 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObject.php(627): Icinga\Module\Director\Data\Db\DbObject->setProperties(Array)
#7 /usr/share/icingaweb2/modules/director/library/Director/Web/Widget/ActivityLogInfo.php(444): Icinga\Module\Director\Objects\IcingaObject->setProperties(Array)
#8 /usr/share/icingaweb2/modules/director/library/Director/Web/Widget/ActivityLogInfo.php(311): Icinga\Module\Director\Web\Widget\ActivityLogInfo->createObject(String, Object(stdClass))
#9 /usr/share/icingaweb2/modules/director/library/Director/Web/Widget/ActivityLogInfo.php(320): Icinga\Module\Director\Web\Widget\ActivityLogInfo->newObject()
#10 /usr/share/icingaweb2/modules/director/library/Director/Web/Widget/ActivityLogInfo.php(116): Icinga\Module\Director\Web\Widget\ActivityLogInfo->newConfig()
#11 /usr/share/icingaweb2/modules/director/application/controllers/ConfigController.php(181): Icinga\Module\Director\Web\Widget\ActivityLogInfo->showTab(String)
#12 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Director\Controllers\ConfigController->activityAction()
#13 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#14 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#15 /usr/share/php/Icinga/Application/Web.php(407): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#16 /usr/share/php/Icinga/Application/webrouter.php(104): Icinga\Application\Web->dispatch()
#17 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#18 {main}
```

**Comment by lazyfrosch** [comment]
Those internal fields and references must be done via the object naming Director relies on.

What kind of ID is this?

**Comment by Thomas-Gelf** [comment]
The underlying code changed a lot, so if this is still a thing in v1.5.x please let us know. In that case, instructions of how to reproduce this would be great. Closing this so far.
