### ISSUE TITLE
Failed to load icinga_apiuser ""

### ISSUE THREAD

**Issue by swizzly** [Icinga/icingaweb2-module-director#1293]
In Director opening Icinga Infrastructure/Endpoints/<MYENDPOINT>/Inspect results in the following error message:

```
Oops, an error occurred!

Failed to load icinga_apiuser "" (DbObject.php:616)

#0 /usr/share/icingaweb2/modules/director/library/Director/Data/Db/DbObject.php(1089): Icinga\Module\Director\Data\Db\DbObject->loadFromDb()
#1 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObject.php(308): Icinga\Module\Director\Data\Db\DbObject::loadWithAutoIncId(NULL, Object(Icinga\Module\Director\Db))
#2 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaEndpoint.php(45): Icinga\Module\Director\Objects\IcingaObject->getRelatedObject('apiuser', NULL)
#3 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaEndpoint.php(77): Icinga\Module\Director\Objects\IcingaEndpoint->getApiUser()
#4 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaEndpoint.php(59): Icinga\Module\Director\Objects\IcingaEndpoint->getRestApiClient()
#5 /usr/share/icingaweb2/modules/director/library/Director/Web/Tree/InspectTreeRenderer.php(35): Icinga\Module\Director\Objects\IcingaEndpoint->api()
#6 /usr/share/icingaweb2/modules/director/library/Director/Web/Tree/InspectTreeRenderer.php(54): Icinga\Module\Director\Web\Tree\InspectTreeRenderer->getNodes()
#7 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/BaseElement.php(130): Icinga\Module\Director\Web\Tree\InspectTreeRenderer->assemble()
#8 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/Html.php(171): dipl\Html\BaseElement->render()
#9 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/BaseElement.php(105): dipl\Html\Html->render()
#10 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/BaseElement.php(133): dipl\Html\BaseElement->renderContent()
#11 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/Html.php(259): dipl\Html\BaseElement->render()
#12 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Zf1/SimpleViewRenderer.php(47): dipl\Html\Html->__toString()
#13 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Zf1/SimpleViewRenderer.php(66): dipl\Zf1\SimpleViewRenderer->render()
#14 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker.php(272): dipl\Zf1\SimpleViewRenderer->postDispatch()
#15 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(518): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#16 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('typesAction')
#17 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#18 /usr/share/php/Icinga/Application/Web.php(389): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#19 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
#20 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#21 {main}
```

Otherwise everything else is working, I have API users defined in the system, the API is working.

## Your Environment
* Director version (System - About): From GitHub Commit 44c2a1b7db659df647af93794c5d848f5b0
* Icinga Web 2 version and modules (System - About): 2.4.1
* Icinga 2 version (`icinga2 --version`): r2.7.0-1
* Operating System and version: RedHat Linux 7.4

**Comment by sposs** [comment]
+1
