### ISSUE TITLE
Retrieving object through API returns error

### ISSUE THREAD

**Issue by matthenning** [Icinga/icingaweb2-module-director#1314]
## Expected Behavior
Director returns pre defiend external http command object

## Current Behavior
Request returns object and an error message. HTTP Code is 200.
I truncated the JSON part, but it tested as valid JSON with `python -m json.tool`
```

HTTP/1.1 200 OK
Date: Thu, 30 Nov 2017 12:03:41 GMT
Server: Apache
X-Powered-By: PHP/7.0.7
Transfer-Encoding: chunked
Content-Type: application/json

{
    "arguments": {
        "-6": {
            "command_id": "36",
            "description": "Use IPv6 connection",
            "set_if": "$http_ipv6$"
        },
TRUNCATED
    }
}
<br />
<b>Fatal error</b>:  Uncaught Zend_Controller_Response_Exception: Cannot send headers; headers already sent in /usr/share/icingaweb2/modules/director/library/Director/RestApi/RequestHandler.php, line 39 in /usr/share/icingaweb2/library/vendor/Zend/Controller/Response/Abstract.php:321
Stack trace:
#0 /usr/share/icingaweb2/library/vendor/Zend/Controller/Response/Abstract.php(339): Zend_Controller_Response_Abstract-&gt;canSendHeaders(true)
#1 /usr/share/php/Icinga/Web/Response.php(340): Zend_Controller_Response_Abstract-&gt;sendHeaders()
#2 /usr/share/icingaweb2/library/vendor/Zend/Controller/Response/Abstract.php(762): Icinga\Web\Response-&gt;sendHeaders()
#3 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(975): Zend_Controller_Response_Abstract-&gt;sendResponse()
#4 /usr/share/php/Icinga/Application/Web.php(407): Zend_Controller_Front-&gt;dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#5 /usr/share/php/Icinga/Application/webrouter.php(104): Icinga\Application\Web-&gt;dispatch()
#6 /usr/share/icingaweb2/public/index in <b>/usr/share/icingaweb2/library/vendor/Zend/Controller/Response/Abstract.php</b> on line <b>321</b><br />
```

## Steps to Reproduce (for bugs)
Send a GET request to director/command?name=http
I used the [curl helper script](https://github.com/Icinga/icingaweb2-module-director/blob/master/doc/70-REST-API.md#curl-helper-script) from the docs.

## Your Environment

* Director version (System - About): 1.4.2
* Icinga Web 2 version and modules (System - About): 2.5.0
* Icinga 2 version (`icinga2 --version`): r2.8.0-1
* Operating System and version: SLES12 SP2
* Webserver, PHP versions: Apache2 2.4.23-29.6.1, PHP 7.0.7

Maybe related to #846 ?

**Comment by matthenning** [comment]
I should add: This only seems to happen for external_object commands. Other objects can be retrieved as expected.

**Comment by matthenning** [comment]
It seems like the size of the returned object is the deciding factor.
After changing the php setting `output_buffering` from 4096 to 16384 I can retrieve the object.

I'm not sure if this is a Director or a Zend issue, so I'll leave this open until @Thomas-Gelf had a chance to look at it.
