### ISSUE TITLE
ImportSource preview/history has problem rendering certain types

### ISSUE THREAD

**Issue by lazyfrosch** [Icinga/icingaweb2-module-director#1325]
Certain types fail to render in the table.

    String, Html Element or Array of such expected, got "stdClass" (Util.php:106)
    String, Html Element or Array of such expected, got "boolean" (Util.php:106)

```
#0 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/Html.php(34): dipl\Html\Util::wantHtml(Object(stdClass))
#1 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/BaseElement.php(119): dipl\Html\Html->add(Object(stdClass))
#2 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/Html.php(123): dipl\Html\BaseElement->add(Object(stdClass))
#3 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/Html.php(113): dipl\Html\Html->addContent(Object(stdClass))
#4 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/Table.php(161): dipl\Html\Html->setContent(Object(stdClass))
#5 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Web/Table/QueryBasedTable.php(168): dipl\Html\Table->renderRow(Object(stdClass))
#6 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Web/Table/QueryBasedTable.php(116): dipl\Web\Table\QueryBasedTable->fetchRows()
#7 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/BaseElement.php(133): dipl\Web\Table\QueryBasedTable->renderContent()
#8 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/Html.php(171): dipl\Html\BaseElement->render()
#9 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/BaseElement.php(105): dipl\Html\Html->render()
#10 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/BaseElement.php(133): dipl\Html\BaseElement->renderContent()
#11 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/Html.php(259): dipl\Html\BaseElement->render()
#12 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Zf1/SimpleViewRenderer.php(47): dipl\Html\Html->__toString()
#13 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Zf1/SimpleViewRenderer.php(66): dipl\Zf1\SimpleViewRenderer->render()
#14 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker.php(272): dipl\Zf1\SimpleViewRenderer->postDispatch()
#15 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(518): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#16 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('indexAction')
#17 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#18 /usr/share/php/Icinga/Application/Web.php(389): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#19 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
#20 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#21 {main}
```

## Your Environment

My setup + @cyberkov

* Director version (System - About): 16729a98ecdfd1a11a3f8da54182047b756c22a5
* Icinga Web 2 version and modules (System - About): 2.4.2 + 2.5.0

**Comment by jonasboettcher** [comment]
Have got the same problem.

- icinga | 2.4.1
- director | master, commit e5d996c4925cb53217b4dd2b4de12f0c0986f7cb
- graphite | 0.0.0.5
- monitoring | 2.4.1
- vsphere | 1.1.0

IcingaWeb2 > "Icinga Director" > "Automation" > Select any "Source name" at "Import source" > "History" > Select any "Import run"

```
Oops, an error occurred!

String, Html Element or Array of such expected, got "stdClass" (Util.php:106)

#0 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/Html.php(34): dipl\Html\Util::wantHtml(Object(stdClass))
#1 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/BaseElement.php(119): dipl\Html\Html->add(Object(stdClass))
#2 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/Html.php(123): dipl\Html\BaseElement->add(Object(stdClass))
#3 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/Html.php(113): dipl\Html\Html->addContent(Object(stdClass))
#4 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/Table.php(161): dipl\Html\Html->setContent(Object(stdClass))
#5 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Web/Table/QueryBasedTable.php(168): dipl\Html\Table->renderRow(Object(stdClass))
#6 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Web/Table/QueryBasedTable.php(116): dipl\Web\Table\QueryBasedTable->fetchRows()
#7 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/BaseElement.php(133): dipl\Web\Table\QueryBasedTable->renderContent()
#8 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/Html.php(171): dipl\Html\BaseElement->render()
#9 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/BaseElement.php(105): dipl\Html\Html->render()
#10 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/BaseElement.php(133): dipl\Html\BaseElement->renderContent()
#11 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/Html.php(259): dipl\Html\BaseElement->render()
#12 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Zf1/SimpleViewRenderer.php(47): dipl\Html\Html->__toString()
#13 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Zf1/SimpleViewRenderer.php(66): dipl\Zf1\SimpleViewRenderer->render()
#14 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker.php(272): dipl\Zf1\SimpleViewRenderer->postDispatch()
#15 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(518): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#16 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('indexAction')
#17 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#18 /usr/share/php/Icinga/Application/Web.php(389): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#19 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
#20 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#21 {main}
```

**Comment by lazyfrosch** [comment]
@jonasboettcher you can test the patch in https://github.com/Icinga/icingaweb2-module-director/commit/50116a1e4e68d3c8cffe5c6980f0a78d1c94febf if you like

**Comment by Thomas-Gelf** [comment]
@lazyfrosch: thanks for your pull request. `Html\Util` is the wrong place for this. I guess Preview (`ImportsourceHookTable`) should have been fixed quite some time ago, history probably leads to the shown error. So `ImportedrowsTable` should probably be the place to fix this.

**Comment by lazyfrosch** [comment]
@Thomas-Gelf will do when preparing the PRs

**Comment by lazyfrosch** [comment]
PR is not #1427

**Comment by lazyfrosch** [comment]
PR merged
