### ISSUE TITLE
Undefined offset: 0 (Dashlet.php:237)

### ISSUE THREAD

**Issue by bmccorkle** [Icinga/icingaweb2-module-director#1400]
Hello,

    I'm new to Icinga and trying to set it up to take over for our aging Nagios environment.  When clicking on the main Icinga Director link, I receive the error message below.  This is a fresh setup, though I did uninstall director then reinstall it as the FreeBSD package collection installed an older version than the ports collection had (1.4.1 I believe, ports installed 1.4.3).  One other item that might not be related is Icinga is showing the Icinga host but it is not listed under director.  So I can't manipulate the Icinga Host or Services configuration.   I currently only have two hosts in Icinga and it's still very much in process of being setup.  Any help is very much appreciated.

## Expected Behavior
Click on Icinga Director link, should see normal screen but receive error message instead.  Sublinks (Hosts, Services, etc) seem to work as expected

## Current Behavior
Clicking on the Icinga Director main link I see the following:

Undefined offset: 0 (Dashlet.php:237)
#0 /usr/local/www/icingaweb2/modules/director/library/Director/Dashboard/Dashlet/Dashlet.php(237): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(8, 'Undefined offse...', '/usr/local/www/...', 237, Array)
#1 /usr/local/www/icingaweb2/modules/director/library/Director/Dashboard/Dashlet/Dashlet.php(184): Icinga\Module\Director\Dashboard\Dashlet\Dashlet->statSummary(false)
#2 /usr/local/www/icingaweb2/modules/director/library/Director/Dashboard/Dashlet/Dashlet.php(147): Icinga\Module\Director\Dashboard\Dashlet\Dashlet->getSummary()
#3 /usr/local/www/icingaweb2/modules/director/library/vendor/ipl/Html/BaseElement.php(133): Icinga\Module\Director\Dashboard\Dashlet\Dashlet->renderContent()
#4 /usr/local/www/icingaweb2/modules/director/library/vendor/ipl/Html/Html.php(171): dipl\Html\BaseElement->render()
#5 /usr/local/www/icingaweb2/modules/director/library/vendor/ipl/Html/BaseElement.php(105): dipl\Html\Html->render()
#6 /usr/local/www/icingaweb2/modules/director/library/vendor/ipl/Html/BaseElement.php(133): dipl\Html\BaseElement->renderContent()
#7 /usr/local/www/icingaweb2/modules/director/library/vendor/ipl/Html/Html.php(171): dipl\Html\BaseElement->render()
#8 /usr/local/www/icingaweb2/modules/director/library/Director/Dashboard/Dashboard.php(83): dipl\Html\Html->render()
#9 /usr/local/www/icingaweb2/modules/director/library/vendor/ipl/Html/Html.php(171): Icinga\Module\Director\Dashboard\Dashboard->render()
#10 /usr/local/www/icingaweb2/modules/director/library/vendor/ipl/Html/BaseElement.php(105): dipl\Html\Html->render()
#11 /usr/local/www/icingaweb2/modules/director/library/vendor/ipl/Html/BaseElement.php(133): dipl\Html\BaseElement->renderContent()
#12 /usr/local/www/icingaweb2/modules/director/library/vendor/ipl/Html/Html.php(259): dipl\Html\BaseElement->render()
#13 /usr/local/www/icingaweb2/modules/director/library/vendor/ipl/Zf1/SimpleViewRenderer.php(47): dipl\Html\Html->__toString()
#14 /usr/local/www/icingaweb2/modules/director/library/vendor/ipl/Zf1/SimpleViewRenderer.php(66): dipl\Zf1\SimpleViewRenderer->render()
#15 /usr/local/www/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker.php(272): dipl\Zf1\SimpleViewRenderer->postDispatch()
#16 /usr/local/www/icingaweb2/library/vendor/Zend/Controller/Action.php(518): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#17 /usr/local/www/icingaweb2/library/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('indexAction')
#18 /usr/local/www/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#19 /usr/local/www/icingaweb2/library/Icinga/Application/Web.php(407): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#20 /usr/local/www/icingaweb2/library/Icinga/Application/webrouter.php(104): Icinga\Application\Web->dispatch()
#21 /usr/local/www/icingaweb2/public/index.php(4): require_once('/usr/local/www/...')
#22 {main}

## Your Environment

* Director version (System - About):  1.4.3
* Icinga Web 2 version and modules (System - About):  2.5.1
* Icinga 2 version (`icinga2 --version`):  2.8.1
* Operating System and version:  FreeBSD 11.1-RELEASE-p6
* Webserver, PHP versions:  Apache 2.4.29  /  PHP 5.6.33
MYSQL:  5.6.39

**Comment by bmccorkle** [comment]
Fixed under #766 for me
