### ISSUE TITLE
Exception using Inspect on services with external commands

### ISSUE THREAD

**Issue by friesoft** [Icinga/icingaweb2-module-director#1402]
## Expected Behavior
Inspect should show up just like for other services using custom commands

## Current Behavior
On services using external commands the inspect button leads to an exception
```
array_map(): Argument #2 should be an array (IcingaObjectInspection.php:56)

#0 [internal function]: Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(2, 'array_map(): Ar...', '/usr/share/icin...', 56, Array)
#1 /usr/share/icingaweb2/modules/director/library/Director/Web/Widget/IcingaObjectInspection.php(56): array_map('escapeshellarg', NULL)
#2 /usr/share/icingaweb2/modules/director/library/Director/Web/Widget/IcingaObjectInspection.php(51): Icinga\Module\Director\Web\Widget\IcingaObjectInspection->renderExecutedCommand(NULL)
#3 /usr/share/icingaweb2/modules/director/library/Director/Web/Widget/IcingaObjectInspection.php(40): Icinga\Module\Director\Web\Widget\IcingaObjectInspection->renderLastCheckResult(Object(stdClass))
#4 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/BaseElement.php(132): Icinga\Module\Director\Web\Widget\IcingaObjectInspection->assemble()
#5 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/Html.php(171): dipl\Html\BaseElement->render()
#6 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/BaseElement.php(107): dipl\Html\Html->render()
#7 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/BaseElement.php(135): dipl\Html\BaseElement->renderContent()
#8 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/Html.php(259): dipl\Html\BaseElement->render()
#9 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Zf1/SimpleViewRenderer.php(47): dipl\Html\Html->__toString()
#10 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Zf1/SimpleViewRenderer.php(66): dipl\Zf1\SimpleViewRenderer->render()
#11 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker.php(272): dipl\Zf1\SimpleViewRenderer->postDispatch()
#12 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(518): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#13 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('objectAction')
#14 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#15 /usr/share/php/Icinga/Application/Web.php(407): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#16 /usr/share/php/Icinga/Application/webrouter.php(104): Icinga\Application\Web->dispatch()
#17 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#18 {main}
```

In our case the problem occurs on the following object:
Host: 
Service: Icinga
Command: icinga (External Check Command)

```
template Service "Icinga" {
    check_command = "icinga"
    check_interval = 10s
}

apply Service "Icinga" {
    import "Icinga"

    assign where host.name == "OURHOST-P00.DOMAIN.TL.DR"
    command_endpoint = "ourhost-p00.domain.tl.dr"
}
```

## Steps to Reproduce (for bugs)
1. Click on the service
2. Click on inspect
3. Exception

## Your Environment
* Director version (System - About): master (5149f05d7419ca8cb019a594dc74d9647f40d2f5, Pulled on 2018/02/21)
* Icinga Web 2 version and modules (System - About): 2.5.1
* Icinga 2 version (`icinga2 --version`): r2.8.1-1
* Operating System and version: Red Hat 7.4
* Webserver, PHP versions: httpd (Red Hat default), PHP 7.1

**Comment by Thomas-Gelf** [comment]
The problem here is that `icinga` isn't a "real" command but short-circuited internally in Icinga 2, so there is no executed command in this case. Will be fixed, thanks for reporting it.

**Comment by friesoft** [comment]
Thank you for the lightning fast fix! :+1: You are faster fixing things then me reporting/testing :laughing:

**Comment by Thomas-Gelf** [comment]
Tracking errors down and providing a good description is often worth more and requires more time than the actual fix. It's hard to discover such border cases, but it's trivial to fix them when someone precisely points you to the problem. Thanks again!
