### ISSUE TITLE
PostgreSQL group by incomplete

### ISSUE THREAD

**Issue by lazyfrosch** [Icinga/icingaweb2-module-director#1509]
View: Host -> Services

```
SQLSTATE[42803]: Grouping error: 7 ERROR: column "hsb.service_id" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: ...s.object_name AS name, s.assign_filter, CASE WHEN hsb.servic...
^, query was: SELECT s.id, s.object_name AS name, s.assign_filter, CASE WHEN hsb.service_id IS NULL THEN 'n' ELSE 'y' END AS blacklisted FROM icinga_service AS s
LEFT JOIN icinga_host_service_blacklist AS hsb ON s.id = hsb.service_id AND hsb.host_id = '28' WHERE (object_type = 'apply' AND assign_filter IS NOT NULL) GROUP BY s.id


#4 /usr/share/icingaweb2/modules/director/library/Director/Web/Table/IcingaHostAppliedServicesTable.php(135): Zend_Db_Adapter_Abstract->fetchAll(Object(Zend_Db_Select))
#5 /usr/share/icingaweb2/modules/director/library/Director/Web/Table/IcingaHostAppliedServicesTable.php(106): Icinga\Module\Director\Web\Table\IcingaHostAppliedServicesTable->fetchAllApplyRules()
#6 /usr/share/icingaweb2/modules/director/library/Director/Web/Table/IcingaHostAppliedServicesTable.php(84): Icinga\Module\Director\Web\Table\IcingaHostAppliedServicesTable->getAllApplyRules()
```

## Your Environment
* Director version (System - About): master `v1.4.0-207-ga005ac32`
* Icinga Web 2 version and modules (System - About): `2.5.3`
* Icinga 2 version (`icinga2 --version`): `2.8.4`
* Operating System and version: `Debian stretch`
* Database: PostgreSQL 10.3

**Comment by lazyfrosch** [comment]
Ping me if you need anything!
