### ISSUE TITLE
Service Sets : adding Service return SQLSTATE[42000]: Syntax error or access violation

### ISSUE THREAD

**Issue by kraba** [Icinga/icingaweb2-module-director#1513]
## Expected Behavior

Hi There,
I tried to create a new Service Sets but MariaDB return this error when I switch to Service Sets->Service:

`SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; `

## Current Behavior

I add a new Service Sets (and it works):

![ss1](https://user-images.githubusercontent.com/8244705/41030842-259a6b78-6977-11e8-8152-eb8353edc732.png)

But when i switch to Service tab this error appear:

![ss2](https://user-images.githubusercontent.com/8244705/41030885-3b8d31ea-6977-11e8-85cf-e21206c7083b.png)

I may add a new Service but it doesn't appear on listed one and the error come back.
I may add the Service Sets to an hosts and it works fine (3 services now) 

![ss3](https://user-images.githubusercontent.com/8244705/41033229-ae24f8f4-697d-11e8-8027-f22a12156dc7.png)

and if I deploy changes /  I come back to Service Sets the preview works fine:

```
Config preview: testserviceset
zones.d/director-global/servicesets.conf
/** Service Set 'testserviceset' **/

apply Service "hostalive" {
    import "hostalive"
    assign where host.vars.os == "linux"
    import DirectorOverrideTemplate
}
apply Service "Linux-Disk" {
    import "Linux-Disk"
    assign where host.vars.os == "linux"
    import DirectorOverrideTemplate
}
apply Service "Linux-Load" {
   import "Linux-Load"
   assign where host.vars.os == "linux"
   import DirectorOverrideTemplate
}
```

but...if I switch on Service tab the sql error persist.

A full trace of error from console:

```
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''n' AS blacklisted FROM icinga_service AS s
 LEFT JOIN icinga_service_set AS ss ' at line 1, query was: SELECT s.id, s.service_set_id, ss.host_id, ss.object_name AS service_set, s.object_name AS service, s.disabled, s.object_type, s.'n' AS blacklisted FROM icinga_service AS s
 LEFT JOIN icinga_service_set AS ss ON ss.id = s.service_set_id WHERE (s.service_set_id = '15') ORDER BY s.object_name ASC LIMIT 25 (Pdo.php:225)

#0 /usr/share/icingaweb2/library/vendor/Zend/Db/Statement.php(297): Zend_Db_Statement_Pdo->_execute(Array)
#1 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Abstract.php(470): Zend_Db_Statement->execute(Array)
#2 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Pdo/Abstract.php(232): Zend_Db_Adapter_Abstract->query('SELECT s.id, s....', Array)
#3 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Abstract.php(725): Zend_Db_Adapter_Pdo_Abstract->query(Object(Zend_Db_Select), Array)
#4 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Web/Table/ZfQueryBasedTable.php(93): Zend_Db_Adapter_Abstract->fetchAll(Object(Zend_Db_Select))
#5 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Web/Table/QueryBasedTable.php(209): dipl\Web\Table\ZfQueryBasedTable->fetchQueryRows()
#6 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Web/Table/QueryBasedTable.php(148): dipl\Web\Table\QueryBasedTable->fetch()
#7 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Web/Table/QueryBasedTable.php(112): dipl\Web\Table\QueryBasedTable->fetchRows()
#8 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/BaseHtmlElement.php(198): dipl\Web\Table\QueryBasedTable->renderContent()
#9 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/HtmlDocument.php(193): dipl\Html\BaseHtmlElement->renderUnwrapped()
#10 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/HtmlDocument.php(250): dipl\Html\HtmlDocument->render()
#11 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/BaseHtmlElement.php(175): dipl\Html\HtmlDocument->renderUnwrapped()
#12 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/BaseHtmlElement.php(198): dipl\Html\BaseHtmlElement->renderContent()
#13 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/HtmlDocument.php(193): dipl\Html\BaseHtmlElement->renderUnwrapped()
#14 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/HtmlDocument.php(262): dipl\Html\HtmlDocument->render()
#15 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Zf1/SimpleViewRenderer.php(47): dipl\Html\HtmlDocument->__toString()
#16 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Zf1/SimpleViewRenderer.php(66): dipl\Zf1\SimpleViewRenderer->render()
#17 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker.php(272): dipl\Zf1\SimpleViewRenderer->postDispatch()
#18 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(518): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#19 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('servicesAction')
#20 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#21 /usr/share/php/Icinga/Application/Web.php(409): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#22 /usr/share/php/Icinga/Application/webrouter.php(104): Icinga\Application\Web->dispatch()
#23 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#24 {main}
```

## Your Environment

* Director version (System - About): 
**Version : master
Git commit : 4b2546b14fc86c6084260f4d9386e597579fe32**
* Icinga Web 2 version and modules (System - About):
**Icinga Web 2 Version 2.5.3
Git commit ca7e886b820f0145999fdf7377f5c4132301eada
Git commit date 2018-04-27**
* Icinga 2 version (`icinga2 --version`): **r2.8.4-1**
* Operating System and version:  Red Hat Enterprise Linux Server release 7.5 (Maipo) - 3.10.0-693.el7.x86_64 
* Webserver, PHP versions:
Webserver: Apache/2.4.6 (Red Hat Enterprise Linux) Server built:   Jan  8 2018 06:49:04
PHP: PHP 7.1.8 (cli) (built: Aug  8 2017 09:01:08) ( NTS )
MariaDB: 5.5.56-MariaDB

**Comment by Thomas-Gelf** [comment]
Ciao Matteo,

thanks for reporting this. This should have been fixed a week ago with 31a6ab0, please pull the latest master.

Cheers,
Thomas
