### ISSUE TITLE
Exception when trying to Inspect a Pending service

### ISSUE THREAD

**Issue by leeclemens** [Icinga/icingaweb2-module-director#1641]
## Expected Behavior
Graceful error message if the required information cannot (yet) be displayed.

## Current Behavior
Exception/Traceback is displayed

## Possible Solution
Handle the condition and display an error if the correct information cannot be displayed.

## Steps to Reproduce (for bugs)
Create a new service
While it is `Pending`, click `Inspect`

## Your Environment

* Director version (System - About):
`1.5.1`
* Icinga Web 2 version and modules (System - About):
`2.6.1`
* Icinga 2 version (`icinga2 --version`):
```
icinga2 - The Icinga 2 network monitoring daemon (version: r2.9.1-1)
```
* Operating System and version:
```
System information:
  Platform: CentOS Linux
  Platform version: 7 (Core)
  Kernel: Linux
  Kernel version: 3.10.0-862.11.6.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: unknown
```
* Webserver, PHP versions:
```
nginx-1.12.2-2.el7.x86_64
Apache httpd 2.4.34
rh-php71-php-fpm-7.1.8-1.el7.x86_64
```

**Comment by leeclemens** [comment]
The backtrace:

```
services "<myserver>!<myservice>"
Oops, an error occurred!
First parameter must either be an object or the name of an existing class (IcingaObjectInspection.php:60)
#0 [internal function]: Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(2, 'First parameter...', '/usr/share/icin...', 60, Array)
#1 /usr/share/icingaweb2/modules/director/library/Director/Web/Widget/IcingaObjectInspection.php(60): property_exists(NULL, 'command')
#2 /usr/share/icingaweb2/modules/director/library/Director/Web/Widget/IcingaObjectInspection.php(45): Icinga\Module\Director\Web\Widget\IcingaObjectInspection->renderLastCheckResult(NULL)
#3 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/HtmlDocument.php(232): Icinga\Module\Director\Web\Widget\IcingaObjectInspection->assemble()
#4 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/BaseHtmlElement.php(194): dipl\Html\HtmlDocument->ensureAssembled()
#5 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/HtmlDocument.php(193): dipl\Html\BaseHtmlElement->renderUnwrapped()
#6 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/HtmlDocument.php(250): dipl\Html\HtmlDocument->render()
#7 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/BaseHtmlElement.php(175): dipl\Html\HtmlDocument->renderUnwrapped()
#8 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/BaseHtmlElement.php(198): dipl\Html\BaseHtmlElement->renderContent()
#9 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/HtmlDocument.php(193): dipl\Html\BaseHtmlElement->renderUnwrapped()
#10 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/HtmlDocument.php(262): dipl\Html\HtmlDocument->render()
#11 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Zf1/SimpleViewRenderer.php(47): dipl\Html\HtmlDocument->__toString()
#12 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Zf1/SimpleViewRenderer.php(66): dipl\Zf1\SimpleViewRenderer->render()
#13 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker.php(272): dipl\Zf1\SimpleViewRenderer->postDispatch()
#14 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(518): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#15 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('objectAction')
#16 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#17 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#18 /usr/share/php/Icinga/Application/webrouter.php(104): Icinga\Application\Web->dispatch()
#19 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#20 {main}
```

**Comment by Thomas-Gelf** [comment]
Thanks for reporting this! Not sure whether this was a missing property in former Icinga 2 versions and is now NULL, anyways - both situations should be covered. I'll immediately push a fix, it would be great if you could give it a try and let me know whether it solves your problem.

**Comment by leeclemens** [comment]
That fix worked great, thanks for the quick fix @Thomas-Gelf !

**Comment by Thomas-Gelf** [comment]
You're welcome, thanks for testing!
