### ISSUE TITLE
Unable to detect your deployment endpoint. I was looking for the first endpoint configured with an assigned API user in the "master" zone.

### ISSUE THREAD

**Issue by mtdeguzis** [Icinga/icingaweb2-module-director#1644]
## Expected Behavior
On a fresh install of icinga2 + icingaweb, I should be able to work with directory.

## Current Behavior
```
Seems eerily similar to #918

**Error message**
Unable to detect your deployment endpoint. I was looking for the first endpoint configured with an assigned API user in the "master" zone.

#0 /usr/share/icingaweb2/modules/director/library/Director/Db.php(233): Icinga\Module\Director\Db->getDeploymentEndpointName()
#1 /usr/share/icingaweb2/modules/director/library/Director/Web/Controller/Extension/CoreApi.php(36): Icinga\Module\Director\Db->getDeploymentEndpoint()
#2 /usr/share/icingaweb2/modules/director/application/controllers/ConfigController.php(263): Icinga\Module\Director\Web\Controller\ActionController->api()
#3 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Director\Controllers\ConfigController->filesAction()
#4 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#5 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#6 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#7 /usr/share/php/Icinga/Application/webrouter.php(104): Icinga\Application\Web->dispatch()
#8 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#9 {main}
```

/etc/icinga2/zones.conf
```
/*
 * Generated by Icinga 2 node setup commands
 * on 2018-09-17 16:11:40 +0000
 */

object Endpoint "nodename" {
}

object Zone "master" {
        endpoints = [ "nodename" ]
}

object Zone "global-templates" {
        global = true
}

object Zone "director-global" {
        global = true
}
```

api-users.conf
```
─
/**
 * The APIUser objects are used for authentication against the API.
 */
object ApiUser "root" {
  password = "pw"
  // client_cn = ""

  permissions = [ "*" ]
}
// Required for Director
object ApiUser "icinga2-director" {
  password = "pw"
  permissions = [ "*" ]
}
```

## Possible Solution
?

## Your Environment

* Director version (System - About): master
* Icinga Web 2 version and modules (System - About):
``
Icinga Web 2 Version
2.6.1
Git commit
b3e0b5d587c3587a09d82b3634dbe3a5dd315353
```
* Icinga 2 version (`icinga2 --version`):
```
icinga2 - The Icinga 2 network monitoring daemon (version: r2.9.1-1)

Copyright (c) 2012-2018 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: Red Hat Enterprise Linux Server
  Platform version: 7.5 (Maipo)
  Kernel: Linux
  Kernel version: 3.10.0-693.17.1.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: unknown
```
* Operating System and version: RHEL 7.4
* Webserver, PHP versions: 
```
# /opt/rh/rh-php71/root/bin/php --version
PHP 7.1.8 (cli) (built: Aug  8 2017 09:01:08) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
```

**Comment by mtdeguzis** [comment]
Something I noticed during setup:
```
# My code line:
if ! psql -h $DB_HOST -U director -d director < /usr/share/icingaweb2/modules/director/schema/pgsql.sql; then

<TRUNCATED>
CREATE INDEX
COMMENT
NOTICE:  CREATE TABLE will create implicit sequence "icinga_usergroup_id_seq" for serial column "icinga_usergroup.id"
(standard_in) 1: syntax error
(standard_in) 1: syntax error
```

**Comment by mtdeguzis** [comment]
Using pgsanity I see:
```
CREATE OR REPLACE FUNCTION unix_timestamp(timestamp with time zone) RETURNS bigint AS '
        SELECT EXTRACT(EPOCH FROM $1)::bigint AS result
' LANGUAGE sql;
```

That LANGUAGE line is just hanging out there. Maybe a red herring, though I see this in the automation doc here:

> You do not need to manually care about creating the schema and to migrate it for newer versions. Just grant the configured user all permissions on his database. I suppose I don't need to import the schema myself. Trying without this piece in my setups.

https://github.com/Icinga/icingaweb2-module-director/blob/master/doc/03-Automation.md

**Comment by mtdeguzis** [comment]
Could $1 be mangled when psql ingests it?
