### ISSUE TITLE
Director does not ask for pending database migration

### ISSUE THREAD

**Issue by binarygraka** [Icinga/icingaweb2-module-director#1708]
## Expected Behavior

When checking out the latest stable version of the Director (in my case `v1.5.2`), a notification to migrate the database should appear in the Icingaweb2 Director frontend and I should be able to migrate the database and continue using the director.

## Current Behavior

I have cloned the Director a few weeks ago and checked out the Master branch. I'm currently at the following version:

```
commit 4c3c81c275bce743ef6fe68957725e67fd54385e
Author: Thomas Gelf <thomas@gelf.net>
Date:   Wed Oct 17 09:05:20 2018 +0200

    JobsCommand: explicitly load with ID

    fixes #1677

diff --git a/application/clicommands/JobsCommand.php b/application/clicommands/JobsCommand.php
index 7848ef3..adddd74 100644
--- a/application/clicommands/JobsCommand.php
+++ b/application/clicommands/JobsCommand.php
@@ -21,7 +21,7 @@ class JobsCommand extends Command
         $jobId = $this->params->shift();
         if ($jobId) {
             $this->raiseLimits();
-            $job = DirectorJob::load($jobId, $this->db());
+            $job = DirectorJob::loadWithAutoIncId($jobId, $this->db());
             $job->run();
             exit(0);
         }
```

I then checkout `v1.5.2` using the following command: `git checkout v1.5.2`. 

I then browse the Director frontend as usual, but no message stating anything about a database migration appear. Moreover, I can view hosts, services, notifications and more. However, if I go to Director --> Config deployment --> Render config, the following error appears:

```
Trying to set invalid icinga_timeperiod key "prefer_includes". DB schema change?

#0 /usr/share/icingaweb2/modules/director/library/Director/Data/Db/DbObject.php(1157): Icinga\Module\Director\Data\Db\DbObject->setDbProperties(Object(stdClass))
#1 /usr/share/icingaweb2/modules/director/library/Director/Data/Db/DbObject.php(1182): Icinga\Module\Director\Data\Db\DbObject::loadAll(Object(Icinga\Module\Director\Db), NULL, String)
#2 /usr/share/icingaweb2/modules/director/library/Director/IcingaConfig/IcingaConfig.php(691): Icinga\Module\Director\Data\Db\DbObject::prefetchAll(Object(Icinga\Module\Director\Db))
#3 /usr/share/icingaweb2/modules/director/library/Director/IcingaConfig/IcingaConfig.php(463): Icinga\Module\Director\IcingaConfig\IcingaConfig->createFileFromDb(String)
#4 /usr/share/icingaweb2/modules/director/library/Director/IcingaConfig/IcingaConfig.php(268): Icinga\Module\Director\IcingaConfig\IcingaConfig->generateFromDb()
#5 /usr/share/icingaweb2/modules/director/library/Director/IcingaConfig/IcingaConfig.php(304): Icinga\Module\Director\IcingaConfig\IcingaConfig->hasBeenModified()
#6 /usr/share/icingaweb2/modules/director/library/Director/IcingaConfig/IcingaConfig.php(257): Icinga\Module\Director\IcingaConfig\IcingaConfig->storeIfModified()
#7 /usr/share/icingaweb2/modules/director/application/controllers/ConfigController.php(313): Icinga\Module\Director\IcingaConfig\IcingaConfig::generate(Object(Icinga\Module\Director\Db))
#8 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Director\Controllers\ConfigController->storeAction()
#9 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#10 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#11 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#12 /usr/share/php/Icinga/Application/webrouter.php(104): Icinga\Application\Web->dispatch()
#13 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#14 {main}
```

If I take the following steps: Activity log --> `There are no pending changes. Deploy anyways`, I get the following error:

```
Trying to set invalid icinga_timeperiod key "prefer_includes". DB schema change? (DbObject.php:651)
```

According to my understanding, the current commit I'm on is from `v1.5.1` and when checking out `v1.5.2` the director should ask for a database migration.

I also have the issue that services, that were assigned to a host via a service set, are not displayed under Host --> Services for every service set. This only works for a few service sets. Thus I wanted to update to `v1.5.2` first to test this on the newest version.

## Your Environment

* Director version (System - About): `commit 4c3c81c275bce743ef6fe68957725e67fd54385e
`
* Icinga Web 2 version and modules (System - About): 
  * Graphite: `1.1.0`
  * Monitoring: `2.6.1`
  * Icinga Web 2: `2.6.1`
* Icinga 2 version (`icinga2 --version`): `r2.10.2-1`
* Operating System and version: `CentOS Linux release 7.2.1511 (Core)`
* Webserver, PHP versions: 
  * Apache: `2.4.6`
  * `rh-php71`

**Comment by binarygraka** [comment]
Just searched the issues again for `icinga_timeperiod` and found the relating issue #1694 

I also wait for `1.6.0` then, thanks.
