### ISSUE TITLE
Error when restoring snapshot: Cannot load resource config "". Resource does not exist

### ISSUE THREAD

**Issue by mtdeguzis** [Icinga/icingaweb2-module-director#1716]
## Expected Behavior
Restoring a snapshot after disabling a command with director should restore the command state.

## Current Behavior
Restoring a snapshot of a basket fails with:

```
Cannot load resource config "". Resource does not exist

#0 /usr/share/icingaweb2/modules/director/library/Director/Db.php(63): Icinga\Data\ResourceFactory::getResourceConfig(NULL)
#1 /usr/share/icingaweb2/modules/director/application/forms/RestoreBasketForm.php(65): Icinga\Module\Director\Db::fromResourceName(NULL)
#2 /usr/share/icingaweb2/modules/director/application/controllers/BasketController.php(201): Icinga\Module\Director\Forms\RestoreBasketForm->getDb()
#3 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Director\Controllers\BasketController->snapshotAction()
#4 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#5 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#6 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#7 /usr/share/php/Icinga/Application/webrouter.php(104): Icinga\Application\Web->dispatch()
#8 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#9 {main}
```
## Steps to reproduce
1. Create basket of all items
![image](https://user-images.githubusercontent.com/27829577/48953912-6e60f600-ef15-11e8-9d86-b81a2bf7cb58.png)
2. Click Snapshots, then Create Snapshot
![image](https://user-images.githubusercontent.com/27829577/48953916-74ef6d80-ef15-11e8-9cf7-40bd6e7f6675.png)
3. Modify a command, such as disabling it, deploy this change via Director
4. Attempt to restore the snapshot:
![image](https://user-images.githubusercontent.com/27829577/48953937-89336a80-ef15-11e8-915c-68a0cabc8b8c.png)
![image](https://user-images.githubusercontent.com/27829577/48953945-8e90b500-ef15-11e8-966e-e823f316c0f6.png)

## Your Environment

* Director version (System - About): master (last updated Oct 30).
* Icinga Web 2 version and modules (System - About): 2.6.1, commit b3e0b5d587c3587a09d82b3634dbe3a5dd315353
* Icinga 2 version (`icinga2 --version`):
```
icinga2 - The Icinga 2 network monitoring daemon (version: r2.10.1-1)

Copyright (c) 2012-2018 Icinga Development Team (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: Red Hat Enterprise Linux Server
  Platform version: 7.5 (Maipo)
  Kernel: Linux
  Kernel version: 3.10.0-862.11.6.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: unknown

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid
```
* Operating System and version: RHEL 7.5 x86_64
* Webserver, PHP versions: 
```
# /opt/rh/rh-php71/root/bin/php --version
PHP 7.1.8 (cli) (built: Aug  8 2017 09:01:08) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
```

**Comment by Thomas-Gelf** [comment]
Please try the latest master, if I remember it correctly this should have been fixed.

**Comment by Thomas-Gelf** [comment]
NB: Otherwise please let me know!

**Comment by mtdeguzis** [comment]
I made a mistake I did update director github master in use after my other ticket on this. Will recheck.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by mtdeguzis** [comment]
Rebuilt our Icinga Dev instance again with the master branch of Director and latest icingaweb2 bugfix release. Same result.

**Comment by mtdeguzis** [comment]
I stopped using the git archive and used a git clone to ensure what commit I was on:
```
commit 01f82b2d4841d13e6d43a4b918e62dce2cacdc9b
Author: Thomas Gelf <thomas@gelf.net>
Date:   Thu Nov 22 08:25:33 2018 +0100

    RestApiClient: use correct RuntimeException
```

**Comment by Thomas-Gelf** [comment]
Sorry guys, I overlooked this one. Didn't happen to me as this occurs only with less than two configured DB resources. And that's probably the default for most setups :laughing:

**Comment by Thomas-Gelf** [comment]
@mtdeguzis: ses, it's on the v1.6.1 milestone (see above on the right side), and has already been pushed to the **support/1.6** branch
