### ISSUE TITLE
Basket might fail to restore depending on your PHP version

### ISSUE THREAD

**Issue by Thomas-Gelf** [Icinga/icingaweb2-module-director#1782]
## Expected Behavior
I can upload a basket

## Current Behavior
It might fail with an error telling me something about being unable to `count()`.

**Comment by log1-c** [comment]
Hi @Thomas-Gelf ,

the problem still exists for me with v1.6.2.

```
count(): Parameter must be an array or an object that implements Countable

#0 /usr/share/icingaweb2/library/vendor/Zend/Validate/File/Upload.php(224): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(Integer, String, String, Integer, Array)
#1 /usr/share/icingaweb2/library/vendor/Zend/File/Transfer/Adapter/Abstract.php(665): Zend_Validate_File_Upload->isValid(String, String)
#2 /usr/share/icingaweb2/library/vendor/Zend/File/Transfer/Adapter/Http.php(145): Zend_File_Transfer_Adapter_Abstract->isValid(String)
#3 /usr/share/icingaweb2/library/vendor/Zend/Form/Element/File.php(441): Zend_File_Transfer_Adapter_Http->isValid(String)
#4 /usr/share/icingaweb2/library/vendor/Zend/Form.php(2278): Zend_Form_Element_File->isValid(NULL, Array)
#5 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(379): Zend_Form->isValid(Array)
#6 /usr/share/icingaweb2/modules/director/application/controllers/BasketController.php(124): Icinga\Module\Director\Web\Form\QuickForm->handleRequest()
#7 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Director\Controllers\BasketController->uploadAction()
#8 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#9 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#10 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#11 /usr/share/php/Icinga/Application/webrouter.php(104): Icinga\Application\Web->dispatch()
#12 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#13 {main}
```

OS is Ubuntu 18.04.2
PHP is PHP 7.2.15-0ubuntu0.18.04.1

**Comment by mikeb93** [comment]
Hi @Thomas-Gelf 
I'm also having this issue

PHP 7.2.17-0ubuntu0.18.04.1
Ubuntu Server 18.04.2 LTS

**Comment by Thomas-Gelf** [comment]
@mikeb93: a vendor-library used by Icinga Web 2 fails here, you might want to apply the patch shown [here](https://github.com/Icinga/icingaweb2/issues/3689)

**Comment by mikeb93** [comment]
@Thomas-Gelf 
Please excuse my incompetence when it comes to git...
.. But how would I apply that patch when I installed icingaweb2 via the apt repositories?
