### ISSUE TITLE
Import run history entries not working with Icinga Web 2.7.x

### ISSUE THREAD

**Issue by N-o-X** [Icinga/icingaweb2-module-director#1924]
## Expected Behavior
Import run history entry should be displayed when selected

## Current Behavior
```
Undefined property: stdClass::$object_name (SimpleQuery.php:372)
#0 /vagrant/library/Icinga/Data/SimpleQuery.php(372): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(8, 'Undefined prope...', '/vagrant/librar...', 372, Array)
#1 [internal function]: Icinga\Data\SimpleQuery->compare(Object(stdClass), Object(stdClass))
#2 /vagrant/library/Icinga/Data/DataArray/ArrayDatasource.php(247): usort(Array, Array)
#3 /vagrant/library/Icinga/Data/DataArray/ArrayDatasource.php(180): Icinga\Data\DataArray\ArrayDatasource->createResult(Object(Icinga\Data\SimpleQuery))
#4 /vagrant/library/Icinga/Data/SimpleQuery.php(649): Icinga\Data\DataArray\ArrayDatasource->count(Object(Icinga\Data\SimpleQuery))
#5 /vagrant/modules/director/library/vendor/ipl/Data/SimpleQueryPaginationAdapter.php(21): Icinga\Data\SimpleQuery->count()
#6 [internal function]: dipl\Data\SimpleQueryPaginationAdapter->count()
#7 /vagrant/modules/director/library/vendor/ipl/Web/Widget/Paginator.php(134): count(Object(dipl\Data\SimpleQueryPaginationAdapter))
#8 /vagrant/modules/director/library/vendor/ipl/Web/Widget/Paginator.php(115): dipl\Web\Widget\Paginator->getTotalItemCount()
#9 /vagrant/modules/director/library/vendor/ipl/Web/Widget/Paginator.php(457): dipl\Web\Widget\Paginator->getPageCount()
#10 /vagrant/modules/director/library/vendor/ipl/Html/HtmlDocument.php(250): dipl\Web\Widget\Paginator->render()
#11 /vagrant/modules/director/library/vendor/ipl/Html/BaseHtmlElement.php(175): dipl\Html\HtmlDocument->renderUnwrapped()
#12 /vagrant/modules/director/library/vendor/ipl/Html/BaseHtmlElement.php(198): dipl\Html\BaseHtmlElement->renderContent()
#13 /vagrant/modules/director/library/vendor/ipl/Html/HtmlDocument.php(193): dipl\Html\BaseHtmlElement->renderUnwrapped()
#14 /vagrant/modules/director/library/vendor/ipl/Html/HtmlDocument.php(250): dipl\Html\HtmlDocument->render()
#15 /vagrant/modules/director/library/vendor/ipl/Html/BaseHtmlElement.php(175): dipl\Html\HtmlDocument->renderUnwrapped()
#16 /vagrant/modules/director/library/vendor/ipl/Web/Widget/Controls.php(168): dipl\Html\BaseHtmlElement->renderContent()
#17 /vagrant/modules/director/library/vendor/ipl/Html/BaseHtmlElement.php(198): dipl\Web\Widget\Controls->renderContent()
#18 /vagrant/modules/director/library/vendor/ipl/Html/HtmlDocument.php(193): dipl\Html\BaseHtmlElement->renderUnwrapped()
#19 /vagrant/modules/director/library/vendor/ipl/Html/HtmlDocument.php(262): dipl\Html\HtmlDocument->render()
#20 /vagrant/modules/director/library/vendor/ipl/Zf1/SimpleViewRenderer.php(61): dipl\Html\HtmlDocument->__toString()
#21 /vagrant/modules/director/library/vendor/ipl/Zf1/SimpleViewRenderer.php(104): dipl\Zf1\SimpleViewRenderer->render()
#22 /vagrant/library/vendor/Zend/Controller/Action/HelperBroker.php(272): dipl\Zf1\SimpleViewRenderer->postDispatch()
#23 /vagrant/library/vendor/Zend/Controller/Action.php(518): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#24 /vagrant/library/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('indexAction')
#25 /vagrant/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#26 /vagrant/library/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#27 /vagrant/library/Icinga/Application/webrouter.php(99): Icinga\Application\Web->dispatch()
#28 /vagrant/public/index.php(4): require_once('/vagrant/librar...')
#29 {main}
```
## Possible Solution
This happens because of this change https://github.com/Icinga/icingaweb2/commit/032ca7ae50db1f970df667f613c3ee49fe225aeb
in Icinga Web 2.7.0 and requires to add an order column.

## Steps to Reproduce (for bugs)
- Create & Run an import source with 2+ rows
- Click on `History` and select a history entry

## Your Environment
* Director version (System - About): master@https://github.com/Icinga/icingaweb2-module-director/commit/d1a06c11cfc63204b877114cf0380b5b84c8deb0
* Icinga Web 2 version and modules (System - About): Icinga Web 2.7.0

**Comment by Thomas-Gelf** [comment]
Thanks for reporting this!
