### ISSUE TITLE
Director 1.7.2 fails to import objects it has exported

### ISSUE THREAD

**Issue by maggu** [Icinga/icingaweb2-module-director#2016]
## Expected Behavior
Director is able to import config objects it has exported, at least when exporting and importing with the same version of Director (1.7.2).

## Current Behavior
When I try to import any exported ImportSource definitions with property modifiers it fails with the following error:

```
PHP Fatal error:  Uncaught Error: Call to a member function setProperties() on null in /usr/share/icingaweb2/modules/director/library/Director/Objects/ImportSource.php:128
Stack trace:
#0 /usr/share/icingaweb2/modules/director/library/Director/Data/Db/DbObject.php(329): Icinga\Module\Director\Objects\ImportSource->setModifiers(Array)
#1 /usr/share/icingaweb2/modules/director/library/Director/Data/Db/DbObjectWithSettings.php(23): Icinga\Module\Director\Data\Db\DbObject->set('modifiers', Array)
#2 /usr/share/icingaweb2/modules/director/library/Director/Data/Db/DbObject.php(429): Icinga\Module\Director\Data\Db\DbObjectWithSettings->set('modifiers', Array)
#3 /usr/share/icingaweb2/modules/director/library/Director/Objects/ImportSource.php(107): Icinga\Module\Director\Data\Db\DbObject->setProperties(Array)
#4 /usr/share/icingaweb2/modules/director/library/Director/DirectorObject/Automation/ImportExport.php(125): Icinga\Module\Director\Objects\ImportSource::import(Object(stdClass), Object(Icinga\Module\Director\Db))
#5 /usr/share/ic in /usr/share/icingaweb2/modules/director/library/Director/Objects/ImportSource.php on line 128

Fatal error: Uncaught Error: Call to a member function setProperties() on null in /usr/share/icingaweb2/modules/director/library/Director/Objects/ImportSource.php:128
Stack trace:
#0 /usr/share/icingaweb2/modules/director/library/Director/Data/Db/DbObject.php(329): Icinga\Module\Director\Objects\ImportSource->setModifiers(Array)
#1 /usr/share/icingaweb2/modules/director/library/Director/Data/Db/DbObjectWithSettings.php(23): Icinga\Module\Director\Data\Db\DbObject->set('modifiers', Array)
#2 /usr/share/icingaweb2/modules/director/library/Director/Data/Db/DbObject.php(429): Icinga\Module\Director\Data\Db\DbObjectWithSettings->set('modifiers', Array)
#3 /usr/share/icingaweb2/modules/director/library/Director/Objects/ImportSource.php(107): Icinga\Module\Director\Data\Db\DbObject->setProperties(Array)
#4 /usr/share/icingaweb2/modules/director/library/Director/DirectorObject/Automation/ImportExport.php(125): Icinga\Module\Director\Objects\ImportSource::import(Object(stdClass), Object(Icinga\Module\Director\Db))
#5 /usr/share/ic in /usr/share/icingaweb2/modules/director/library/Director/Objects/ImportSource.php on line 128
```

## Steps to Reproduce (for bugs)
Create the following import source in director, export it, delete it in Director and import it again.
```
[
    {
        "description": null,
        "key_column": "title",
        "modifiers": [
            {
                "description": null,
                "priority": "1",
                "property_name": "parameters.vars.hostenv",
                "provider_class": "Icinga\\Module\\Director\\PropertyModifier\\PropertyModifierLowercase",
                "settings": {},
                "target_property": "hostenv"
            }
        ],
        "originalId": "1",
        "provider_class": "Icinga\\Module\\Puppetdb\\ProvidedHook\\Director\\ImportSource",
        "settings": {
            "api_version": "v4",
            "client_cert": "puppetdb",
            "query_type": "resource",
            "resource_type": "@@Icinga2::Object::Host",
            "server": "puppetdb.example.org"
        },
        "source_name": "PuppetDB Hosts"
    }
]
```
## Your Environment
* Director version (System - About): 1.7.2
* Icinga Web 2 version and modules (System - About): 2.7.3

Name | Version
--- | ---
businessprocess | 2.2.0
cube | 1.1.0
director | 1.7.2
fileshipper | 1.1.0
generictts | 2.0.0
incubator | 0.5.0
ipl | v0.3.0
monitoring | 2.7.3
puppetdb | 1.0.0
reactbundle | 0.7.0
vsphere | 1.1.0

* Icinga 2 version (`icinga2 --version`):  2.11.2-1
* Operating System and version: CentOS Linux release 7.7.1908 (x86_64)
* Webserver, PHP versions: Apache HTTP server 2.4.6, PHP 7.1.30
* Database: PostgreSQL 9.2.24

**Comment by mickael-ange** [comment]
Same here with modules Director 1.7.2, AWS 1.0.0.

It has something to do with the modifiers importation.

If I removed the modifier objects from my basket, the restoration works. Then if I put back the modifiers I can restore the whole basket.

```
cat /tmp/basket.json |  icingacli director basket restore
PHP Fatal error:  Uncaught Error: Call to a member function setProperties() on null in /opt/icingaweb2-module-director-1.7.2/library/Director/Objects/ImportSource.php:128
Stack trace:
#0 /opt/icingaweb2-module-director-1.7.2/library/Director/Data/Db/DbObject.php(329): Icinga\Module\Director\Objects\ImportSource->setModifiers(Array)
#1 /opt/icingaweb2-module-director-1.7.2/library/Director/Data/Db/DbObjectWithSettings.php(23): Icinga\Module\Director\Data\Db\DbObject->set('modifiers', Array)
#2 /opt/icingaweb2-module-director-1.7.2/library/Director/Data/Db/DbObject.php(429): Icinga\Module\Director\Data\Db\DbObjectWithSettings->set('modifiers', Array)
#3 /opt/icingaweb2-module-director-1.7.2/library/Director/Objects/ImportSource.php(107): Icinga\Module\Director\Data\Db\DbObject->setProperties(Array)
#4 /opt/icingaweb2-module-director-1.7.2/library/Director/DirectorObject/Automation/BasketSnapshot.php(277): Icinga\Module\Director\Objects\ImportSource::import(Object(stdClass), Object(Icinga\Module\Director\Db), true)
#5 /opt/icinga in /opt/icingaweb2-module-director-1.7.2/library/Director/Objects/ImportSource.php on line 128

Fatal error: Uncaught Error: Call to a member function setProperties() on null in /opt/icingaweb2-module-director-1.7.2/library/Director/Objects/ImportSource.php:128
Stack trace:
#0 /opt/icingaweb2-module-director-1.7.2/library/Director/Data/Db/DbObject.php(329): Icinga\Module\Director\Objects\ImportSource->setModifiers(Array)
#1 /opt/icingaweb2-module-director-1.7.2/library/Director/Data/Db/DbObjectWithSettings.php(23): Icinga\Module\Director\Data\Db\DbObject->set('modifiers', Array)
#2 /opt/icingaweb2-module-director-1.7.2/library/Director/Data/Db/DbObject.php(429): Icinga\Module\Director\Data\Db\DbObjectWithSettings->set('modifiers', Array)
#3 /opt/icingaweb2-module-director-1.7.2/library/Director/Objects/ImportSource.php(107): Icinga\Module\Director\Data\Db\DbObject->setProperties(Array)
#4 /opt/icingaweb2-module-director-1.7.2/library/Director/DirectorObject/Automation/BasketSnapshot.php(277): Icinga\Module\Director\Objects\ImportSource::import(Object(stdClass), Object(Icinga\Module\Director\Db), true)
#5 /opt/icinga in /opt/icingaweb2-module-director-1.7.2/library/Director/Objects/ImportSource.php on line 128
# After removing the modifiers, restore succeed
[root@icinga2 vagrant]# cat /tmp/basket.json |  icingacli director basket restore
Objects from Basket Snapshot have been restored
# After putting the modifiers back, restore succeed
[root@icinga2 vagrant]# cat /tmp/basket.json |  icingacli director basket restore
Objects from Basket Snapshot have been restored
```
we cannot attach a json file to a comment, please rename `basket.json.txt` to `basket.json`: [basket.json.txt](https://github.com/Icinga/icingaweb2-module-director/files/3882245/basket.json.txt)

**Comment by mickael-ange** [comment]
Seems related to #2013

**Comment by mickael-ange** [comment]
Furthermore, with the above basket I have attached, the import and sync jobs are not restored properly, the settings `source` and `rule` aren't selected. I have to select them manually to complete the basket restoration.

![image](https://user-images.githubusercontent.com/5266874/69838437-88eb4f00-128e-11ea-8f0f-64c568a601bf.png)

![image-2019-11-27-11-34-52-098](https://user-images.githubusercontent.com/5266874/69838548-01521000-128f-11ea-8481-541f0d3efd20.png)

![image-2019-11-27-11-35-43-152](https://user-images.githubusercontent.com/5266874/69838559-0e6eff00-128f-11ea-8100-dd26d6860053.png)

![image-2019-11-27-11-36-33-578](https://user-images.githubusercontent.com/5266874/69838580-2181cf00-128f-11ea-9090-6a3626cb7572.png)

**Comment by mkayontour** [comment]
I tried restoring 1 ServiceSet, 2 Import Rules and 2 Sync Rules: 
```
Uncaught Error: Call to a member function setProperties() on null in /usr/share/icingaweb2/modules/director/library/Director/Objects/ImportSource.php:128
Stack trace:
#0 /usr/share/icingaweb2/modules/director/library/Director/Data/Db/DbObject.php(329): Icinga\Module\Director\Objects\ImportSource->setModifiers(Array)
#1 /usr/share/icingaweb2/modules/director/library/Director/Data/Db/DbObjectWithSettings.php(23): Icinga\Module\Director\Data\Db\DbObject->set('modifiers', Array)
#2 /usr/share/icingaweb2/modules/director/library/Director/Data/Db/DbObject.php(429): Icinga\Module\Director\Data\Db\DbObjectWithSettings->set('modifiers', Array)
#3 /usr/share/icingaweb2/modules/director/library/Director/Objects/ImportSource.php(107): Icinga\Module\Director\Data\Db\DbObject->setProperties(Array)
#4 /usr/share/icingaweb2/modules/director/library/Director/DirectorObject/Automation/BasketSnapshot.php(277): Icinga\Module\Director\Objects\ImportSource::import(Object(stdClass), Object(Icinga\Module\Director\Db), true)
#5 /usr/

#0 [internal function]: Icinga\Application\Web->Icinga\Application\{closure}()
#1 {main}
``` 

This is the version v1.7.2

**Comment by Thomas-Gelf** [comment]
This has been fixed with the small fix in a7c2174, it hasn't been released yet

**Comment by mkayontour** [comment]
Awesome, patched the file and it works like expected :) 

Thanks

**Comment by kajla** [comment]
Thanks, it's works.

**Comment by RincewindsHat** [comment]
I guess this can be closed then?
