### ISSUE TITLE
Failed to start director background daemon

### ISSUE THREAD

**Issue by bahrpatrick** [Icinga/icingaweb2-module-director#2018]
## Your Environment

* Director version (System - About): 1.7.2
* Icinga Web 2 version and modules (System - About): 2.7.3
* Icinga 2 version (`icinga2 --version`): 2.11.2
* Operating System and version: CentOS 7.7
* Webserver, PHP versions: httpd php 7.1

Hello,
I´ve just updated our Icinga2 environment to Version 2.11.2 from 2.11.0.
Now I got some problems with the Icinga Director Background Daemon.

The systemd service won´t start.
`● icinga-director.service - Icinga Director - Monitoring Configuration
   Loaded: loaded (/etc/systemd/system/icinga-director.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Mon 2019-11-11 13:12:42 CET; 49s ago
     Docs: https://icinga.com/docs/director/latest/
 Main PID: 24521 (code=exited, status=255)
   CGroup: /system.slice/icinga-director.service

Nov 11 13:12:42 IPSNBG6SRV01.dc.iso-hosting.net systemd[1]: icinga-director.service: main process exited, code=exited, status=255/n/a
Nov 11 13:12:42 IPSNBG6SRV01.dc.iso-hosting.net systemd[1]: Failed to start Icinga Director - Monitoring Configuration.
Nov 11 13:12:42 IPSNBG6SRV01.dc.iso-hosting.net systemd[1]: Unit icinga-director.service entered failed state.
Nov 11 13:12:42 IPSNBG6SRV01.dc.iso-hosting.net systemd[1]: icinga-director.service failed.`

I tried to reinstall the director module with the latest version but this also didn´t resolved the problem.

When I´m trying to run the director daemon manual the following error occurs:

`Launching the run script /usr/share/icingaweb2/modules/director/run.php for module director failed with the following exception: Missing dependencies, please check
PHP Fatal error:  Uncaught Error: Class 'React\EventLoop\Factory' not found in /usr/share/icingaweb2/modules/director/library/Director/Daemon/BackgroundDaemon.php:48
Stack trace:
#0 /usr/share/icingaweb2/modules/director/application/clicommands/DaemonCommand.php(24): Icinga\Module\Director\Daemon\BackgroundDaemon->run()
#1 /usr/share/php/Icinga/Cli/Loader.php(265): Icinga\Module\Director\Clicommands\DaemonCommand->runAction()
#2 /usr/share/php/Icinga/Application/Cli.php(152): Icinga\Cli\Loader->dispatch()
#3 /usr/share/php/Icinga/Application/Cli.php(142): Icinga\Application\Cli->dispatchOnce()
#4 /usr/bin/icingacli(7): Icinga\Application\Cli->dispatch()
#5 {main}
  thrown in /usr/share/icingaweb2/modules/director/library/Director/Daemon/BackgroundDaemon.php on line 48

Fatal error: Uncaught Error: Class 'React\EventLoop\Factory' not found in /usr/share/icingaweb2/modules/director/library/Director/Daemon/BackgroundDaemon.php:48
Stack trace:
#0 /usr/share/icingaweb2/modules/director/application/clicommands/DaemonCommand.php(24): Icinga\Module\Director\Daemon\BackgroundDaemon->run()
#1 /usr/share/php/Icinga/Cli/Loader.php(265): Icinga\Module\Director\Clicommands\DaemonCommand->runAction()
#2 /usr/share/php/Icinga/Application/Cli.php(152): Icinga\Cli\Loader->dispatch()
#3 /usr/share/php/Icinga/Application/Cli.php(142): Icinga\Application\Cli->dispatchOnce()
#4 /usr/bin/icingacli(7): Icinga\Application\Cli->dispatch()
#5 {main}
  thrown in /usr/share/icingaweb2/modules/director/library/Director/Daemon/BackgroundDaemon.php on line 48
`
Seems like something is missing but I´m not sure what.

Thanks for your help

Patrick

**Comment by bahrpatrick** [comment]
Fixed the daemon.
The Problem was caused by the configuration based in /etc/icingaweb2/ after the update. In my environment the icingaweb2 configuration is installed to another location.
