### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Cannot access empty property in /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObject.php:3086

### ISSUE THREAD

**Issue by Aleksey-Maksimov** [Icinga/icingaweb2-module-director#2040]
Hello.

I experimented with **icingacli** and somehow wrote the value to an empty variable in the host properties.

```
# icingacli director host show switch001.holding.com

object Host "switch001.holding.com" {
    import "Cisco Switch"

    display_name = "SW001"
    address = "10.1.5.7"
    vars[""] = "snmp_SNMPv2_MIB_sysObjectID"
    vars.IOS = "\"Cisco"
    vars.snmp_SNMPv2_MIB_sysContact = "\"\""
    vars.snmp_SNMPv2_MIB_sysLocation = "\"\""
    vars.snmp_SNMPv2_MIB_sysObjectID = "1.3.6.1.4.1.9.1.563"
    vars.snmp_community = "public"
    vars.snmp_version = "1"
}
```
Now I can’t save anything any changes to this host and can’t delete it.

```
# icingacli director host delete switch001.holding.com

PHP Fatal error:  Uncaught Error: Cannot access empty property in /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObject.php:3086
Stack trace:
#0 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObject.php(1625): Icinga\Module\Director\Objects\IcingaObject->getPlainUnmodifiedObject()
#1 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaHost.php(359): Icinga\Module\Director\Objects\IcingaObject->beforeDelete()
#2 /usr/share/icingaweb2/modules/director/library/Director/Data/Db/DbObject.php(1017): Icinga\Module\Director\Objects\IcingaHost->beforeDelete()
#3 /usr/share/icingaweb2/modules/director/library/Director/Cli/ObjectCommand.php(234): Icinga\Module\Director\Data\Db\DbObject->delete()
#4 /usr/share/php/Icinga/Cli/Loader.php(265): Icinga\Module\Director\Cli\ObjectCommand->deleteAction()
#5 /usr/share/php/Icinga/Application/Cli.php(152): Icinga\Cli\Loader->dispatch()
#6 /usr/share/php/Icinga/Application/Cli.php(142): Icinga\Application\Cli->dispatchOnce()
#7 /usr/bi in /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObject.php on line 3086

Fatal error: Uncaught Error: Cannot access empty property in /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObject.php:3086
Stack trace:
#0 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObject.php(1625): Icinga\Module\Director\Objects\IcingaObject->getPlainUnmodifiedObject()
#1 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaHost.php(359): Icinga\Module\Director\Objects\IcingaObject->beforeDelete()
#2 /usr/share/icingaweb2/modules/director/library/Director/Data/Db/DbObject.php(1017): Icinga\Module\Director\Objects\IcingaHost->beforeDelete()
#3 /usr/share/icingaweb2/modules/director/library/Director/Cli/ObjectCommand.php(234): Icinga\Module\Director\Data\Db\DbObject->delete()
#4 /usr/share/php/Icinga/Cli/Loader.php(265): Icinga\Module\Director\Cli\ObjectCommand->deleteAction()
#5 /usr/share/php/Icinga/Application/Cli.php(152): Icinga\Cli\Loader->dispatch()
#6 /usr/share/php/Icinga/Application/Cli.php(142): Icinga\Application\Cli->dispatchOnce()
#7 /usr/bi in /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObject.php on line 3086
```
I get a similar error if I try to change or delete a host from WebUI

![image](https://user-images.githubusercontent.com/17614847/69897683-6cb7e280-1360-11ea-93d4-7bdcca363153.png)

Please give advice on what to do now and how to fix it.

**Comment by Aleksey-Maksimov** [comment]
Can someone help?

**Comment by Thomas-Gelf** [comment]
Hi @Aleksey-Maksimov,

it'd love to learn how you managed it to create this :D As a quick-fix I'd suggest to delete this variable from your database. Please first check whether there is only this one:

```sql
SELECT * FROM icinga_host_var WHERE varname = '';
``` 

If so, then delete it:


```sql
DELETE FROM icinga_host_var WHERE varname = '';
``` 

This will not show up in your activity log, but at least it fixes your problem.

Cheers,
Thomas

**Comment by Aleksey-Maksimov** [comment]
The problem is solved! 
Thanks more for the help, Thomas. 
Good luck.
