### ISSUE TITLE
After creating a 'data field category', 'modify' host template throws an exception

### ISSUE THREAD

**Issue by NeverUsedID** [Icinga/icingaweb2-module-director#2041]
## Current Behavior
A Click on "modify" at the host template generates the following error:

```
Form elements check_execution and custom_fields:Command Parameters have the same order (60) - this would result in only the last added element to be rendered (Form.php:3399)
#0 /usr/share/icingaweb2/library/vendor/Zend/Form.php(3295): Zend_Form->_sort()
#1 /usr/share/icingaweb2/library/vendor/Zend/Form/Decorator/FormElements.php(83): Zend_Form->rewind()
#2 /usr/share/icingaweb2/library/vendor/Zend/Form.php(2974): Zend_Form_Decorator_FormElements->render('')
#3 /usr/share/icingaweb2/modules/ipl/vendor/ipl/html/src/HtmlDocument.php(273): Zend_Form->render()
#4 /usr/share/icingaweb2/modules/ipl/vendor/ipl/html/src/BaseHtmlElement.php(175): ipl\Html\HtmlDocument->renderUnwrapped()
#5 /usr/share/icingaweb2/modules/ipl/vendor/ipl/html/src/BaseHtmlElement.php(213): ipl\Html\BaseHtmlElement->renderContent()
#6 /usr/share/icingaweb2/modules/ipl/vendor/ipl/html/src/HtmlDocument.php(211): ipl\Html\BaseHtmlElement->renderUnwrapped()
#7 /usr/share/icingaweb2/modules/ipl/vendor/ipl/html/src/HtmlDocument.php(285): ipl\Html\HtmlDocument->render()
#8 /usr/share/icingaweb2/modules/incubator/vendor/gipfl/icingaweb2/src/Zf1/SimpleViewRenderer.php(65): ipl\Html\HtmlDocument->__toString()
#9 /usr/share/icingaweb2/modules/incubator/vendor/gipfl/icingaweb2/src/Zf1/SimpleViewRenderer.php(104): gipfl\IcingaWeb2\Zf1\SimpleViewRenderer->render()
#10 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker.php(272): gipfl\IcingaWeb2\Zf1\SimpleViewRenderer->postDispatch()
#11 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(518): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#12 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('editAction')
#13 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#14 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#15 /usr/share/php/Icinga/Application/webrouter.php(99): Icinga\Application\Web->dispatch()
#16 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#17 {main}
```

The Command Parameters Category has 43 elements in it. 

## Possible Workaround

Delete some field randomly in the category.  Havn't found the data field yet, which caused the error.

## Your Environment

* Director version (System - About): master -596e352761dd6aca98da09389115e21f974eba39
reactbundle: >=0.7.0
ipl: >=0.3.0
incubator: >=0.5.0
--
* Icinga Web 2 version and modules (System - About): 2.7.3

* Webserver, PHP versions: 7.3

**Comment by Thomas-Gelf** [comment]
Haven't been able to reproduce this, but looks like a bug

**Comment by joni1993** [comment]
Just came across this as well:
```
Form elements clustering and custom_fields:Services_Mail have the same order (80) - this would result in only the last added element to be rendered (Form.php:3399)

#0 /usr/share/icingaweb2/library/vendor/Zend/Form.php(3295): Zend_Form->_sort()
#1 /usr/share/icingaweb2/library/vendor/Zend/Form/Decorator/FormElements.php(83): Zend_Form->rewind()
#2 /usr/share/icingaweb2/library/vendor/Zend/Form.php(2974): Zend_Form_Decorator_FormElements->render('')
#3 /usr/share/icingaweb2/modules/ipl/vendor/ipl/html/src/HtmlDocument.php(273): Zend_Form->render()
#4 /usr/share/icingaweb2/modules/ipl/vendor/ipl/html/src/BaseHtmlElement.php(175): ipl\Html\HtmlDocument->renderUnwrapped()
#5 /usr/share/icingaweb2/modules/ipl/vendor/ipl/html/src/BaseHtmlElement.php(213): ipl\Html\BaseHtmlElement->renderContent()
#6 /usr/share/icingaweb2/modules/ipl/vendor/ipl/html/src/HtmlDocument.php(211): ipl\Html\BaseHtmlElement->renderUnwrapped()
#7 /usr/share/icingaweb2/modules/ipl/vendor/ipl/html/src/HtmlDocument.php(285): ipl\Html\HtmlDocument->render()
#8 /usr/share/icingaweb2/modules/incubator/vendor/gipfl/icingaweb2/src/Zf1/SimpleViewRenderer.php(65): ipl\Html\HtmlDocument->__toString()
#9 /usr/share/icingaweb2/modules/incubator/vendor/gipfl/icingaweb2/src/Zf1/SimpleViewRenderer.php(104): gipfl\IcingaWeb2\Zf1\SimpleViewRenderer->render()
#10 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker.php(272): gipfl\IcingaWeb2\Zf1\SimpleViewRenderer->postDispatch()
#11 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(518): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#12 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('indexAction')
#13 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#14 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#15 /usr/share/php/Icinga/Application/webrouter.php(99): Icinga\Application\Web->dispatch()
#16 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#17 {main}
```

**Comment by joni1993** [comment]
I could bypass the error by increasing the static number in 
https://github.com/Icinga/icingaweb2-module-director/blob/b1c29c16d02a858cfcb377177ead605613db9a95/library/Director/Web/Form/IcingaObjectFieldLoader.php#L265                 and
https://github.com/Icinga/icingaweb2-module-director/blob/b1c29c16d02a858cfcb377177ead605613db9a95/library/Director/Web/Form/IcingaObjectFieldLoader.php#L258
by 500.

I don't know where this values (50,51) come from... Maybe @Thomas-Gelf can clear this up?

**Comment by joni1993** [comment]
Seems like custom_fields previously had the order of 50 and the new categories are now just 51.... But depending on the number of categories this will overlap with orders of other "groups" (clustering, check_execution).

Maybe the custom_fields + the categories should just be last and use a high number to ensure no overlapping
