### ISSUE TITLE
Reactbundle breaks director

### ISSUE THREAD

**Issue by kort3x** [Icinga/icingaweb2-module-director#2087]
Hi all,

complete noob so please be gentle :)

After installing the reactbundle http://icinga/icingaweb2/director throws:

```
 Undefined property: Icinga\Module\Director\Controllers\IndexController::$window

#0 /usr/share/icingaweb2/modules/director/library/Director/Web/Controller/ActionController.php(78): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(8, 'Undefined prope...', '/usr/share/icin...', 78, Array)
#1 /usr/share/icingaweb2/modules/director/library/Director/Web/Controller/Extension/DirectorDb.php(130): Icinga\Module\Director\Web\Controller\ActionController->Window()
#2 /usr/share/icingaweb2/modules/director/library/Director/Web/Controller/Extension/DirectorDb.php(49): Icinga\Module\Director\Web\Controller\ActionController->getWindowSessionValue('db_resource')
#3 /usr/share/icingaweb2/modules/director/application/controllers/IndexController.php(53): Icinga\Module\Director\Web\Controller\ActionController->getPreferredDbResourceName()
#4 /usr/share/icingaweb2/modules/director/application/controllers/IndexController.php(42): Icinga\Module\Director\Controllers\IndexController->showKickstartForm()
#5 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Director\Controllers\IndexController->indexAction()
#6 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('indexAction')
#7 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#8 /usr/share/php/Icinga/Application/Web.php(389): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#9 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
#10 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#11 {main}
```

## Your Environment
* Icinga
Director version (System - About): master
Icinga Web 2 version: 2.4.1
incubator: 0.5.0
ipl v0.4.0:
monitoring: 2.4.1
reactbundle: 0.7.0
Icinga 2 version: r2.8.1

* Operating System and version:
   Ubuntu 18.04.4 LTS 

* Webserver, PHP versions:
apache 2.4.29
PHP 7.1.33
Zend Engine v3.1.0

**Comment by Thomas-Gelf** [comment]
Sorry for the late reply. The problem should have been the Icinga Web 2 version, please try at least v2.6. In case the problem persists please let us know.
