### ISSUE TITLE
Got invalid parent id 7 for timeperiod "1 o'clock"

### ISSUE THREAD

**Issue by kirijanj** [Icinga/icingaweb2-module-director#2118]
## Your Environment

* Director version (System - About):
* Icinga Web 2 version and modules (System - About):
* Icinga 2 version (`icinga2 --version`):
* Operating System and version:
* Webserver, PHP versions:

**Comment by kirijanj** [comment]
Hi, 

I'm getting error "Got invalid parent id 7 for timeperiod "1 o'clock" while creating timeperiod configuration.

When click the timeperiod, it's showing like

#0 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObject.php(2950): Icinga\Module\Director\Resolver\TemplateTree->listParentNamesFor(Object(Icinga\Module\Director\Objects\IcingaTimePeriod))
#1 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObject.php(956): Icinga\Module\Director\Objects\IcingaObject->listImportNames()
#2 /usr/share/icingaweb2/modules/director/library/Director/Data/Db/DbObject.php(238): Icinga\Module\Director\Objects\IcingaObject->getImports()
#3 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObject.php(683): Icinga\Module\Director\Data\Db\DbObject->get(String)
#4 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/DirectorObjectForm.php(849): Icinga\Module\Director\Objects\IcingaObject->get(String)
#5 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/DirectorObjectForm.php(801): Icinga\Module\Director\Web\Form\DirectorObjectForm->setDefaultsFromObject(Object(Icinga\Module\Director\Objects\IcingaTimePeriod))
#6 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(583): Icinga\Module\Director\Web\Form\DirectorObjectForm->onRequest()
#7 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(597): Icinga\Module\Director\Web\Form\QuickForm->setRequest(Object(Icinga\Web\Request))
#8 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(376): Icinga\Module\Director\Web\Form\QuickForm->getRequest()
#9 /usr/share/icingaweb2/modules/director/library/Director/Web/Controller/ObjectController.php(532): Icinga\Module\Director\Web\Form\QuickForm->handleRequest()
#10 /usr/share/icingaweb2/modules/director/library/Director/Web/Controller/ObjectController.php(135): Icinga\Module\Director\Web\Controller\ObjectController->addObjectForm(Object(Icinga\Module\Director\Objects\IcingaTimePeriod))
#11 /usr/share/icingaweb2/modules/director/library/Director/Web/Controller/ObjectController.php(99): Icinga\Module\Director\Web\Controller\ObjectController->editAction()
#12 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Director\Web\Controller\ObjectController->indexAction()
#13 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#14 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#15 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#16 /usr/share/php/Icinga/Application/webrouter.php(99): Icinga\Application\Web->dispatch()
#17 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#18 {main}

**Comment by kirijanj** [comment]
please help on this ...
