### ISSUE TITLE
SelfService API Unable to fetch Agent Ticket

### ISSUE THREAD

**Issue by arogic** [Icinga/icingaweb2-module-director#2127]
## Expected Behavior
Following the [Documentation](https://github.com/Icinga/icingaweb2-module-director/blob/master/doc/70-REST-API.md#agent-tickets) to fetch Tickets through the API by running the following:
```bash
curl -s -u admin:password -H 'Accept: application/json' -X GET 'http://icingaweb2/icingaweb2/director/host/ticket?name=icinga2-client'
```

## Current Behavior
Getting following error instead of a Ticket response:
```
{
    "error": "Failed to load icinga_host \"icinga2-client\""
}
```
When I try to access the URL: http://icingaweb2/icingaweb2/director/host/ticket?name=icinga2-client in a browser I get:
```
Failed to load icinga_host "icinga2-client"

#0 /usr/share/icingaweb2/modules/director/library/Director/Data/Db/DbObject.php(1173): Icinga\Module\Director\Data\Db\DbObject->loadFromDb()
#1 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObject.php(2589): Icinga\Module\Director\Data\Db\DbObject::load(String, Object(Icinga\Module\Director\Db))
#2 /usr/share/icingaweb2/modules/director/library/Director/Web/Controller/ObjectController.php(458): Icinga\Module\Director\Objects\IcingaObject::loadByType(String, String, Object(Icinga\Module\Director\Db))
#3 /usr/share/icingaweb2/modules/director/library/Director/Web/Controller/ObjectController.php(441): Icinga\Module\Director\Web\Controller\ObjectController->loadObject()
#4 /usr/share/icingaweb2/modules/director/library/Director/Web/Controller/ObjectController.php(75): Icinga\Module\Director\Web\Controller\ObjectController->eventuallyLoadObject()
#5 /usr/share/php/Icinga/Web/Controller/ActionController.php(152): Icinga\Module\Director\Web\Controller\ObjectController->init()
#6 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(59): Icinga\Web\Controller\ActionController->__construct(Object(Icinga\Web\Request), Object(Icinga\Web\Response), Array)
#7 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#8 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#9 /usr/share/php/Icinga/Application/webrouter.php(99): Icinga\Application\Web->dispatch()
#10 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#11 {main}
```

## Your Environment
icinga2 agent has been installed on the machine where I am trying to fetch the Agent Ticket through the Director SelfService API.
* Director version (System - About): 1.7.2
* Icinga Web 2 version and modules (System - About): 2.7.3
* Icinga 2 version (`icinga2 --version`): r2.11.3-1
* Operating System and version: Ubuntu 18.04.4 LTS (Bionic Beaver)
* Webserver, PHP versions: Apache, 7.2.24-0ubuntu0.18.04.4

**Comment by arogic** [comment]
Hi,

I figured it out. I made a mistake and specified the hostname of the client instead of using the name of the "Host Template". 
```bash
curl -s -u admin:password -H 'Accept: application/json' \
 -X GET 'http://icingaweb2/icingaweb2/director/host/ticket?name=windows-agent'
```
result:
```
"735e9dd547980c9eecf161c45a2f7f62342423"
```

All works now. Closing this Issue.

Regards
