### ISSUE TITLE
[...] setAutorefreshInterval($interval) should be compatible with [...]

### ISSUE THREAD

**Issue by Foxeronie** [Icinga/icingaweb2-module-director#2254]
Hi!

I get the following error with the current master:

```
ErrorException in /opt/icingaweb2/modules/director/library/Director/Web/Controller/ActionController.php:132 with message: Declaration of Icinga\Module\Director\Web\Controller\ActionController::setAutorefreshInterval($interval) should be compatible with Icinga\Web\Controller\ActionController::setAutorefreshInterval($interval, $bypassUserPreferences = false)
#0 /opt/icingaweb2/modules/director/library/Director/Web/Controller/ActionController.php(27): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}()
#1 /usr/share/icingaweb2/library/Icinga/Application/ClassLoader.php(303): require(String)
#2 [internal function]: Icinga\Application\ClassLoader->loadClass()
#3 /opt/icingaweb2/modules/director/application/controllers/DashboardController.php(12): spl_autoload_call()
#4 /usr/share/icingaweb2/library/Icinga/Application/ClassLoader.php(303): require(String)
#5 [internal function]: Icinga\Application\ClassLoader->loadClass()
#6 /opt/icingaweb2/modules/director/application/controllers/IndexController.php(12): spl_autoload_call()
#7 /usr/share/icingaweb2/library/Icinga/Application/ClassLoader.php(303): require(String)
#8 [internal function]: Icinga\Application\ClassLoader->loadClass()
#9 [internal function]: spl_autoload_call()
#10 /usr/share/icingaweb2/library/Icinga/Web/Controller/Dispatcher.php(55): class_exists()
#11 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch()
#12 /usr/share/icingaweb2/library/Icinga/Application/Web.php(301): Zend_Controller_Front->dispatch()
#13 /usr/share/icingaweb2/library/Icinga/Application/webrouter.php(105): Icinga\Application\Web->dispatch()
#14 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#15 {main} 
```
Autorefresh is enabled with Default speed. Also happens if autorefresh is disabled (don't know if this is the problem, only saw the error message).

* Director version (System - About): master: commit 0544b57db4273976d938ee48b21a57d7caf8c483
* Icinga Web 2 version and modules (System - About): 2.8.2 - commit 53388a394044f778135ec8b582627fbdda271ec8
* Icinga 2 version (`icinga2 --version`): r2.12.1-1
* Operating System and version: Ubuntu 20.04
* Webserver, PHP versions: Apache 2.4.41-4ubuntu3.1 - PHP 7.4.3-4ubuntu2.4

incubator: stable/0.6.0
ipl: stable/0.5.0
reactbundle: stable/0.8.0

Best regards,
Patrick

**Comment by Thomas-Gelf** [comment]
Hi Patrick,

you're probably using a recent GIT master of Icinga Web 2. Please open `library/Icinga/Web/Controller/ActionController.php` and change it as follows:

```patch
-    public function setAutorefreshInterval($interval, $bypassUserPreferences = false)
-    {
+    public function setAutorefreshInterval($interval)
+    {
+        $bypassUserPreferences = false
```
 
There is already a related pull request (4293) available in the icingaweb2 repository.

**Comment by Foxeronie** [comment]
You are right and that fixed the problem. Thank you for the fast response. :)
