### ISSUE TITLE
unable to render host in module director host view

### ISSUE THREAD

**Issue by Marci24h** [Icinga/icingaweb2-module-director#2255]
# unable to render host in module director host view

## Expected Behavior
In the module director within icingaweb it should be possible to click on a hostobject
Icinga Director -> Hosts -> Hosts -> select a host
the host details should be shown in the right pane

## Current Behavior
If assignin a Hostgroup directly to a single host to override the one inherited from the host template, rendering the Host in Icinga Director module will fail after upgrading from Director v1.7.2 to v1.8.0

If switching back to version 1.7.2 with `git checkout v1.7.2` the error is gone away
After `git checkout v1.8.0` the error reoccurs

## Steps to Reproduce
Assign a Hostgroup directly to host object
it doesn't matter if the group is already inherited from the template or if it's a different group

### error message in icingaweb module director

```
Uncaught Error: Call to undefined method ipl\Html\Text::addAttributes() in /usr/share/icingaweb2/modules/director/application/forms/IcingaHostForm.php:233
Stack trace:
#0 /usr/share/icingaweb2/modules/director/application/forms/IcingaHostForm.php(60): Icinga\Module\Director\Forms\IcingaHostForm->addGroupsElement()
#1 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(370): Icinga\Module\Director\Forms\IcingaHostForm->setup()
#2 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(587): Icinga\Module\Director\Web\Form\QuickForm->prepareElements()
#3 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(602): Icinga\Module\Director\Web\Form\QuickForm->setRequest(Object(Icinga\Web\Request))
#4 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(381): Icinga\Module\Director\Web\Form\QuickForm->getRequest()
#5 /usr/share/icingaweb2/modules/director/library/Director/Web/Controller/ObjectController.php(536): Ici

#0 [internal function]: Icinga\Application\Web->Icinga\Application\{closure}()
#1 {main}
```

![20201218_issue_director_render_host_groups](https://user-images.githubusercontent.com/43334930/102600414-11998f00-411f-11eb-9e0d-fc381f3e3750.png)

### related configurations
```
zones.d/director-global/host_templates.conf
template Host "server-linux" {
    check_command = "hostalive_custom"
    max_check_attempts = "3"
    check_interval = 3m
    retry_interval = 29s
    check_timeout = 7s
    enable_active_checks = true
    enable_passive_checks = true
    enable_perfdata = true
    notes = "Linux Clients"
    groups = [ "linux", "server" ]
}


zones.d/zone-agent/hosts.conf
object Host "server.sub.domain.tld" {
    import "server-linux"

    address = "10.2.3.4"
    groups = [ "linux" ] # <- after adding a group the object can not displayed anymore - error is thrown
    vars.OperatingSystem = "debian"
    vars.network_interfaces = [ "enp1s0", "eth1" ]
    vars.parent_host = [ "vhost.sub.domain.tld" ]
}

zones.d/zone-agent/agent_endpoints.conf
object Endpoint "server.sub.domain.tld" {
    log_duration = 0s
}

zones.d/zone-agent/agent_zones.conf
object Zone "server.sub.domain.tld" {
    parent = "zone-agent"
    endpoints = [ "server.sub.domain.tld" ]
}
```

### versions

icinga web runs on a different host than the icinga master, but in this case it shouldn't matter

#### webserver with icingaweb
OS: Debian GNU/Linux 10 (buster)
webserver: nginx version: nginx/1.14.2
PHP:
>PHP 7.3.19-1~deb10u1 (fpm-fcgi) (built: Jul  5 2020 06:46:45)
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.19, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.19-1~deb10u1, Copyright (c) 1999-2018, by Zend Technologies

DB: mysql  Ver 15.1 Distrib 10.3.25-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**Icinga Web 2 Version**
Version: 2.8.2
Git commit: 8a89839af94a247ee2149b2336c73b8251b477c0
PHP Version: 7.3.19-1~deb10u1

**Loaded modules**
director: 1.8.0
doc: 2.8.2
incubator: 0.6.0
ipl: v0.5.0
monitoring: 2.8.2
reactbundle: 0.8.0

#### icinga-master

**root@icinga-master:~# icinga2 --version**
```
icinga2 - The Icinga 2 network monitoring daemon (version: r2.12.1-1)

Copyright (c) 2012-2020 Icinga GmbH (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: Debian GNU/Linux
  Platform version: 10 (buster)
  Kernel: Linux
  Kernel version: 4.19.0-12-amd64
  Architecture: x86_64

Build information:
  Compiler: GNU 8.3.0
  Build host: runner-wytxxqbb-project-298-concurrent-0
  OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid
```

**root@icinga-master:~# icinga2 feature list**
```
Disabled features: command compatlog debuglog elasticsearch gelf graphite icingadb livestatus opentsdb perfdata statusdata syslog
Enabled features: api checker ido-mysql influxdb mainlog notification
```

**Comment by idandr** [comment]
Could this be a duplicate of #2253?

**Comment by Marci24h** [comment]
yes, that looks very similar.
sorry that i haven't found this issue.
i'll close this one.
