### ISSUE TITLE
Exception on clicking a host

### ISSUE THREAD

**Issue by friesoft** [Icinga/icingaweb2-module-director#2288]
## Expected Behavior
No exception on clicking a host in the Hosts list.

## Current Behavior
When clicking a host in the list of hosts the right panel opens with an exception instead of the host.

`array_key_exists(): The first argument should be either a string or an integer`

```
#0 [internal function]: Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(Integer, String, String, Integer, Array)
#1 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/DirectorObjectForm.php(635): array_key_exists(Array, Array)
#2 /usr/share/icingaweb2/modules/director/library/Director/Objects/DirectorDatafield.php(284): Icinga\Module\Director\Web\Form\DirectorObjectForm->setInheritedValue(Object(Zend_Form_Element_Select), Array, String)
#3 /usr/share/icingaweb2/modules/director/library/Director/Objects/DirectorDatafield.php(240): Icinga\Module\Director\Objects\DirectorDatafield->applyObjectData(Object(Zend_Form_Element_Select), Object(Icinga\Module\Director\Forms\IcingaHostForm))
#4 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/IcingaObjectFieldLoader.php(380): Icinga\Module\Director\Objects\DirectorDatafield->getFormElement(Object(Icinga\Module\Director\Forms\IcingaHostForm))
#5 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/IcingaObjectFieldLoader.php(183): Icinga\Module\Director\Web\Form\IcingaObjectFieldLoader->createElements(Object(Icinga\Module\Director\Forms\IcingaHostForm))
#6 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/IcingaObjectFieldLoader.php(200): Icinga\Module\Director\Web\Form\IcingaObjectFieldLoader->getElements(Object(Icinga\Module\Director\Forms\IcingaHostForm))
#7 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/DirectorObjectForm.php(470): Icinga\Module\Director\Web\Form\IcingaObjectFieldLoader->prepareElements(Object(Icinga\Module\Director\Forms\IcingaHostForm))
#8 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/DirectorObjectForm.php(827): Icinga\Module\Director\Web\Form\DirectorObjectForm->prepareFields(Object(Icinga\Module\Director\Objects\IcingaHost))
#9 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(588): Icinga\Module\Director\Web\Form\DirectorObjectForm->onRequest()
#10 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(602): Icinga\Module\Director\Web\Form\QuickForm->setRequest(Object(Icinga\Web\Request))
#11 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(381): Icinga\Module\Director\Web\Form\QuickForm->getRequest()
#12 /usr/share/icingaweb2/modules/director/library/Director/Web/Controller/ObjectController.php(536): Icinga\Module\Director\Web\Form\QuickForm->handleRequest()
#13 /usr/share/icingaweb2/modules/director/library/Director/Web/Controller/ObjectController.php(138): Icinga\Module\Director\Web\Controller\ObjectController->addObjectForm(Object(Icinga\Module\Director\Objects\IcingaHost))
#14 /usr/share/icingaweb2/modules/director/application/controllers/HostController.php(54): Icinga\Module\Director\Web\Controller\ObjectController->editAction()
#15 /usr/share/icingaweb2/modules/director/library/Director/Web/Controller/ObjectController.php(102): Icinga\Module\Director\Controllers\HostController->editAction()
#16 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Director\Web\Controller\ObjectController->indexAction()
#17 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#18 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#19 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#20 /usr/share/php/Icinga/Application/webrouter.php(99): Icinga\Application\Web->dispatch()
#21 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#22 {main}
```

We have found out that the variable "inherited" is of type array (with 1 element) instead of string or integer.

## Possible Solution
Our workaround currently is this:
```
diff --git a/library/Director/Web/Form/DirectorObjectForm.php b/library/Director/Web/Form/DirectorObjectForm.php
index fd8e0a6..1fde86d 100644
--- a/library/Director/Web/Form/DirectorObjectForm.php
+++ b/library/Director/Web/Form/DirectorObjectForm.php
@@ -629,6 +629,9 @@ abstract class DirectorObjectForm extends DirectorForm
             if (is_bool($inherited)) {
                 $inherited = $inherited ? 'y' : 'n';
             }
+            if (is_array($inherited) && count($inherited) == 1) {
+                $inherited = $inherited[0];
+            }
             if (array_key_exists($inherited, $multi)) {
                 $multi[null] = $multi[$inherited] . sprintf($txtInherited, $inheritedFrom);
             } else {
```

## Steps to Reproduce (for bugs)
Open hosts list and click on a host

## Your Environment
* Director version (System - About): happens with 1.8.0 and current master (e2a88861487e9cefad94776fd610b3a9703b9e03)
* Icinga Web 2 version and modules (System - About): 2.8.2
* Icinga 2 version (`icinga2 --version`): 2.12.3
* Operating System and version: RHEL 7.9
* Webserver, PHP versions: Apache httpd 2.4, PHP 7.3.20

**Comment by Nathaniel-Donahue** [comment]
ref/NC/702512

**Comment by raviks789** [comment]
@friesoft could you give more details about how the hosts were configured, how many templates are involved etc.

**Comment by friesoft** [comment]
Thats the host + template structure in Director (rendered using preview).
```
object Host "HOST4711" {
    import "template-linux-groupa"

    address = "192.168.10.11"
    notes = "Our server"
    groups = [ "groupa", "linux", "sysP" ]
    vars.nginxlogs = [  ]
    vars.arch = "lin64"
    vars.archname = "x86_64-linux-thread-multi"
    vars.directories = [  ]
    vars.disks = [ "/", "/opt" ]
    vars.nginxs = [
        "/opt/nginx_install1",
        "/opt/nginx_install2"
    ]
    vars.mysqls = [  ]
    vars.componentports = [  ]
    vars.official = "1"
    vars.os = "linux"
    vars.componentaccesslogs = [  ]
    vars.cm_version = "false"
    vars.relevant4prod = "1"
    vars.secondaryips = [
        "192.168.10.21",
        "192.168.10.31"
    ]
    vars.serviceproviders = [  ]
    vars.appllogs = [
        "/logs/nginx_install1/appl.log",
        "/logs/nginx_install2/appl.log"
    ]
    vars.appls = [  ]
    vars.ssh_user = "icinga"
    vars.websphere_ajps = [
        "/opt/websphere_install1:127.0.0.1:10009",
        "/opt/websphere_install2:127.0.0.1:8009"
    ]
    vars.webspheres = [
        "/opt/websphere_install1",
        "/opt/websphere_install2"
    ]
    vars.vhosts = ""
    vars.compontentconfigs = [
        "/opt/nginx_install1/conf/appl.conf",
        "/opt/nginx_install2/conf/appl.conf"
    ]
}


---------

template Host "template-linux-groupa" {
    import "template-linux"

    vars.notify_groups = [ "ICINGA_NOTIFYGROUP_EV" ]
    vars.permission = [ "groupa" ]
}


-------


template Host "template-linux" {
    check_command = "hostalive"
    max_check_attempts = "3"
    check_interval = 15s
    retry_interval = 10s
    check_timeout = 1m
    enable_notifications = true
    enable_active_checks = true
    enable_passive_checks = true
    enable_event_handler = true
    enable_flapping = true
    enable_perfdata = true
    volatile = true
    notes_url = "https://test.com/$host.name$"
    icon_image = "tux.png"
    icon_image_alt = "Linux"
    vars.os = [ "linux" ]
    vars.permission = [ "asdf", "groupa" ]
    vars.ssh_user = "icinga"
}
```

All Fields are set on the host Template "template-linux":
* vars.nginxs
* vars.os (mandatory)
* vars.webspheres
* vars.permission
* vars.ssh_user (mandatory)
* vars.websphere_ajps
* vars.notify_groups
* vars.notify_no_backup
* vars.notify_times
* vars.notify
* vars.compontentconfigs

All fields are imported/synced from a mysql datasource.

**Comment by Thomas-Gelf** [comment]
The problem here is that:

* a select box type field has been configured
* parent has an array for that variable, the code doesn't expect this

IMHO the template should be fixed, as such mixed-type-vars are never a good idea. Anyway, the code should of course not fail in this scenario. Will be fixed.

**Comment by Thomas-Gelf** [comment]
Hint: added another commit which now also shows invalid inherited data. In your case it's probably `[ "linux" ]` instead of `"linux"` on `template-linux`. The former fix catches this, your problem should be fixed. I'd nonetheless strongly suggest to fix the template by selecting `linux` in it's OS select box.

You didn't mention any details regarding configured fields, so this is just a wild assumption. I could be wrong, and the culprit might be another field. That's just the first one that attracted my attention while looking at your config preview.

Cheers,
Thomas

**Comment by friesoft** [comment]
Spot-on as always @Thomas-Gelf Thanks 🥳 
I guess this comes from us having a datalist for OS and there is no "target data type" choosen.

I can verify that the fix works (no exception anymore) :) Thanks!
