### ISSUE TITLE
Member of Service Group not displayed if service in Service Set

### ISSUE THREAD

**Issue by lucafwp** [Icinga/icingaweb2-module-director#2295]
## Expected Behavior
Clicking on a member of a servicegroup shoul show its details.

## Current Behavior
If a service, member of a servicegroup, is only available in a Service Set an error is displayed:

> Failed to load icinga_service for host_id IS NULL AND service_set_id IS NULL AND object_name = 'Test_test_test_try' AND object_type = 'template'

```
#0 /usr/share/icingaweb2/modules/director/library/Director/Data/Db/DbObject.php(1173): Icinga\Module\Director\Data\Db\DbObject->loadFromDb()
#1 /usr/share/icingaweb2/modules/director/application/controllers/ServiceController.php(237): Icinga\Module\Director\Data\Db\DbObject::load(Array, Object(Icinga\Module\Director\Db))
#2 /usr/share/icingaweb2/modules/director/library/Director/Web/Controller/ObjectController.php(441): Icinga\Module\Director\Controllers\ServiceController->loadObject()
#3 /usr/share/icingaweb2/modules/director/library/Director/Web/Controller/ObjectController.php(75): Icinga\Module\Director\Web\Controller\ObjectController->eventuallyLoadObject()
#4 /usr/share/icingaweb2/modules/director/application/controllers/ServiceController.php(45): Icinga\Module\Director\Web\Controller\ObjectController->init()
#5 /usr/share/php/Icinga/Web/Controller/ActionController.php(155): Icinga\Module\Director\Controllers\ServiceController->init()
#6 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(59): Icinga\Web\Controller\ActionController->__construct(Object(Icinga\Web\Request), Object(Icinga\Web\Response), Array)
#7 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#8 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#9 /usr/share/php/Icinga/Application/webrouter.php(99): Icinga\Application\Web->dispatch()
#10 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#11 {main} 
```

![image](https://user-images.githubusercontent.com/36190810/109320272-1fbb0880-7850-11eb-9946-a327a81a29b7.png)

## Steps to Reproduce (for bugs)

1. Create a new service named "test1"
2. Create a a new Service Set
3. Add a new service to Service Set which imports "test1" and rename it "test1_try"
4. Create a new service group with following rule: `service.name = *_try`
5. Show members of service group and click on "test1_try"

## Your Environment
* Director version (System - About): 1.7.2
* Icinga Web 2 version and modules (System - About): 2.8.2
* Icinga 2 version (`icinga2 --version`): 2.12.3
* Operating System and version: CentOS 7.9.2009
* Webserver, PHP versions: 7.3.11

**Comment by lucafwp** [comment]
Hi, are there any update on this issue?
