### ISSUE TITLE
REST API Import Source - JSON format and Key column name

### ISSUE THREAD

**Issue by Nauticus3** [Icinga/icingaweb2-module-director#2331]
## Expected Behavior
Use "foreign_id" as Key column name.

## Current Behavior
The value "attributes" is recognized as Key column name and it includes the entire list of properties instead of each entry separately.

## Steps to Reproduce (for bugs)
I try to use the below example info as Import Source in the Icinga Director. It is fetched in JSON format from a REST API source.

```
[
	{
		"attributes": {
			"id": 1,
			"foreign_id": "hostname1",
			"address": "192.0.0.1",
			"operating_system": "Microsoft Windows Server",
			"type": "Prod"
		}
	},
	{
		"attributes": {
			"id": 2,
			"foreign_id": "hostname2",
			"address": "192.0.0.2",
			"operating_system": "Linux Redhat",
			"type": "Test"
		}
	}
]
```

During the "Preview" it seems to read all the properties within "attributes" regardless of what I set as the "Key column name". 
![Capture](https://user-images.githubusercontent.com/63096701/119517183-af048900-bd77-11eb-81cd-c4be6d9c2a09.JPG)
![Capture2](https://user-images.githubusercontent.com/63096701/119518707-1111be00-bd79-11eb-82a5-304d6db78daf.JPG)

This causes the import to fail with the error:
This Import Source failed when last checked at 2021-05-25 16:46:30: First parameter must either be an object or the name of an existing class

Do you know if any solution to the problem?

## Your Environment
* Director version (System - About): 1.8.0
* Icinga Web 2 version and modules (System - About): 2.7.1
* Icinga 2 version (`icinga2 --version`): 2.11.5
* Operating System and version: RHEL 7

**Comment by Thomas-Gelf** [comment]
Hi @Nauticus3!

* `attributes` does not qualify for "key column", as it is an object
* there is no `foreign_id` on every row, but there is `attributes.foreign_id`

You should be able to flatten your data source by extracting `attributes`, and then you can set your key column to `foreign_id`

**Comment by Nauticus3** [comment]
Thank you @Thomas-Gelf for the quick reply!

![4](https://user-images.githubusercontent.com/63096701/119623857-dd7e7480-be08-11eb-8124-05d0b9b8cc40.JPG)

After setting `attributes` as Extract property and `foreign_id` as the key column I get this error:

```
Oops, an error occurred!
First parameter must either be an object or the name of an existing class (ImportSourceRestApi.php:74)
#0 [internal function]: Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(2, 'First parameter...', '/usr/share/icin...', 74, Array)
#1 /usr/share/icingaweb2/modules/director/library/Director/Import/ImportSourceRestApi.php(74): property_exists(Array, 'attributes')
#2 /usr/share/icingaweb2/modules/director/library/Director/Import/ImportSourceRestApi.php(25): Icinga\Module\Director\Import\ImportSourceRestApi->extractProperty(Array)
#3 /usr/share/icingaweb2/modules/director/library/Director/Web/Table/ImportsourceHookTable.php(100): Icinga\Module\Director\Import\ImportSourceRestApi->fetchData()
#4 /usr/share/icingaweb2/modules/incubator/vendor/gipfl/icingaweb2/src/Table/SimpleQueryBasedTable.php(29): Icinga\Module\Director\Web\Table\ImportsourceHookTable->prepareQuery()
#5 /usr/share/icingaweb2/modules/incubator/vendor/gipfl/icingaweb2/src/Table/SimpleQueryBasedTable.php(15): gipfl\IcingaWeb2\Table\SimpleQueryBasedTable->getQuery()
#6 /usr/share/icingaweb2/modules/incubator/vendor/gipfl/icingaweb2/src/Table/QueryBasedTable.php(56): gipfl\IcingaWeb2\Table\SimpleQueryBasedTable->getPaginationAdapter()
#7 /usr/share/icingaweb2/modules/incubator/vendor/gipfl/icingaweb2/src/Table/QueryBasedTable.php(255): gipfl\IcingaWeb2\Table\QueryBasedTable->getPaginator(Object(gipfl\IcingaWeb2\Url))
#8 /usr/share/icingaweb2/modules/director/application/controllers/ImportsourceController.php(162): gipfl\IcingaWeb2\Table\QueryBasedTable->renderTo(Object(Icinga\Module\Director\Controllers\ImportsourceController))
#9 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Director\Controllers\ImportsourceController->previewAction()
#10 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('previewAction')
#11 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#12 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#13 /usr/share/php/Icinga/Application/webrouter.php(99): Icinga\Application\Web->dispatch()
#14 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#15 {main}
```
