### ISSUE TITLE
Activity log link to service apply rule results in stack trace

### ISSUE THREAD

**Issue by log1-c** [Icinga/icingaweb2-module-director#2338]
## Expected Behavior

If you choose an action in the activity log, where a service apply rule has been changed and click the "service-name" link in the diff view it should open the corresponding service.

## Current Behavior

There still is a bug where you get only a stack trace when clicking on the service name, as already mentioned in https://github.com/Icinga/icingaweb2-module-director/issues/1377
The implemented fix only worked for services from service sets, though.
![image](https://user-images.githubusercontent.com/24474580/121020150-6352d600-c7a0-11eb-9b7a-5091c584e854.png)

Strack trace as text:
```
Failed to load icinga_service for host_id IS NULL AND service_set_id IS NULL AND object_name = 'cpu_perfcounter_exe' AND object_type = 'template'

#0 /usr/share/icingaweb2/modules/director/library/Director/Data/Db/DbObject.php(1173): Icinga\Module\Director\Data\Db\DbObject->loadFromDb()
#1 /usr/share/icingaweb2/modules/director/application/controllers/ServiceController.php(237): Icinga\Module\Director\Data\Db\DbObject::load(Array, Object(Icinga\Module\Director\Db))
#2 /usr/share/icingaweb2/modules/director/library/Director/Web/Controller/ObjectController.php(445): Icinga\Module\Director\Controllers\ServiceController->loadObject()
#3 /usr/share/icingaweb2/modules/director/library/Director/Web/Controller/ObjectController.php(78): Icinga\Module\Director\Web\Controller\ObjectController->eventuallyLoadObject()
#4 /usr/share/icingaweb2/modules/director/application/controllers/ServiceController.php(45): Icinga\Module\Director\Web\Controller\ObjectController->init()
#5 /usr/share/php/Icinga/Web/Controller/ActionController.php(155): Icinga\Module\Director\Controllers\ServiceController->init()
#6 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(59): Icinga\Web\Controller\ActionController->__construct(Object(Icinga\Web\Request), Object(Icinga\Web\Response), Array)
#7 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#8 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#9 /usr/share/php/Icinga/Application/webrouter.php(99): Icinga\Application\Web->dispatch()
#10 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#11 {main}
```

## Steps to Reproduce (for bugs)

1. Go to activiy log
2. Choose an entry where a service apply object (not a template, service set or service from a service set) got changed
3. In the "Diff" panel click on the link for the service name

## Your Environment

* Director version (System - About): 1.8.0
* Icinga Web 2 version and modules (System - About): 2.8.2
* Icinga 2 version (`icinga2 --version`): 2.12.3
* Operating System and version: CentOS 8/RHEL8

**Comment by log1-c** [comment]
fixed with v1.10.2
