### ISSUE TITLE
Unable to fetch ticket from Hosts->agent tab on Icingaweb2 after installing the master version of director.

### ISSUE THREAD

**Issue by Prathameshhankare** [Icinga/icingaweb2-module-director#2380]
## Current Behavior
I accidently installed master version of director module but it was working fine with no issues until I updated Icinga2 and icingaweb2 to the latest version(i.e 2.9.3 and 2.13.1 respectively). 
Now, after update I am unable to fetch tickets from Hosts--> Agent tab on Icingaweb2.

Below is the error I get:
`Requesting salt, but got none

#0 /usr/share/icingaweb2/modules/director/library/Director/IcingaConfig/AgentWizard.php(109): Icinga\Module\Director\IcingaConfig\AgentWizard->getTicketSalt()
#1 /usr/share/icingaweb2/modules/director/library/Director/IcingaConfig/AgentWizard.php(141): Icinga\Module\Director\IcingaConfig\AgentWizard->getTicket()
#2 /usr/share/icingaweb2/modules/director/library/Director/Web/SelfService.php(256): Icinga\Module\Director\IcingaConfig\AgentWizard->renderWindowsInstaller()
#3 /usr/share/icingaweb2/modules/director/library/Director/Web/SelfService.php(52): Icinga\Module\Director\Web\SelfService->showLegacyAgentInstructions(Object(Icinga\Module\Director\Controllers\HostController))
#4 /usr/share/icingaweb2/modules/director/application/controllers/HostController.php(544): Icinga\Module\Director\Web\SelfService->renderTo(Object(Icinga\Module\Director\Controllers\HostController))
#5 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Director\Controllers\HostController->agentAction()
#6 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#7 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#8 /usr/share/php/Icinga/Application/Web.php(304): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#9 /usr/share/php/Icinga/Application/webrouter.php(107): Icinga\Application\Web->dispatch()
#10 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#11 {main}`

## My Environment

* Director version (System - About): Master
* Icinga Web 2 version and modules (System - About): 2.9.3
* Icinga 2 version (`icinga2 --version`): 2.13.1
* Operating System and version: Centos 7
* Webserver, PHP versions: httpd(apache) - PHP-73

**Comment by Prathameshhankare** [comment]
This is resolved now. good to close the issue.
