### ISSUE TITLE
Some of the  Activity Log - modify Diffs throw bug

### ISSUE THREAD

**Issue by majales** [Icinga/icingaweb2-module-director#2392]
## Expected Behavior

To see "Diff" when I click to "modify" on Activity Log. Some of the diffs are OK and some throw error. This is happenning since Director update from previous  1.7.2. 

## Current Behavior

```
Uninitialized string offset: -1 (ArrayRenderer.php:134)
#0 /usr/share/icingaweb2/modules/incubator/vendor/gipfl/diff/src/PhpDiff/Renderer/Html/ArrayRenderer.php(134): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(8, 'Uninitialized s...', '/usr/share/icin...', 134, Array)
#1 /usr/share/icingaweb2/modules/incubator/vendor/gipfl/diff/src/PhpDiff/Renderer/Html/ArrayRenderer.php(67): gipfl\Diff\PhpDiff\Renderer\Html\ArrayRenderer->getChangeExtent('        "BSSHOP...', '        "BSSHOP...')
#2 /usr/share/icingaweb2/modules/incubator/vendor/gipfl/diff/src/PhpDiff/Renderer/Html/ArrayRenderer.php(34): gipfl\Diff\PhpDiff\Renderer\Html\ArrayRenderer->renderOpcodesGroup(Array, Array, Array)
#3 /usr/share/icingaweb2/modules/incubator/vendor/gipfl/diff/src/PhpDiff/Renderer/Html/SideBySide.php(18): gipfl\Diff\PhpDiff\Renderer\Html\ArrayRenderer->render()
#4 /usr/share/icingaweb2/modules/ipl/vendor/ipl/html/src/HtmlDocument.php(226): gipfl\Diff\PhpDiff\Renderer\Html\SideBySide->render()
#5 /usr/share/icingaweb2/modules/ipl/vendor/ipl/html/src/HtmlDocument.php(350): ipl\Html\HtmlDocument->renderUnwrapped()
#6 /usr/share/icingaweb2/modules/ipl/vendor/ipl/html/src/HtmlDocument.php(226): ipl\Html\HtmlDocument->render()
#7 /usr/share/icingaweb2/modules/ipl/vendor/ipl/html/src/BaseHtmlElement.php(255): ipl\Html\HtmlDocument->renderUnwrapped()
#8 /usr/share/icingaweb2/modules/ipl/vendor/ipl/html/src/BaseHtmlElement.php(339): ipl\Html\BaseHtmlElement->renderContent()
#9 /usr/share/icingaweb2/modules/ipl/vendor/ipl/html/src/HtmlDocument.php(350): ipl\Html\BaseHtmlElement->renderUnwrapped()
#10 /usr/share/icingaweb2/modules/ipl/vendor/ipl/html/src/HtmlDocument.php(252): ipl\Html\HtmlDocument->render()
#11 /usr/share/icingaweb2/modules/incubator/vendor/gipfl/icingaweb2/src/Zf1/SimpleViewRenderer.php(65): ipl\Html\HtmlDocument->__toString()
#12 /usr/share/icingaweb2/modules/incubator/vendor/gipfl/icingaweb2/src/Zf1/SimpleViewRenderer.php(104): gipfl\IcingaWeb2\Zf1\SimpleViewRenderer->render()
#13 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker.php(272): gipfl\IcingaWeb2\Zf1\SimpleViewRenderer->postDispatch()
#14 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(518): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#15 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('activityAction')
#16 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#17 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#18 /usr/share/php/Icinga/Application/webrouter.php(104): Icinga\Application\Web->dispatch()
#19 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#20 {main}
```
## Your Environment

* Director version (System - About): 1.8.1
* Icinga Web 2 version and modules (System - About): 2.6.3
* Icinga 2 version (`icinga2 --version`): 2.8.4
* Operating System and version: Ubuntu 16 LTS
* Webserver, PHP versions: Apache 2.4.18, Php 7.0

**Comment by RandomUser0815** [comment]
I have the same error. The interesting thing is, that not every entry shows this error.
For one host, I have about 12 entries in the activity log. 6 entries show this issue, others don't, and the diffs are OK, as @majales said above.

URL: https://icinga.eyeworkers.de/director/host/history?uuid=b80732ca-d5db-494e-9448-21970000002a#!/director/config/activity?id=1753

`Uncaught Error: Call to undefined function gipfl\Diff\PhpDiff\Renderer\Html\mb_strlen() in /usr/share/icingaweb2/modules/incubator/vendor/gipfl/diff/src/PhpDiff/Renderer/Html/ArrayRenderer.php:41
Stack trace:
#0 /usr/share/icingaweb2/modules/incubator/vendor/gipfl/diff/src/PhpDiff/Renderer/Html/ArrayRenderer.php(69): gipfl\Diff\PhpDiff\Renderer\Html\ArrayRenderer->insertLineMarkers()
#1 /usr/share/icingaweb2/modules/incubator/vendor/gipfl/diff/src/PhpDiff/Renderer/Html/ArrayRenderer.php(34): gipfl\Diff\PhpDiff\Renderer\Html\ArrayRenderer->renderOpcodesGroup()
#2 /usr/share/icingaweb2/modules/incubator/vendor/gipfl/diff/src/PhpDiff/Renderer/Html/SideBySide.php(18): gipfl\Diff\PhpDiff\Renderer\Html\ArrayRenderer->render()
#3 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(338): gipfl\Diff\PhpDiff\Renderer\Html\SideBySide->render()
#4 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(516): ipl\Html\HtmlDocument->renderUnwrapped()
#5 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(338): ipl\Html\HtmlDocument->render()
#6 /usr/share/icinga-php/ipl/vendor/ipl/html/src/BaseHtmlElement.php(297): ipl\Html\HtmlDocument->renderUnwrapped()
#7 /usr/share/icinga-php/ipl/vendor/ipl/html/src/BaseHtmlElement.php(365): ipl\Html\BaseHtmlElement->renderContent()
#8 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(516): ipl\Html\BaseHtmlElement->renderUnwrapped()
#9 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(368): ipl\Html\HtmlDocument->render()
#10 /usr/share/icingaweb2/modules/incubator/vendor/gipfl/icingaweb2/src/Zf1/SimpleViewRenderer.php(65): ipl\Html\HtmlDocument->__toString()
#11 /usr/share/icingaweb2/modules/incubator/vendor/gipfl/icingaweb2/src/Zf1/SimpleViewRenderer.php(104): gipfl\IcingaWeb2\Zf1\SimpleViewRenderer->render()
#12 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker.php(272): gipfl\IcingaWeb2\Zf1\SimpleViewRenderer->postDispatch()
#13 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(518): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#14 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch()
#15 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch()
#16 /usr/share/php/Icinga/Application/Web.php(290): Zend_Controller_Front->dispatch()
#17 /usr/share/php/Icinga/Application/webrouter.php(105): Icinga\Application\Web->dispatch()
#18 /usr/share/icingaweb2/public/index.php(4): require_once('...')
#19 {main}
  thrown (ArrayRenderer.php:41)`
  

icinga2 - The Icinga 2 network monitoring daemon (version: r2.13.7-1)

Copyright (c) 2012-2023 Icinga GmbH (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <https://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: Ubuntu
  Platform version: 20.04.6 LTS (Focal Fossa)
  Kernel: Linux
  Kernel version: 5.4.0-149-generic
  Architecture: x86_64

Build information:
  Compiler: GNU 9.4.0
  Build host: runner-hh8q3bz2-project-575-concurrent-0
  OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid
  

`
Icinga Web 2 Version | 2.11.4
Git commit 11453bfa92a70a44efbf7f966f5e7f27e9300a28
PHP Version 8.1.18
Git commit date 2023-01-26
`

###

PHP 8.1.18 (cli) (built: Apr 14 2023 04:39:24) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.18, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.18, Copyright (c), by Zend Technologies


  ###

MODULE         VERSION   STATE     DESCRIPTION
director       1.10.2    enabled   Director - Config tool for Icinga 2
doc            2.11.4    enabled   Documentation module
incubator      0.18.0    enabled   Incubator provides bleeding-edge libraries
monitoring     2.11.4    enabled   Icinga monitoring module
translation    2.11.4    enabled   Translation module
