### ISSUE TITLE
Create/modify arguments on Commands failed

### ISSUE THREAD

**Issue by patschbo** [Icinga/icingaweb2-module-director#2453]
## Expected Behavior
Create a new Command and add some arguments

## Current Behavior
I could create the command but then, if i would add some arguments i get this debug output.
If i click again on the command and navigate to the arguments, the previously create argument exists, but if you click on the argument the following error comes again

```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'icinga_command_argument.uuid' in 'field list', query was: SELECT icinga_command_argument.uuid FROM icinga_command_argument WHERE (`command_id` = '248') AND (`argument_name` = '--restart')

#0 /usr/share/icingaweb2/library/vendor/Zend/Db/Statement.php(297): Zend_Db_Statement_Pdo->_execute()
#1 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Abstract.php(470): Zend_Db_Statement->execute()
#2 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query()
#3 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Abstract.php(816): Zend_Db_Adapter_Pdo_Abstract->query()
#4 /usr/share/icingaweb2/modules/director/library/Director/Db/Branch/UuidLookup.php(90): Zend_Db_Adapter_Abstract->fetchOne()
#5 /usr/share/icingaweb2/modules/director/library/Director/Db/Branch/UuidLookup.php(64): Icinga\Module\Director\Db\Branch\UuidLookup::fetchOptionalUuid()
#6 /usr/share/icingaweb2/modules/director/library/Director/Data/Db/DbObject.php(1271): Icinga\Module\Director\Db\Branch\UuidLookup::findUuidForKey()
#7 /usr/share/icingaweb2/modules/director/application/controllers/CommandController.php(109): Icinga\Module\Director\Data\Db\DbObject::load()
#8 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Director\Controllers\CommandController->argumentsAction()
#9 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch()
#10 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch()
#11 /usr/share/php/Icinga/Application/Web.php(304): Zend_Controller_Front->dispatch()
#12 /usr/share/php/Icinga/Application/webrouter.php(107): Icinga\Application\Web->dispatch()
#13 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#14 {main}
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'icinga_command_argument.uuid' in 'field list'

#0 /usr/share/icingaweb2/library/vendor/Zend/Db/Statement/Pdo.php(219): PDOStatement->execute()
#1 /usr/share/icingaweb2/library/vendor/Zend/Db/Statement.php(297): Zend_Db_Statement_Pdo->_execute()
#2 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Abstract.php(470): Zend_Db_Statement->execute()
#3 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query()
#4 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Abstract.php(816): Zend_Db_Adapter_Pdo_Abstract->query()
#5 /usr/share/icingaweb2/modules/director/library/Director/Db/Branch/UuidLookup.php(90): Zend_Db_Adapter_Abstract->fetchOne()
#6 /usr/share/icingaweb2/modules/director/library/Director/Db/Branch/UuidLookup.php(64): Icinga\Module\Director\Db\Branch\UuidLookup::fetchOptionalUuid()
#7 /usr/share/icingaweb2/modules/director/library/Director/Data/Db/DbObject.php(1271): Icinga\Module\Director\Db\Branch\UuidLookup::findUuidForKey()
#8 /usr/share/icingaweb2/modules/director/application/controllers/CommandController.php(109): Icinga\Module\Director\Data\Db\DbObject::load()
#9 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Director\Controllers\CommandController->argumentsAction()
#10 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch()
#11 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch()
#12 /usr/share/php/Icinga/Application/Web.php(304): Zend_Controller_Front->dispatch()
#13 /usr/share/php/Icinga/Application/webrouter.php(107): Icinga\Application\Web->dispatch()
#14 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#15 {main}
```

## Your Environment
* Director version (System - About): master (c487a8b4478dee3a7f6276fdf04777bff7fa485e)
* Icinga Web 2 version and modules (System - About): 2.9.5
* Icinga 2 version (`icinga2 --version`):  r2.13.2-1
* Operating System and version: 20.04.3 LTS (Focal Fossa)
* Webserver, PHP versions: Apache  2.4.41-4ubuntu3.8, PHP 7.4.3

**Comment by Thomas-Gelf** [comment]
Thanks for reporting this, has been fixed!
