### ISSUE TITLE
Deploy button not working

### ISSUE THREAD

**Issue by patschbo** [Icinga/icingaweb2-module-director#2454]
## Expected Behavior
To change a custom variable, i click on **Modify** and than after change the argument i click the Button **Override vars**.
Then i will deploy the new setting and click **Deploy** and get the following debug output.

## Current Behavior

```
Uncaught TypeError: Argument 2 passed to Icinga\Module\Director\Data\Db\DbObjectStore::load() must implement interface Ramsey\Uuid\UuidInterface, null given, called in /usr/share/icingaweb2/modules/director/library/Director/Data/Db/DbObject.php on line 1273 and defined in /usr/share/icingaweb2/modules/director/library/Director/Data/Db/DbObjectStore.php:38
Stack trace:
#0 /usr/share/icingaweb2/modules/director/library/Director/Data/Db/DbObject.php(1273): Icinga\Module\Director\Data\Db\DbObjectStore->load()
#1 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaServiceSet.php(122): Icinga\Module\Director\Data\Db\DbObject::load()
#2 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaServiceSet.php(97): Icinga\Module\Director\Objects\IcingaServiceSet->getServiceObjectsForSet()
#3 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaServiceSet.php(304): Icinga\Module\Director\Objects\IcingaServiceSet->getServiceObjects()
#4 /usr/share/icingaweb2/modules/directo

#0 [internal function]: Icinga\Application\Web->Icinga\Application\{closure}()
#1 {main}
``` 

## Your Environment
* Director version (System - About): master (c487a8b4478dee3a7f6276fdf04777bff7fa485e)
* Icinga Web 2 version and modules (System - About): 2.9.5
* Icinga 2 version (`icinga2 --version`):  r2.13.2-1
* Operating System and version: 20.04.3 LTS (Focal Fossa)
* Webserver, PHP versions: Apache  2.4.41-4ubuntu3.8, PHP 7.4.3

**Comment by Thomas-Gelf** [comment]
Should be fixed, thank you!
