### ISSUE TITLE
Director module error: Icinga\Util\Translator not found

### ISSUE THREAD

**Issue by jprusch** [Icinga/icingaweb2-module-director#2548]
## Expected Behavior
Opening the director link should display the director main screen

## Current Behavior
Instead an error message is displayed:
`Uncaught Error: Class 'Icinga\Util\Translator' not found in /usr/share/icingaweb2/modules/incubator/vendor/gipfl/icingaweb2/src/Translator.php:20
Stack trace:
#0 /usr/share/icingaweb2/modules/incubator/vendor/gipfl/translation/src/TranslationHelper.php(17): gipfl\IcingaWeb2\Translator->translate()
#1 /usr/share/icingaweb2/modules/director/library/Director/Web/Tabs/MainTabs.php(26): Icinga\Module\Director\Web\Tabs\MainTabs->translate()
#2 /usr/share/icingaweb2/modules/director/application/controllers/DashboardController.php(55): Icinga\Module\Director\Web\Tabs\MainTabs->__construct()
#3 /usr/share/icingaweb2/modules/director/application/controllers/IndexController.php(42): Icinga\Module\Director\Controllers\DashboardController->indexAction()
#4 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Director\Controllers\IndexController->indexAction()
#5 /usr/share/icingaweb2/library/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch()
#6 /usr/share/icingaweb2

#0 [internal function]: Icinga\Application\Web->Icinga\Application\{closure}()
#1 {main}`

Same error is shown with VSphereDB module on opening main screen

## Your Environment

<img width="663" alt="image" src="https://user-images.githubusercontent.com/9337414/174479035-4835c071-d7d4-499c-a952-972ce904a167.png">

**Comment by dreua** [comment]
Same story but with the freshly released Icinga Web 2 v2.11.0.
It would be nice if we could solve this in a way that not everyone needs to find this information on their own. Does icinga Web have some mechanism declare dependencies on certain versions?

**Comment by rfay** [comment]
Perhaps this has been neglected in the Ubuntu 22.04 apt repo? icingaweb2 2.11.1 is out there, but icingaweb2-module-incubator is still the old version.

```
# apt-cache policy icingaweb2-module-incubator
icingaweb2-module-incubator:
  Installed: 0.6.0-2
  Candidate: 0.6.0-2
  Version table:
 *** 0.6.0-2 500
        500 http://mirrors.linode.com/ubuntu jammy/universe amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by tuomassalo** [comment]
What is the preferred way of fixing this error on Ubuntu 20.04 or 22.04?

**Comment by Mike-Benoit** [comment]
I'm running into this issue too on Ubuntu 22.04, some instructions on a proper fix would be nice.

**Comment by Mike-Benoit** [comment]
I think I figured out the issue. Originally the "icingaweb2-module-director" package was not installed, so the IcingaWeb2 Director module in "/usr/share/icingaweb2/modules/director" was an old version. However even after installing icingaweb2-module-director from APT, it was v1.6.0 from the Ubuntu repo which was also quite old and still failed.

So I fixed it by manually installing the latest IcingaWeb2 Director module like this:
```
cd /usr/share/icingaweb2/modules
mv director director.old
git clone --branch v1.10.2 https://github.com/Icinga/icingaweb2-module-director.git director
```

Not sure why Icinga's own APT repo doesn't have a package to do this automatically, but nonetheless the above got me going again.

**Comment by lippserd** [comment]
> However even after installing icingaweb2-module-director from APT, it was v1.6.0 from the Ubuntu repo which was also quite old and still failed.

https://icinga.com/docs/icinga-director/package-installation-docs/doc/02-Installation/Ubuntu/

**Comment by RobbieTheK** [comment]
This has caused some issues on Fedora 36:

```
Icinga Web 2 Version	2.11.2
Git commit	9b6349e4a0611d9beadffb708c7ea2cb1075d229
PHP Version	8.1.12
Git commit date	2022-11-04
```

`SQLSTATE[42S02]: Base table or view not found: 1146 Table 'director.director_activity_log_remark' doesn't exist, query was: SELECT director_activity_log_remark.* FROM director_activity_log_remark WHERE (first_related_activity <= 914) AND (last_related_activity >= 815) (Pdo.php:225)`

```
#0 /usr/share/icingaweb2/library/vendor/Zend/Db/Statement.php(304): Zend_Db_Statement_Pdo->_execute()
#1 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Abstract.php(470): Zend_Db_Statement->execute()
#2 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query()
#3 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Abstract.php(725): Zend_Db_Adapter_Pdo_Abstract->query()
#4 /usr/share/icingaweb2/modules/director/library/Director/Web/Table/ActivityLogTable.php(75): Zend_Db_Adapter_Abstract->fetchAll()
#5 /usr/share/icingaweb2/modules/incubator/vendor/gipfl/icingaweb2/src/Table/QueryBasedTable.php(230): Icinga\Module\Director\Web\Table\ActivityLogTable->fetchQueryRows()
#6 /usr/share/icingaweb2/modules/incubator/vendor/gipfl/icingaweb2/src/Table/QueryBasedTable.php(164): gipfl\IcingaWeb2\Table\QueryBasedTable->fetch()
#7 /usr/share/icingaweb2/modules/incubator/vendor/gipfl/icingaweb2/src/Table/QueryBasedTable.php(115): gipfl\IcingaWeb2\Table\QueryBasedTable->fetchRows()
#8 /usr/share/icinga-php/ipl/vendor/ipl/html/src/BaseHtmlElement.php(323): gipfl\IcingaWeb2\Table\QueryBasedTable->renderContent()
#9 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(499): ipl\Html\BaseHtmlElement->renderUnwrapped()
#10 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(339): ipl\Html\HtmlDocument->render()
#11 /usr/share/icinga-php/ipl/vendor/ipl/html/src/BaseHtmlElement.php(255): ipl\Html\HtmlDocument->renderUnwrapped()
#12 /usr/share/icinga-php/ipl/vendor/ipl/html/src/BaseHtmlElement.php(323): ipl\Html\BaseHtmlElement->renderContent()
#13 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(499): ipl\Html\BaseHtmlElement->renderUnwrapped()
#14 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(369): ipl\Html\HtmlDocument->render()
#15 /usr/share/icingaweb2/modules/incubator/vendor/gipfl/icingaweb2/src/Zf1/SimpleViewRenderer.php(65): ipl\Html\HtmlDocument->__toString()
#16 /usr/share/icingaweb2/modules/incubator/vendor/gipfl/icingaweb2/src/Zf1/SimpleViewRenderer.php(104): gipfl\IcingaWeb2\Zf1\SimpleViewRenderer->render()
#17 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker.php(272): gipfl\IcingaWeb2\Zf1\SimpleViewRenderer->postDispatch()
#18 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(518): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#19 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch()
#20 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch()
#21 /usr/share/php/Icinga/Application/Web.php(290): Zend_Controller_Front->dispatch()
#22 /usr/share/php/Icinga/Application/webrouter.php(105): Icinga\Application\Web->dispatch()
#23 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#24 {main}
```
