### ISSUE TITLE
Link to a rule in service->modify throws exception 

### ISSUE THREAD

**Issue by kdeb** [Icinga/icingaweb2-module-director#2572]
## Current Behavior

If you select the link in a service (overview/services/<_service which was **created by a rule**_>/modify) which leads to the rule with which a service was created, there is an exception.

```
( ! )  Fatal error: Uncaught Error: Call to a member function toString() on  null in  /usr/share/icingaweb2/modules/director/application/controllers/ServiceController.php  on line 254

( ! ) Error: Call to a member function toString() on null in /usr/share/icingaweb2/modules/director/application/controllers/ServiceController.php on line 254

1 | 0.0001 | 407224 | {main}(  ) | .../index.php:0
2 | 0.0003 | 431288 | require_once( '/usr/share/php/Icinga/Application/webrouter.php' ) | .../index.php:4
3 | 0.0309 | 4512320 | Icinga\Application\Web->dispatch(  ) | .../webrouter.php:107
4 | 0.0309 | 4512320 | Zend_Controller_Front->dispatch(  ) | .../Web.php:304
5 | 0.0317 | 4567912 | Icinga\Web\Controller\Dispatcher->dispatch(  ) | .../Front.php:937
6 | 0.0353 | 5123872 | Icinga\Module\Director\Controllers\ServiceController->__construct(  ) | .../Dispatcher.php:59
7 | 0.0382 | 5456240 | Icinga\Module\Director\Controllers\ServiceController->init(  ) | .../ActionController.php:165
8 | 0.0382 | 5456240 | Icinga\Module\Director\Controllers\ServiceController->init(  ) | .../ServiceController.php:46
9 | 0.0569 | 7371424 | Icinga\Module\Director\Controllers\ServiceController->loadOptionalObject(  ) | .../ObjectController.php:90
10 | 0.0569 | 7371456 | Icinga\Module\Director\Controllers\ServiceController->loadObject(  ) | .../ObjectController.php:497

( ! )  Fatal error: Uncaught Zend_Controller_Response_Exception: Cannot send  headers; headers already sent in , line 0 in  /usr/share/icingaweb2/library/vendor/Zend/Controller/Plugin/Broker.php  on line 332

( ! ) Zend_Controller_Exception: Cannot send headers; headers already sent in , line 0#0 /usr/share/icingaweb2/library/vendor/Zend/Controller/Response/Abstract.php(115): Zend_Controller_Response_Abstract->canSendHeaders() #1 /usr/share/php/Icinga/Web/Controller/ActionController.php(505): Zend_Controller_Response_Abstract->setHeader() #2 /usr/share/php/Icinga/Web/Controller/ActionController.php(480): Icinga\Web\Controller\ActionController->postDispatchXhr() #3 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(512): Icinga\Web\Controller\ActionController->postDispatch() #4 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch() #5 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch() #6 /usr/share/php/Icinga/Application/Web.php(471): Zend_Controller_Front->dispatch() #7 [internal function]: Icinga\Application\Web->Icinga\Application\{closure}() #8 {main} in /usr/share/icingaweb2/library/vendor/Zend/Controller/Plugin/Broker.php on line 332

Call Stack
1 | 0.0596 | 7517112 | Icinga\Application\Web->Icinga\Application\{closure:/usr/share/php/Icinga/Application/Web.php:454-473}(  ) | .../Web.php:0
2 | 0.0596 | 7512008 | Zend_Controller_Front->dispatch(  ) | .../Web.php:471
```

## Steps to Reproduce (for bugs)

![2022-07-22 14_11_37-Icinga Web](https://user-images.githubusercontent.com/3480192/180437590-b91670c7-0756-451f-9227-2760811d1b6f.png)

![2022-07-22 13_28_51-Icinga_exception](https://user-images.githubusercontent.com/3480192/180437922-934b8c96-9f3a-4b95-a093-9fe299088bc9.png)

## Your Environment

* Director version (System - About): 1.9.1
* Icinga Web 2 version and modules (System - About): 2.9.5
* Icinga 2 version (`icinga2 --version`): r2.13.1-1
* Operating System and version: SUSE Linux Enterprise Server 15 SP3
* Webserver, PHP versions: apache/2.4.51, PHP 7.4.6

**Comment by log1-c** [comment]
See here: https://github.com/Icinga/icingaweb2-module-director/issues/2554
