### ISSUE TITLE
PHP Deprecated messages break the REST APIs json return

### ISSUE THREAD

**Issue by RafaelSche** [Icinga/icingaweb2-module-director#2575]
## Expected Behavior
```py
>>> import requests
>>> headers = requests.structures.CaseInsensitiveDict()
>>> headers['Accept'] = 'application/json'
>>> objects = requests.get('http://icinga-bullseye-server.com/director/hosts', headers=headers, auth=('admin', 'password'))
>>> objects.json()
```
Should return a json of all the hosts in the system.  
  
## Current Behavior
```py
>>> import requests
>>> headers = requests.structures.CaseInsensitiveDict()
>>> headers['Accept'] = 'application/json'
>>> objects = requests.get('http://icinga-bullseye-server.com/director/hosts', headers=headers, auth=('admin', 'password'))
>>> objects.json()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
>>> objects._content[:500]
b'<br />\n<b>Deprecated</b>:  strlen(): Passing null to parameter #1 ($string) of type string is deprecated in <b>/usr/share/icingaweb2/modules/director/library/Director/Web/Controller/ObjectsController.php</b> on line <b>88</b><br />\n{ "objects": [ <br />\n<b>Deprecated</b>:  strlen(): Passing null to parameter #1 ($string) of type string is deprecated in <b>/usr/share/icingaweb2/modules/director/library/Director/RestApi/IcingaObjectsHandler.php</b> on line <b>92</b><br />\n{\n    "address": "123.123'
>>> content = objects._content[232:]  
>>> content[:15] + content[243:260]  # that "fixes" it
b'{ "objects": [ {\n    "address": '
>>> import json
>>> objects._content = content[:15] + content[243:]
>>> objects.json()  # succeeds
```

## Possible Solution
I could disable those messages, by configuring error reporting on the server accordingly. But I feel like they should not end up in the endpoint return in any case. Although I am not familiar with PHP.

## Steps to Reproduce (for bugs)
See the code examples. I made them on a python shell.

## Your Environment
Icinga Web 2  2.11.1    
Git Commit    eecf8d9934cbf30ec063cea4a525b26bfd2bf99a 
PHP Version   8.1.8     
MODULE           VERSION   
businessprocess  2.4.0     
director         1.9.1     
doc              2.11.1    
grafana          1.4.2     
incubator        0.17.0    
monitoring       2.11.1  
  
Icinga 2 version (`icinga2 --version`): icinga2 - The Icinga 2 network monitoring daemon (version: r2.13.4-1)  
  
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"  
  
Webserver:  
Package: apache2
Version: 2.4.54-1~deb11u1
  
Python 3.9.2

**Comment by Thomas-Gelf** [comment]
Thanks for reporting this, should have been fixed yesterday with fe3d5c7
