### ISSUE TITLE
Unknown column 'o.uuid' in 'field list'

### ISSUE THREAD

**Issue by preske87** [Icinga/icingaweb2-module-director#2593]
## Expected Behavior
Accessing iCinga director and being able to see all objects

## Current Behavior
Accessing any directory screen I get the following error
```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'o.uuid' in 'field list', query was: SELECT o.object_name, o.disabled, h.object_name AS host, h.id AS host_id, h.object_type AS host_object_type, h.disabled AS host_disabled, o.id, o.uuid, CASE WHEN hsb.service_id IS NULL THEN 'n' ELSE 'y' END AS blacklisted FROM icinga_service AS o
 LEFT JOIN icinga_host AS h ON o.host_id = h.id
 LEFT JOIN icinga_host_service_blacklist AS hsb ON hsb.service_id = o.id AND hsb.host_id = o.host_id WHERE (o.object_type = 'object') AND (o.service_set_id IS NULL) ORDER BY o.object_name ASC, o.object_name ASC, h.object_name ASC LIMIT 100 (Pdo.php:225)
#0 /usr/share/icingaweb2/library/vendor/Zend/Db/Statement.php(297): Zend_Db_Statement_Pdo->_execute()
#1 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Abstract.php(470): Zend_Db_Statement->execute()
#2 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query()
#3 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Abstract.php(725): Zend_Db_Adapter_Pdo_Abstract->query()
#4 /usr/local/share/icingaweb2/modules/incubator/vendor/gipfl/icingaweb2/src/Table/ZfQueryBasedTable.php(101): Zend_Db_Adapter_Abstract->fetchAll()
#5 /usr/local/share/icingaweb2/modules/incubator/vendor/gipfl/icingaweb2/src/Table/QueryBasedTable.php(230): gipfl\IcingaWeb2\Table\ZfQueryBasedTable->fetchQueryRows()
#6 /usr/local/share/icingaweb2/modules/incubator/vendor/gipfl/icingaweb2/src/Table/QueryBasedTable.php(164): gipfl\IcingaWeb2\Table\QueryBasedTable->fetch()
#7 /usr/local/share/icingaweb2/modules/incubator/vendor/gipfl/icingaweb2/src/Table/QueryBasedTable.php(115): gipfl\IcingaWeb2\Table\QueryBasedTable->fetchRows()
#8 /usr/share/icinga-php/ipl/vendor/ipl/html/src/BaseHtmlElement.php(323): gipfl\IcingaWeb2\Table\QueryBasedTable->renderContent()
#9 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(498): ipl\Html\BaseHtmlElement->renderUnwrapped()
#10 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(339): ipl\Html\HtmlDocument->render()
#11 /usr/share/icinga-php/ipl/vendor/ipl/html/src/BaseHtmlElement.php(255): ipl\Html\HtmlDocument->renderUnwrapped()
#12 /usr/share/icinga-php/ipl/vendor/ipl/html/src/BaseHtmlElement.php(323): ipl\Html\BaseHtmlElement->renderContent()
#13 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(498): ipl\Html\BaseHtmlElement->renderUnwrapped()
#14 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(369): ipl\Html\HtmlDocument->render()
#15 /usr/local/share/icingaweb2/modules/incubator/vendor/gipfl/icingaweb2/src/Zf1/SimpleViewRenderer.php(65): ipl\Html\HtmlDocument->__toString()
#16 /usr/local/share/icingaweb2/modules/incubator/vendor/gipfl/icingaweb2/src/Zf1/SimpleViewRenderer.php(104): gipfl\IcingaWeb2\Zf1\SimpleViewRenderer->render()
#17 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker.php(272): gipfl\IcingaWeb2\Zf1\SimpleViewRenderer->postDispatch()
#18 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(518): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#19 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch()
#20 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch()
#21 /usr/share/php/Icinga/Application/Web.php(304): Zend_Controller_Front->dispatch()
#22 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
#23 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#24 {main}
```

## Possible Solution
TBD

## Steps to Reproduce (for bugs)
Access any iCinga director screen or use director API

## Your Environment
* Director version (System - About): 1.9.1
* Icinga Web 2 version and modules (System - About): 2.10.1
* Within [docker container](https://hub.docker.com/r/jordan/icinga2/#!)

**Comment by Thomas-Gelf** [comment]
The Director dashboard should show a button allowing you to apply schema migrations after an upgrade

**Comment by Thomas-Gelf** [comment]
No feedback, hope this worked out for you. Otherwise please let me know
