### ISSUE TITLE
Multiple Errors when i start the deamon

### ISSUE THREAD

**Issue by fr3ddy-sudo** [Icinga/icingaweb2-module-director#2612]
Hi Everybody,

my problem is i cant start the systemd process 

/usr/share/icingaweb2/bin/icingacli director daemon run --debug --trace
PHP Fatal error:  Uncaught Error: Undefined constant "Icinga\Module\Director\Daemon\SIGHUP" in /usr/share/icingaweb2/modules/director/library/Director/Daemon/BackgroundDaemon.php:187
Stack trace:
#0 /usr/share/icingaweb2/modules/director/library/Director/Daemon/BackgroundDaemon.php(68): Icinga\Module\Director\Daemon\BackgroundDaemon->registerSignalHandlers()
#1 /usr/share/icingaweb2/modules/director/library/Director/Daemon/BackgroundDaemon.php(52): Icinga\Module\Director\Daemon\BackgroundDaemon->initialize()
#2 /usr/share/icinga-php/vendor/vendor/react/event-loop/src/Tick/FutureTickQueue.php(46): Icinga\Module\Director\Daemon\BackgroundDaemon->Icinga\Module\Director\Daemon\{closure}()
#3 /usr/share/icinga-php/vendor/vendor/react/event-loop/src/StreamSelectLoop.php(183): React\EventLoop\Tick\FutureTickQueue->tick()
#4 /usr/share/icingaweb2/modules/director/library/Director/Daemon/BackgroundDaemon.php(55): React\EventLoop\StreamSelectLoop->run()
#5 /usr/share/icingaweb2/modules/director/application/clicommands/DaemonCommand.php(24): Icinga\Module\Director\Daemon\BackgroundDaemon->run()
#6 /usr/share/icingaweb2/library/Icinga/Cli/Loader.php(267): Icinga\Module\Director\Clicommands\DaemonCommand->runAction()
#7 /usr/share/icingaweb2/library/Icinga/Application/Cli.php(164): Icinga\Cli\Loader->dispatch()
#8 /usr/share/icingaweb2/library/Icinga/Application/Cli.php(154): Icinga\Application\Cli->dispatchOnce()
#9 /usr/share/icingaweb2/bin/icingacli(7): Icinga\Application\Cli->dispatch()
#10 {main}
  thrown in /usr/share/icingaweb2/modules/director/library/Director/Daemon/BackgroundDaemon.php on line 187

Fatal error: Uncaught Error: Undefined constant "Icinga\Module\Director\Daemon\SIGHUP" in /usr/share/icingaweb2/modules/director/library/Director/Daemon/BackgroundDaemon.php:187
Stack trace:
#0 /usr/share/icingaweb2/modules/director/library/Director/Daemon/BackgroundDaemon.php(68): Icinga\Module\Director\Daemon\BackgroundDaemon->registerSignalHandlers()
#1 /usr/share/icingaweb2/modules/director/library/Director/Daemon/BackgroundDaemon.php(52): Icinga\Module\Director\Daemon\BackgroundDaemon->initialize()
#2 /usr/share/icinga-php/vendor/vendor/react/event-loop/src/Tick/FutureTickQueue.php(46): Icinga\Module\Director\Daemon\BackgroundDaemon->Icinga\Module\Director\Daemon\{closure}()
#3 /usr/share/icinga-php/vendor/vendor/react/event-loop/src/StreamSelectLoop.php(183): React\EventLoop\Tick\FutureTickQueue->tick()
#4 /usr/share/icingaweb2/modules/director/library/Director/Daemon/BackgroundDaemon.php(55): React\EventLoop\StreamSelectLoop->run()
#5 /usr/share/icingaweb2/modules/director/application/clicommands/DaemonCommand.php(24): Icinga\Module\Director\Daemon\BackgroundDaemon->run()
#6 /usr/share/icingaweb2/library/Icinga/Cli/Loader.php(267): Icinga\Module\Director\Clicommands\DaemonCommand->runAction()
#7 /usr/share/icingaweb2/library/Icinga/Application/Cli.php(164): Icinga\Cli\Loader->dispatch()
#8 /usr/share/icingaweb2/library/Icinga/Application/Cli.php(154): Icinga\Application\Cli->dispatchOnce()
#9 /usr/share/icingaweb2/bin/icingacli(7): Icinga\Application\Cli->dispatch()
#10 {main}
  thrown in /usr/share/icingaweb2/modules/director/library/Director/Daemon/BackgroundDaemon.php on line 187

Have anyone a tip for me?

**Comment by Thomas-Gelf** [comment]
You're probably missing `php-pcntl`, please check our [dependencies](https://github.com/Icinga/icingaweb2-module-director/blob/master/doc/02-Installation.md#requirements)

**Comment by fr3ddy-sudo** [comment]
Yes you are right this paket has faild.

Now i become icingadirector[1139039]: ERROR: Cannot read enabled modules. Module directory "/etc/icingaweb2/enabledModules" is not readable

This is right because by me it is /icingaweb2/
Where can i config the right directory?

Thanks for your Help

**Comment by lippserd** [comment]
Hi,

> This is right because by me it is /icingaweb2/

Why? I don't want to start an argument about [FHS](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard), but I wouldn't put configuration anywhere else but `/etc/icingaweb2`.

All the best,
Eric

**Comment by fr3ddy-sudo** [comment]
The problem was that icingaweb2 cant access in the directory

**Comment by lippserd** [comment]
> The problem was that icingaweb2 cant access in the directory

Please elaborate. How did you instal lcinga Web and the Director?

**Comment by fr3ddy-sudo** [comment]
So,
I reinstall everything, now everything runs in /etc/icingaweb2/
Now icinga2  and icingaweb2 has no errors

Now when i wnat start the Deamon i become:

> 17:23-root@server:[~]: journalctl -xeu icinga-director.service
░░ 
░░ The job identifier is 39082 and the job result is done.
Sep 26 17:23:57 server systemd[1]: Starting Icinga Director - Monitoring Configuration...
░░ Subject: A start job for unit icinga-director.service has begun execution
░░ Defined-By: systemd
░░ Support: https://gentoo.org/support/
░░ 
░░ A start job for unit icinga-director.service has begun execution.
░░ 
░░ The job identifier is 39082.
Sep 26 17:23:57 server icingadirector[1281057]: ERROR: There is no such module or command: 'director'
Sep 26 17:23:57 server icingadirector[1281057]: USAGE: icingacli [module] <command> [action] [options]
Sep 26 17:23:57 server icingadirector[1281057]: Available commands:
Sep 26 17:23:57 server icingadirector[1281057]:   help            Help for modules, commands and actions
Sep 26 17:23:57 server icingadirector[1281057]:   module          List and handle modules
Sep 26 17:23:57 server icingadirector[1281057]:   version         Shows version of Icinga Web 2, loaded modules and>
Sep 26 17:23:57 server icingadirector[1281057]:   web
Sep 26 17:23:57 server icingadirector[1281057]: Available modules:
Sep 26 17:23:57 server icingadirector[1281057]:   setup
Sep 26 17:23:57 server icingadirector[1281057]: Global options:
Sep 26 17:23:57 server icingadirector[1281057]:   --log [t]       Log to <t>, either stderr, file or syslog (defaul>
Sep 26 17:23:57 server icingadirector[1281057]:   --log-path <f>  Which file to log into in case of --log file
Sep 26 17:23:57 server icingadirector[1281057]:   --verbose       Be verbose
Sep 26 17:23:57 server icingadirector[1281057]:   --debug         Show debug output
Sep 26 17:23:57 server icingadirector[1281057]:   --help          Show help
Sep 26 17:23:57 server icingadirector[1281057]:   --benchmark     Show benchmark summary
Sep 26 17:23:57 server icingadirector[1281057]:   --watch [s]     Refresh output every <s> seconds (default: 5)
Sep 26 17:23:57 server icingadirector[1281057]:   --version       Shows version of Icinga Web 2, loaded modules and>
Sep 26 17:23:57 server icingadirector[1281057]: Show help on a specific command : icingacli help <command>
Sep 26 17:23:57 server icingadirector[1281057]: Show help on a specific module  : icingacli help <module>
Sep 26 17:23:57 server systemd[1]: icinga-director.service: Main process exited, code=exited, status=3/NOTIMPLEMENT>
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: https://gentoo.org/support/
░░ 
░░ An ExecStart= process belonging to unit icinga-director.service has exited.
░░ 
░░ The process' exit code is 'exited' and its exit status is 3.
Sep 26 17:23:57 server systemd[1]: icinga-director.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://gentoo.org/support/
░░ 
░░ The unit icinga-director.service has entered the 'failed' state with result 'exit-code'.
Sep 26 17:23:57 server systemd[1]: Failed to start Icinga Director - Monitoring Configuration.
░░ Subject: A start job for unit icinga-director.service has failed
░░ Defined-By: systemd
░░ Support: https://gentoo.org/support/
░░ 
░░ A start job for unit icinga-director.service has finished with a failure.


I run a Gentoo System with the Portage Pakeges  the director i install from the tarbal file

**Comment by fr3ddy-sudo** [comment]
Please see this issue: https://github.com/Icinga/icingaweb2-module-director/issues/2609

Solved the last Problem 

THX everybody

**Comment by fr3ddy-sudo** [comment]
Sry now i become error by the Kikstarter:
Director Kickstart-Assistent

        Storing director_activity_log[] failed: SQLSTATE[42S22]: Column not found: 1054 Unknown column '0x' in 'field list', query was: INSERT INTO director_activity_log (object_name, action_name, object_type, old_properties, new_properties, author, change_time, checksum, parent_checksum) VALUES (?, ?, ?, ?, ?, ?, ?, 0x34e81e5a63956a2f85e68aaa83f42e2a10244e11, 0x) {array ( 'id' => NULL, 'object_name' => 'icingadb', 'action_name' => 'create', 'object_type' => 'icinga_command', 'old_properties' => NULL, 'new_properties' => '{"methods_execute":"PluginCheck","object_name":"icingadb","object_type":"external_object","timeout":60,"vars":{"icingadb_database_backlog_critical":900,"icingadb_database_backlog_warning":300,"icingadb_full_dump_duration_critical":600,"icingadb_full_dump_duration_warning":300,"icingadb_full_sync_duration_critical":600,"icingadb_full_sync_duration_warning":300,"icingadb_name":"icingadb","icingadb_redis_backlog_critical":900,"icingadb_redis_backlog_warning":300}}', 'author' => 'cn=manager,dc=frederik,dc=baess', 'change_time' => '2022-09-27 13:13:01', 'checksum' => '4�Zc�j/�抪��.*$N', 'parent_checksum' => NULL, )} (DbObject.php:934)

Datenbankressource

Die Konfiguration sieht gut aus. Dennoch kann dieser Kickstart-Assistent jederzeit neu ausgeführt werden, um geänderte oder neu erstellte Kommandodefinitionen oder neue ITL-Kommandos nach einem Icinga-2-Core-Upgrade (neu) zu importieren.
Name des Endpunkts
Icinga-Host
Port
API Benutzer
Passwort

 


Deprecated
: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in
/usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaCommand.php
on line
133

I dont know what the error is:

My input is:
Name des Endpunkts server
Icinga-Host 172.16.0.4
Port 5665
API Benutzer director
Passwort secret
