### ISSUE TITLE
Director background daemon: Call to a member function getBranch() on null (v1.10)

### ISSUE THREAD

**Issue by Yoda-BZH** [Icinga/icingaweb2-module-director#2633]
Since the [configuration-branch update](https://icinga.com/docs/icinga-director-branches/latest/doc/03-Configuration-Branches/) on director, the [background daemon](https://icinga.com/docs/icinga-director/latest/doc/75-Background-Daemon/) (icinga-director) stopped working.

## Expected Behavior

The icinga-director service should run every automation job declared (url: /director/jobs).

## Current Behavior

The service generate some errors :

```
icingadirector@servername:~$ /usr/bin/icingacli director daemon run 
UNEXPECTED: Got invalid NetString data: 
Fatal error: Uncaught Error: Call to a member function getBranch() on null in /usr/share/icingaweb2/modules/director/library/Director/Import/Sync.php:900
Stack trace:
#0 /usr/share/icingaweb2/modules/director/library/Director/Objects/SyncRule.php(158): Icinga\Module\Director\Import\Sync->apply()
#1 /usr/share/icingaweb2/modules/director/library/Director/Objects/SyncRule.php(198): Icinga\Module\Director\Objects\SyncRule->checkForChanges(true)
#2 /usr/share/icingaweb2/modules/director/library/Director/Job/SyncJob.php(56): Icinga\Module\Director\Objects\SyncRule->applyChanges()
#3 /usr/share/icingaweb2/modules/director/library/Director/Job/SyncJob.php(27): Icinga\Module\Director\Job\SyncJob->runForRule(Object(Icinga\Module\Director\Objects\SyncRule))
#4 /usr/share/icingaweb2/modules/director/library/Director/Objects/DirectorJob.php(90): Icinga\Module\Director\Job\SyncJob->run()
#5 /usr/share/icingaweb2/modules/director/application/clicommands/JobsCommand.php(36): Icinga\Module\Director\Objects\DirectorJob->run()
#6 /usr/shar in /usr/share/icingaweb2/modules/director/library/Director/Import/Sync.php on line 900
Job (JOBNAME) failed: Process exited with exit code 255
```

## Possible Solution

quick&dirty fix:
```
library/Director/Import/Sync.php
@@ -883,9 +883,11 @@ class Sync
             }
 
             $this->run->setProperties($runProperties);
+            if($this->store) {
             if (!$this->store->getBranch()->isBranch()) {
                 $this->run->store();
             }
+            }
             $this->notifyResolvers();
             if (! $this->store) {
                 $dba->commit();
@@ -895,9 +897,10 @@ class Sync
             $this->run->set('duration_ms', (int) round(
                 (microtime(true) - $this->runStartTime) * 1000
             ));
+            if($this->store) {
             if (!$this->store->getBranch()->isBranch()) {
                 $this->run->store();
-            }
+            }}
 
             Benchmark::measure('Done applying objects');
         } catch (Exception $e) {
```

## Steps to Reproduce (for bugs)

Update to v1.10 and use the background daemon.

## Your Environment

* Director version (System - About): v1.10 (support branch)
* Icinga Web 2 version and modules (System - About): 2.11.1
* Icinga 2 version (`icinga2 --version`): 2.13.5-1.bullseye
* Operating System and version: Debian 11
* Webserver, PHP versions: nginx, 7.4.30-1+deb11u1

**Comment by Yoda-BZH** [comment]
note: I'm NOT using the configuration branch feature.

**Comment by Thomas-Gelf** [comment]
Thanks for reporting this, will be fixed

**Comment by Thomas-Gelf** [comment]
Hint: the proposed workaround avoids errors, but seems to stop job execution

**Comment by Thomas-Gelf** [comment]
Update: job execution continues with that fix, but it's outcome isn't going to be stored. This has an impact on "Purge" and other cleanup mechanisms

**Comment by Thomas-Gelf** [comment]
@Yoda-BZH: please try the patch in 21bb6c5, I'll cherry-pick it to `support/1.10` and release it with v1.10.2

**Comment by Yoda-BZH** [comment]
seem good :)

Thanks !
