### ISSUE TITLE
"Not found" - when we try to edit service inside of service set - not all service sets are affected

### ISSUE THREAD

**Issue by fatslimjoe** [Icinga/icingaweb2-module-director#2748]
## Expected Behavior
open edit form of icinga2 service which is inside of some service set's in icinga director and change some values inside of fileds.

## Current Behavior
after trying to edit service inside of service set it is trowing error's (Not all service sets are affected.):

![image](https://github.com/Icinga/icingaweb2-module-director/assets/7080575/993bc3c9-87d7-4b43-b4f8-6fe258813cd6)

Error in plain text:

Not found

#0 /usr/share/icingaweb2/modules/director/library/Director/Web/Controller/ObjectController.php(507): Icinga\Module\Director\Controllers\ServiceController->loadObject()

#1 /usr/share/icingaweb2/modules/director/library/Director/Web/Controller/ObjectController.php(100): Icinga\Module\Director\Web\Controller\ObjectController->loadOptionalObject()

#2 /usr/share/icingaweb2/modules/director/library/Director/Web/Controller/ObjectController.php(69): Icinga\Module\Director\Web\Controller\ObjectController->initializeWebRequest()

#3 /usr/share/icingaweb2/modules/director/application/controllers/ServiceController.php(50): Icinga\Module\Director\Web\Controller\ObjectController->init()

#4 /usr/share/php/Icinga/Web/Controller/ActionController.php(170): Icinga\Module\Director\Controllers\ServiceController->init()

#5 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(59): Icinga\Web\Controller\ActionController->__construct()

#6 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch()

#7 /usr/share/php/Icinga/Application/Web.php(290): Zend_Controller_Front->dispatch()

#8 /usr/share/php/Icinga/Application/webrouter.php(105): Icinga\Application\Web->dispatch()

#9 /usr/share/icingaweb2/public/index.php(4): require_once(String)

#10 {main}

## Possible Solution
clone service set or create new one

## Steps to Reproduce (for bugs)
edit existing service inside of existing service set

## Your Environment

* Director version (System - About): 1.10.2 and 1.9.1
* Icinga Web 2 version and modules (System - About): 2.11.4 and 2.10.1
* Icinga 2 version (`icinga2 --version`): r2.13.7-1 and  r2.13.3-1
* Operating System and version: CentOS Linux release 7.9.2009
* Webserver, PHP versions: php 8.0.28 and php 7.3.29

We have noticed this problem after we updated our env on following version:

* Director version (System - About): 1.9.1
* Icinga Web 2 version and modules (System - About): 2.10.1
* Icinga 2 version (`icinga2 --version`): r2.13.3-1
* Operating System and version: CentOS Linux release 7.9.2009
* Webserver, PHP versions: php 7.3.29 

Issue is for quit a while existen in Icinga2 Community but didnt noticed that is any github issue open:

https://community.icinga.com/t/icinga-director-cant-add-service-template-to-service-set/11021/3

**Comment by CalmVibes** [comment]
I found a workaround - set ServiceSets to hosts through HostGroups. Not just adding a ServiceSet to the list of Services of the Host. In my case, the situation has returned to normal.

**Comment by fatslimjoe** [comment]
> I found a workaround - set ServiceSets to hosts through HostGroups. Not just adding a ServiceSet to the list of Services of the Host. In my case, the situation has returned to normal.

We are using hostgroups for apply rules for our service sets. Some was working some not ...

I have tested newest Director version 1.11.0 in our test env. It seems that they have fix it. I would say it was bug. Now in test env. didnt noticed any issue. Now director is working like a charm. Will continue with testing. 

Thx for feedback!
