### ISSUE TITLE
Uncaught error when trying to modify service details in icingadb-web overview ("findservice" instead of "edit")

### ISSUE THREAD

**Issue by bangerer** [Icinga/icingaweb2-module-director#2768]
Hi Icinga team!

## Expected Behavior
In icingadb-web -> Overview -> Services, on the details page of a service, there's a section called "Actions" and a link called "Modify".
(Assuming Director is installed and permissions for Director usage are granted).

The link itself looks like this:
https://_myserver.com_/icingaweb2/director/host/findservice?name=_myhost_&service=_myservice_

Clicking on that should take one to the corresponding "Edit service" page.
Which is the case for editing host details when clicking the "Modify" link on a host details page:
https://_myserver.com_/icingaweb2/director/host/edit?name=_myhost_

## Current Behavior
Instead, clicking the "Modify" link on a service details page yields:
`Uncaught Error: Call to a member function select() on null in /usr/share/icingaweb2/modules/director/library/Director/Monitoring.php:141`

(Full stacktrace see below.)

## Possible Solution
Changing the link target to something like this would solve the issue:
https://_myserver.com_/icingaweb2/director/host/servicesetservice?uuid=_myuuid_&service=_myservice_&set=_myserviceset_

## Steps to Reproduce
1. Have icingadb-web and director installed and full permissions in both modules granted for your icingaweb2 user.
2. Visit https://_myserver.com_/icingaweb2/icingadb/service?name=_myservice_&host.name=_myhost_
3. Find the link "Modify" round about the middle of the page and click it.

## Your Environment
* Director version: 1.10.2
* Icinga Web 2 version: 2.11.4
* icingadb: 1.0.2
* Icinga 2 version: 2.13.7
* Operating System and version: Debian 11
* Webserver, PHP versions: Apache 2.4.56, PHP 7.4.33

## Additional context
Full stacktrace:
```
Uncaught Error: Call to a member function select() on null in /usr/share/icingaweb2/modules/director/library/Director/Monitoring.php:141
Stack trace:
#0 /usr/share/icingaweb2/modules/director/library/Director/Monitoring.php(41): Icinga\Module\Director\Monitoring->prepareServiceKeyColumnQuery()
#1 /usr/share/icingaweb2/modules/director/library/Director/Monitoring.php(78): Icinga\Module\Director\Monitoring->hasService()
#2 /usr/share/icingaweb2/modules/director/application/controllers/HostController.php(37): Icinga\Module\Director\Monitoring->authCanEditService()
#3 /usr/share/icingaweb2/modules/director/library/Director/Web/Controller/ActionController.php(57): Icinga\Module\Director\Controllers\HostController->checkDirectorPermissions()
#4 /usr/share/icingaweb2/modules/director/library/Director/Web/Controller/ObjectController.php(64): Icinga\Module\Director\Web\Controller\ActionController->init()
#5 /usr/share/php/Icinga/Web/Controller/ActionController.php(170): Icinga\Module\Director\Web\Controller\ObjectCont
```

Hope this helps! - Greetings, Barney

**Comment by WhoAmI0501** [comment]
This is also happening on my setup... i cannot edit any service. Very annoying.

* Director version: 1.10.2
* Icinga Web 2 version: 2.11.4
* icingadb: 1.0.2
* Icinga 2 version: 2.14.0-1
* Operating System and version: Debian 12
* Webserver, PHP versions: Apache 2.4.57-2, PHP 8.1.23

**Comment by phil-or** [comment]
Same problem here.
- icinga-director.noarch                        1.10.2
