### ISSUE TITLE
Web triggered Sync rule fails after upgrade to Director 1.11.1

### ISSUE THREAD

**Issue by hpreusse** [Icinga/icingaweb2-module-director#2866]
## Expected Behavior
When clicking on "Trigger this Sync" in the "Sync Rule" (Icinga Director web Interface) I would expect that the Sync rule is executed and the changes are commited to the Director DB.

## Current Behavior
The Sync Rule is not executed, instead we get the followeing error message in the web interface:

Undefined index: __FORM_CSRF

#0 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(623): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(Integer, String, String, Integer, Array)
#1 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(390): Icinga\Module\Director\Web\Form\QuickForm->hasBeenSent()
#2 /usr/share/icingaweb2/modules/director/application/controllers/SyncruleController.php(57): Icinga\Module\Director\Web\Form\QuickForm->handleRequest()
#3 /usr/share/icinga-php/vendor/vendor/shardj/zf1-future/library/Zend/Controller/Action.php(516): Icinga\Module\Director\Controllers\SyncruleController->indexAction()
#4 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#5 /usr/share/icinga-php/vendor/vendor/shardj/zf1-future/library/Zend/Controller/Front.php(954): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#6 /usr/share/php/Icinga/Application/Web.php(294): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#7 /usr/share/php/Icinga/Application/webrouter.php(105): Icinga\Application\Web->dispatch()
#8 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#9 {main}

Running the Sync Rule through the defined Job still works.

## Your Environment

* Director version (System - About): 1.11.1
* Icinga Web 2 version and modules (System - About): 2.12.1
* Icinga 2 version (`icinga2 --version`): 2.14.2
* Operating System and version: Redhat 8
* Webserver, PHP versions: Apache 2.4.37, PHP 7.2.24

**Comment by hpreusse** [comment]
I just got the information, that upgrading the [php-incubator](https://github.com/Icinga/icingaweb2-module-incubator) solves the issue.

**Comment by lippserd** [comment]
> I just got the information, that upgrading the [php-incubator](https://github.com/Icinga/icingaweb2-module-incubator) solves the issue.

That is true. Sorry for the trouble.

**Comment by hpreusse** [comment]
Maybe it is a good idea to tighten the version dependency in the new director...
