### ISSUE TITLE
command field error

### ISSUE THREAD

**Issue by ysijason** [Icinga/icingaweb2-module-director#751]
Undefined offset: 17

```
#0 /usr/share/icingaweb2/modules/director/application/forms/IcingaObjectFieldForm.php(65): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(8, 'Undefined offse...', '/usr/share/icin...', 65, Array)
#1 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(311): Icinga\Module\Director\Forms\IcingaObjectFieldForm->setup()
#2 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(450): Icinga\Module\Director\Web\Form\QuickForm->prepareElements()
#3 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(463): Icinga\Module\Director\Web\Form\QuickForm->setRequest(Object(Icinga\Web\Request))
#4 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(322): Icinga\Module\Director\Web\Form\QuickForm->getRequest()
#5 /usr/share/icingaweb2/modules/director/library/Director/Web/Controller/ObjectController.php(287): Icinga\Module\Director\Web\Form\QuickForm->handleRequest()
#6 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Director\Web\Controller\ObjectController->fieldsAction()
#7 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('fieldsAction')
#8 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#9 /usr/share/php/Icinga/Application/Web.php(389): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#10 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
#11 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#12 {main}
```

**Comment by Thomas-Gelf** [comment]
Could you please pull and try again?

**Comment by ysijason** [comment]
@Thomas-Gelf 

fixed, thanks!
