### ISSUE TITLE
Director Dashboard is the only thing thats not working

### ISSUE THREAD

**Issue by rkopplin** [Icinga/icingaweb2-module-director#867]
Hello all,

Director seems to be working fine for me, creating hosts, assigning services and stuff, the only thing which is not working for me is the dashboard (overview of features)
it shows: 

Fatal error: Uncaught Error: Call to undefined method Icinga\Data\Db\DbQuery::union() in /usr/share/icingaweb2/modules/director/library/Director/Dashboard/Dashboard.php:158 Stack trace: #0 /usr/share/icingaweb2/modules/director/library/Director/Dashboard/Dashboard.php(130): Icinga\Module\Director\Dashboard\Dashboard->getObjectSummary(Array) #1 /usr/share/icingaweb2/modules/director/library/Director/Dashboard/Dashboard.php(91): Icinga\Module\Director\Dashboard\Dashboard->fetchDashletSummaries() #2 /usr/share/icingaweb2/modules/director/library/Director/Dashboard/Dashboard.php(64): Icinga\Module\Director\Dashboard\Dashboard->dashlets() #3 /usr/share/icingaweb2/modules/director/library/Director/Dashboard/Dashboard.php(69): Icinga\Module\Director\Dashboard\Dashboard->count() #4 /usr/share/icingaweb2/modules/director/application/controllers/DashboardController.php(33): Icinga\Module\Director\Dashboard\Dashboard->isAvailable() #5 /usr/share/icingaweb2/modules/director/application/controllers/IndexController.php(35): Icinga\Modu in /usr/share/icingaweb2/modules/director/library/Director/Dashboard/Dashboard.php on line 158

any idea?

**Comment by rkopplin** [comment]
closed - fixxed in #862
